/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.resources.reporting.settlement;

import com.payroc.api.core.ClientOptions;
import com.payroc.api.core.RequestOptions;
import com.payroc.api.core.pagination.PayrocPager;
import com.payroc.api.resources.reporting.settlement.requests.ListDisputesStatusesSettlementRequest;
import com.payroc.api.resources.reporting.settlement.requests.ListReportingSettlementAchDepositFeesRequest;
import com.payroc.api.resources.reporting.settlement.requests.ListReportingSettlementAchDepositsRequest;
import com.payroc.api.resources.reporting.settlement.requests.ListReportingSettlementAuthorizationsRequest;
import com.payroc.api.resources.reporting.settlement.requests.ListReportingSettlementBatchesRequest;
import com.payroc.api.resources.reporting.settlement.requests.ListReportingSettlementDisputesRequest;
import com.payroc.api.resources.reporting.settlement.requests.ListReportingSettlementTransactionsRequest;
import com.payroc.api.resources.reporting.settlement.requests.RetrieveAchDepositSettlementRequest;
import com.payroc.api.resources.reporting.settlement.requests.RetrieveAuthorizationSettlementRequest;
import com.payroc.api.resources.reporting.settlement.requests.RetrieveBatchSettlementRequest;
import com.payroc.api.resources.reporting.settlement.requests.RetrieveTransactionSettlementRequest;
import com.payroc.api.types.AchDeposit;
import com.payroc.api.types.AchDepositFee;
import com.payroc.api.types.Authorization;
import com.payroc.api.types.Batch;
import com.payroc.api.types.Dispute;
import com.payroc.api.types.DisputeStatus;
import com.payroc.api.types.Transaction;
import java.util.List;

public class SettlementClient {
    protected final ClientOptions clientOptions;

    private final RawSettlementClient rawClient;

    public SettlementClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawSettlementClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawSettlementClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Use this method to return a <a href="https://docs.payroc.com/api/pagination">paginated</a> list of batches that your merchants submitted to the processor on a specific date.
     * <p><strong>Note:</strong> If you want to view the details of a specific batch and you have its batchId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/retrieve-batch">Retrieve Batch</a> method.</p>
     * <p>Use query parameters to filter the list of results that we return, for example, to search for batches that were submitted by a specific merchant.</p>
     * <blockquote>
     * <p><strong>Important:</strong> You must provide a value for the date query parameter.</p>
     * </blockquote>
     * <p>Our gateway returns the following information about each batch in the list:</p>
     * <ul>
     * <li>Transaction information, including the number of transactions and total value of sales.</li>
     * <li>Merchant information, including the merchant ID (MID) and the processing account that the batch is associated with.</li>
     * </ul>
     */
    public PayrocPager<Batch> listBatches(ListReportingSettlementBatchesRequest request) {
        return this.rawClient.listBatches(request).body();
    }

    /**
     * Use this method to return a <a href="https://docs.payroc.com/api/pagination">paginated</a> list of batches that your merchants submitted to the processor on a specific date.
     * <p><strong>Note:</strong> If you want to view the details of a specific batch and you have its batchId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/retrieve-batch">Retrieve Batch</a> method.</p>
     * <p>Use query parameters to filter the list of results that we return, for example, to search for batches that were submitted by a specific merchant.</p>
     * <blockquote>
     * <p><strong>Important:</strong> You must provide a value for the date query parameter.</p>
     * </blockquote>
     * <p>Our gateway returns the following information about each batch in the list:</p>
     * <ul>
     * <li>Transaction information, including the number of transactions and total value of sales.</li>
     * <li>Merchant information, including the merchant ID (MID) and the processing account that the batch is associated with.</li>
     * </ul>
     */
    public PayrocPager<Batch> listBatches(
            ListReportingSettlementBatchesRequest request, RequestOptions requestOptions) {
        return this.rawClient.listBatches(request, requestOptions).body();
    }

    /**
     * Use this method to retrieve information about a batch.
     * <p><strong>Note:</strong> To retrieve a batch, you need its batchId. If you don't have the batchId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/list-batches">List Batches</a> method to search for the batch.</p>
     * <p>Our gateway returns the following information about the batch:</p>
     * <ul>
     * <li>Transaction information, including the number of transactions and total value of sales.</li>
     * <li>Merchant information, including the merchant ID (MID) and the processing account that the batch is associated with.</li>
     * </ul>
     */
    public Batch retrieveBatch(int batchId) {
        return this.rawClient.retrieveBatch(batchId).body();
    }

    /**
     * Use this method to retrieve information about a batch.
     * <p><strong>Note:</strong> To retrieve a batch, you need its batchId. If you don't have the batchId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/list-batches">List Batches</a> method to search for the batch.</p>
     * <p>Our gateway returns the following information about the batch:</p>
     * <ul>
     * <li>Transaction information, including the number of transactions and total value of sales.</li>
     * <li>Merchant information, including the merchant ID (MID) and the processing account that the batch is associated with.</li>
     * </ul>
     */
    public Batch retrieveBatch(int batchId, RetrieveBatchSettlementRequest request) {
        return this.rawClient.retrieveBatch(batchId, request).body();
    }

    /**
     * Use this method to retrieve information about a batch.
     * <p><strong>Note:</strong> To retrieve a batch, you need its batchId. If you don't have the batchId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/list-batches">List Batches</a> method to search for the batch.</p>
     * <p>Our gateway returns the following information about the batch:</p>
     * <ul>
     * <li>Transaction information, including the number of transactions and total value of sales.</li>
     * <li>Merchant information, including the merchant ID (MID) and the processing account that the batch is associated with.</li>
     * </ul>
     */
    public Batch retrieveBatch(int batchId, RetrieveBatchSettlementRequest request, RequestOptions requestOptions) {
        return this.rawClient.retrieveBatch(batchId, request, requestOptions).body();
    }

    /**
     * Use this method to return a paginated list of your merchants’ transactions.
     * <p><strong>Note:</strong> If you want to view the details of a specific transaction and you have its transactionId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/retrieve-transaction">Retrieve Transaction</a> method.</p>
     * <p>Use query parameters to filter the list of results that we return, for example, to search for transactions for a specific merchant.</p>
     * <blockquote>
     * <p><strong>Important:</strong> You must provide a value for either the date query parameter or the batchId query parameter.</p>
     * </blockquote>
     * <p>Our gateway returns the following information about each transaction in the list:</p>
     * <ul>
     * <li>Merchant and processing account that ran the transaction.</li>
     * <li>Transaction type, date, amount, and the payment method that the customer used.</li>
     * <li>Batch that contains the transaction, and authorization details for the transaction.</li>
     * <li>Processor that settled the transaction and the ACH deposit containing the transaction.</li>
     * </ul>
     */
    public PayrocPager<Transaction> listTransactions() {
        return this.rawClient.listTransactions().body();
    }

    /**
     * Use this method to return a paginated list of your merchants’ transactions.
     * <p><strong>Note:</strong> If you want to view the details of a specific transaction and you have its transactionId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/retrieve-transaction">Retrieve Transaction</a> method.</p>
     * <p>Use query parameters to filter the list of results that we return, for example, to search for transactions for a specific merchant.</p>
     * <blockquote>
     * <p><strong>Important:</strong> You must provide a value for either the date query parameter or the batchId query parameter.</p>
     * </blockquote>
     * <p>Our gateway returns the following information about each transaction in the list:</p>
     * <ul>
     * <li>Merchant and processing account that ran the transaction.</li>
     * <li>Transaction type, date, amount, and the payment method that the customer used.</li>
     * <li>Batch that contains the transaction, and authorization details for the transaction.</li>
     * <li>Processor that settled the transaction and the ACH deposit containing the transaction.</li>
     * </ul>
     */
    public PayrocPager<Transaction> listTransactions(ListReportingSettlementTransactionsRequest request) {
        return this.rawClient.listTransactions(request).body();
    }

    /**
     * Use this method to return a paginated list of your merchants’ transactions.
     * <p><strong>Note:</strong> If you want to view the details of a specific transaction and you have its transactionId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/retrieve-transaction">Retrieve Transaction</a> method.</p>
     * <p>Use query parameters to filter the list of results that we return, for example, to search for transactions for a specific merchant.</p>
     * <blockquote>
     * <p><strong>Important:</strong> You must provide a value for either the date query parameter or the batchId query parameter.</p>
     * </blockquote>
     * <p>Our gateway returns the following information about each transaction in the list:</p>
     * <ul>
     * <li>Merchant and processing account that ran the transaction.</li>
     * <li>Transaction type, date, amount, and the payment method that the customer used.</li>
     * <li>Batch that contains the transaction, and authorization details for the transaction.</li>
     * <li>Processor that settled the transaction and the ACH deposit containing the transaction.</li>
     * </ul>
     */
    public PayrocPager<Transaction> listTransactions(
            ListReportingSettlementTransactionsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listTransactions(request, requestOptions).body();
    }

    /**
     * Use this method to retrieve information about a transaction.
     * <p><strong>Note:</strong> To retrieve a transaction, you need its transactionId. If you don't have the transactionId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/list-transactions">List Transactions</a> method to search for the transaction.</p>
     * <p>Our gateway returns the following information about the transaction:</p>
     * <ul>
     * <li>Merchant and processing account that ran the transaction.</li>
     * <li>Transaction type, date, amount, and the payment method that the customer used.</li>
     * <li>Batch that contains the transaction, and authorization details for the transaction.</li>
     * <li>Processor that settled the transaction and the ACH deposit containing the transaction.</li>
     * </ul>
     */
    public Transaction retrieveTransaction(int transactionId) {
        return this.rawClient.retrieveTransaction(transactionId).body();
    }

    /**
     * Use this method to retrieve information about a transaction.
     * <p><strong>Note:</strong> To retrieve a transaction, you need its transactionId. If you don't have the transactionId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/list-transactions">List Transactions</a> method to search for the transaction.</p>
     * <p>Our gateway returns the following information about the transaction:</p>
     * <ul>
     * <li>Merchant and processing account that ran the transaction.</li>
     * <li>Transaction type, date, amount, and the payment method that the customer used.</li>
     * <li>Batch that contains the transaction, and authorization details for the transaction.</li>
     * <li>Processor that settled the transaction and the ACH deposit containing the transaction.</li>
     * </ul>
     */
    public Transaction retrieveTransaction(int transactionId, RetrieveTransactionSettlementRequest request) {
        return this.rawClient.retrieveTransaction(transactionId, request).body();
    }

    /**
     * Use this method to retrieve information about a transaction.
     * <p><strong>Note:</strong> To retrieve a transaction, you need its transactionId. If you don't have the transactionId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/list-transactions">List Transactions</a> method to search for the transaction.</p>
     * <p>Our gateway returns the following information about the transaction:</p>
     * <ul>
     * <li>Merchant and processing account that ran the transaction.</li>
     * <li>Transaction type, date, amount, and the payment method that the customer used.</li>
     * <li>Batch that contains the transaction, and authorization details for the transaction.</li>
     * <li>Processor that settled the transaction and the ACH deposit containing the transaction.</li>
     * </ul>
     */
    public Transaction retrieveTransaction(
            int transactionId, RetrieveTransactionSettlementRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .retrieveTransaction(transactionId, request, requestOptions)
                .body();
    }

    /**
     * Use this method to retrieve a <a href="https://docs.payroc.com/api/pagination">paginated</a> list of authorizations.
     * <p>Use query parameters to filter the list of results that we return, for example, to search for authorizations linked to a specific merchant.</p>
     * <blockquote>
     * <p><strong>Important:</strong> You must provide a value for either the date query parameter or the batchId query parameter.</p>
     * </blockquote>
     * <p>Our gateway returns the following information about each authorization in the list:</p>
     * <ul>
     * <li>Authorization response from the issuing bank.</li>
     * <li>Amount that the issuing bank authorized.</li>
     * <li>Merchant that ran the authorization.</li>
     * <li>Details about the customer's card, the transaction, and the batch.</li>
     * </ul>
     */
    public PayrocPager<Authorization> listAuthorizations() {
        return this.rawClient.listAuthorizations().body();
    }

    /**
     * Use this method to retrieve a <a href="https://docs.payroc.com/api/pagination">paginated</a> list of authorizations.
     * <p>Use query parameters to filter the list of results that we return, for example, to search for authorizations linked to a specific merchant.</p>
     * <blockquote>
     * <p><strong>Important:</strong> You must provide a value for either the date query parameter or the batchId query parameter.</p>
     * </blockquote>
     * <p>Our gateway returns the following information about each authorization in the list:</p>
     * <ul>
     * <li>Authorization response from the issuing bank.</li>
     * <li>Amount that the issuing bank authorized.</li>
     * <li>Merchant that ran the authorization.</li>
     * <li>Details about the customer's card, the transaction, and the batch.</li>
     * </ul>
     */
    public PayrocPager<Authorization> listAuthorizations(ListReportingSettlementAuthorizationsRequest request) {
        return this.rawClient.listAuthorizations(request).body();
    }

    /**
     * Use this method to retrieve a <a href="https://docs.payroc.com/api/pagination">paginated</a> list of authorizations.
     * <p>Use query parameters to filter the list of results that we return, for example, to search for authorizations linked to a specific merchant.</p>
     * <blockquote>
     * <p><strong>Important:</strong> You must provide a value for either the date query parameter or the batchId query parameter.</p>
     * </blockquote>
     * <p>Our gateway returns the following information about each authorization in the list:</p>
     * <ul>
     * <li>Authorization response from the issuing bank.</li>
     * <li>Amount that the issuing bank authorized.</li>
     * <li>Merchant that ran the authorization.</li>
     * <li>Details about the customer's card, the transaction, and the batch.</li>
     * </ul>
     */
    public PayrocPager<Authorization> listAuthorizations(
            ListReportingSettlementAuthorizationsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listAuthorizations(request, requestOptions).body();
    }

    /**
     * Use this method to retrieve information about an authorization.
     * <p><strong>Note:</strong> To retrieve an authorization, you need its authorizationId. If you don't have the authorizationId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/list-authorizations">List Authorizations</a> method to search for the authorization.</p>
     * <p>Our gateway returns the following information about the authorization:</p>
     * <ul>
     * <li>Authorization response from the issuing bank.</li>
     * <li>Amount that the issuing bank authorized.</li>
     * <li>Merchant that ran the authorization.</li>
     * <li>Details about the customer's card, the transaction, and the batch.</li>
     * </ul>
     */
    public Authorization retrieveAuthorization(int authorizationId) {
        return this.rawClient.retrieveAuthorization(authorizationId).body();
    }

    /**
     * Use this method to retrieve information about an authorization.
     * <p><strong>Note:</strong> To retrieve an authorization, you need its authorizationId. If you don't have the authorizationId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/list-authorizations">List Authorizations</a> method to search for the authorization.</p>
     * <p>Our gateway returns the following information about the authorization:</p>
     * <ul>
     * <li>Authorization response from the issuing bank.</li>
     * <li>Amount that the issuing bank authorized.</li>
     * <li>Merchant that ran the authorization.</li>
     * <li>Details about the customer's card, the transaction, and the batch.</li>
     * </ul>
     */
    public Authorization retrieveAuthorization(int authorizationId, RetrieveAuthorizationSettlementRequest request) {
        return this.rawClient.retrieveAuthorization(authorizationId, request).body();
    }

    /**
     * Use this method to retrieve information about an authorization.
     * <p><strong>Note:</strong> To retrieve an authorization, you need its authorizationId. If you don't have the authorizationId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/list-authorizations">List Authorizations</a> method to search for the authorization.</p>
     * <p>Our gateway returns the following information about the authorization:</p>
     * <ul>
     * <li>Authorization response from the issuing bank.</li>
     * <li>Amount that the issuing bank authorized.</li>
     * <li>Merchant that ran the authorization.</li>
     * <li>Details about the customer's card, the transaction, and the batch.</li>
     * </ul>
     */
    public Authorization retrieveAuthorization(
            int authorizationId, RetrieveAuthorizationSettlementRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .retrieveAuthorization(authorizationId, request, requestOptions)
                .body();
    }

    /**
     * Use this method to return a <a href="https://docs.payroc.com/api/pagination">paginated</a> list of disputes.
     * <p>Use query parameters to filter the list of results that we return, for example, to search for disputes linked to a specific merchant.</p>
     * <blockquote>
     * <p><strong>Important:</strong> You must provide a value for the date query parameter.</p>
     * </blockquote>
     * <p>Our gateway returns the following information about each dispute in the list:</p>
     * <ul>
     * <li>Its status, type, and description.</li>
     * <li>Transaction that the dispute is linked to, including the transaction date, merchant who ran the transaction, and the payment method that the cardholder used.</li>
     * </ul>
     */
    public PayrocPager<Dispute> listDisputes(ListReportingSettlementDisputesRequest request) {
        return this.rawClient.listDisputes(request).body();
    }

    /**
     * Use this method to return a <a href="https://docs.payroc.com/api/pagination">paginated</a> list of disputes.
     * <p>Use query parameters to filter the list of results that we return, for example, to search for disputes linked to a specific merchant.</p>
     * <blockquote>
     * <p><strong>Important:</strong> You must provide a value for the date query parameter.</p>
     * </blockquote>
     * <p>Our gateway returns the following information about each dispute in the list:</p>
     * <ul>
     * <li>Its status, type, and description.</li>
     * <li>Transaction that the dispute is linked to, including the transaction date, merchant who ran the transaction, and the payment method that the cardholder used.</li>
     * </ul>
     */
    public PayrocPager<Dispute> listDisputes(
            ListReportingSettlementDisputesRequest request, RequestOptions requestOptions) {
        return this.rawClient.listDisputes(request, requestOptions).body();
    }

    /**
     * Use this method to return the status history of a dispute.
     * <p>To view the status history of a dispute, you need its disputeId. If you don't have the disputeId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/list-disputes">List Disputes</a> method to search for the dispute.</p>
     * <p>Our gateway returns a list that contains each status change, the date it was changed, and its updated status.</p>
     */
    public List<DisputeStatus> listDisputesStatuses(int disputeId) {
        return this.rawClient.listDisputesStatuses(disputeId).body();
    }

    /**
     * Use this method to return the status history of a dispute.
     * <p>To view the status history of a dispute, you need its disputeId. If you don't have the disputeId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/list-disputes">List Disputes</a> method to search for the dispute.</p>
     * <p>Our gateway returns a list that contains each status change, the date it was changed, and its updated status.</p>
     */
    public List<DisputeStatus> listDisputesStatuses(int disputeId, ListDisputesStatusesSettlementRequest request) {
        return this.rawClient.listDisputesStatuses(disputeId, request).body();
    }

    /**
     * Use this method to return the status history of a dispute.
     * <p>To view the status history of a dispute, you need its disputeId. If you don't have the disputeId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/list-disputes">List Disputes</a> method to search for the dispute.</p>
     * <p>Our gateway returns a list that contains each status change, the date it was changed, and its updated status.</p>
     */
    public List<DisputeStatus> listDisputesStatuses(
            int disputeId, ListDisputesStatusesSettlementRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .listDisputesStatuses(disputeId, request, requestOptions)
                .body();
    }

    /**
     * Use this method to return a <a href="https://docs.payroc.com/api/pagination">paginated</a> list of ACH deposits that we paid to your merchants.
     * <p><strong>Note:</strong> If you want to view the details of a specific ACH deposit and you have its achDepositId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/retrieve-ach-deposit">Retrieve ACH Deposit</a> method.</p>
     * <p>Use query parameters to filter the list of results that we return, for example, to search for ACH deposits that we paid to a specific merchant.</p>
     * <blockquote>
     * <p><strong>Important:</strong> You must provide a value for the date query parameter.</p>
     * </blockquote>
     * <p>Our gateway returns the following information about each ACH deposit in the list:</p>
     * <ul>
     * <li>Merchant that we sent the ACH deposit to.</li>
     * <li>Total amount that we paid the merchant.</li>
     * <li>Breakdown of sales, returns, and fees.</li>
     * </ul>
     */
    public PayrocPager<AchDeposit> listAchDeposits(ListReportingSettlementAchDepositsRequest request) {
        return this.rawClient.listAchDeposits(request).body();
    }

    /**
     * Use this method to return a <a href="https://docs.payroc.com/api/pagination">paginated</a> list of ACH deposits that we paid to your merchants.
     * <p><strong>Note:</strong> If you want to view the details of a specific ACH deposit and you have its achDepositId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/retrieve-ach-deposit">Retrieve ACH Deposit</a> method.</p>
     * <p>Use query parameters to filter the list of results that we return, for example, to search for ACH deposits that we paid to a specific merchant.</p>
     * <blockquote>
     * <p><strong>Important:</strong> You must provide a value for the date query parameter.</p>
     * </blockquote>
     * <p>Our gateway returns the following information about each ACH deposit in the list:</p>
     * <ul>
     * <li>Merchant that we sent the ACH deposit to.</li>
     * <li>Total amount that we paid the merchant.</li>
     * <li>Breakdown of sales, returns, and fees.</li>
     * </ul>
     */
    public PayrocPager<AchDeposit> listAchDeposits(
            ListReportingSettlementAchDepositsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listAchDeposits(request, requestOptions).body();
    }

    /**
     * Use this method to retrieve information about an ACH deposit that we paid to a merchant.
     * <p><strong>Note:</strong> To retrieve an ACH deposit, you need its achDepositId. If you don't have the achDepositId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/list-ach-deposits">List ACH Deposits</a> method to search for the ACH deposit.</p>
     * <p>Our gateway returns the following information about the ACH deposit:</p>
     * <ul>
     * <li>Merchant that we sent the ACH deposit to.</li>
     * <li>Total amount that we paid the merchant.</li>
     * <li>Breakdown of sales, returns, and fees.</li>
     * </ul>
     */
    public AchDeposit retrieveAchDeposit(int achDepositId) {
        return this.rawClient.retrieveAchDeposit(achDepositId).body();
    }

    /**
     * Use this method to retrieve information about an ACH deposit that we paid to a merchant.
     * <p><strong>Note:</strong> To retrieve an ACH deposit, you need its achDepositId. If you don't have the achDepositId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/list-ach-deposits">List ACH Deposits</a> method to search for the ACH deposit.</p>
     * <p>Our gateway returns the following information about the ACH deposit:</p>
     * <ul>
     * <li>Merchant that we sent the ACH deposit to.</li>
     * <li>Total amount that we paid the merchant.</li>
     * <li>Breakdown of sales, returns, and fees.</li>
     * </ul>
     */
    public AchDeposit retrieveAchDeposit(int achDepositId, RetrieveAchDepositSettlementRequest request) {
        return this.rawClient.retrieveAchDeposit(achDepositId, request).body();
    }

    /**
     * Use this method to retrieve information about an ACH deposit that we paid to a merchant.
     * <p><strong>Note:</strong> To retrieve an ACH deposit, you need its achDepositId. If you don't have the achDepositId, use our <a href="https://docs.payroc.com/api/schema/reporting/settlement/list-ach-deposits">List ACH Deposits</a> method to search for the ACH deposit.</p>
     * <p>Our gateway returns the following information about the ACH deposit:</p>
     * <ul>
     * <li>Merchant that we sent the ACH deposit to.</li>
     * <li>Total amount that we paid the merchant.</li>
     * <li>Breakdown of sales, returns, and fees.</li>
     * </ul>
     */
    public AchDeposit retrieveAchDeposit(
            int achDepositId, RetrieveAchDepositSettlementRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .retrieveAchDeposit(achDepositId, request, requestOptions)
                .body();
    }

    /**
     * Retrieve a list of ACH deposit fees.
     * <blockquote>
     * <p><strong>Important:</strong> You must provide a value for either the 'date' query parameter or the 'achDepositId' query parameter.</p>
     * </blockquote>
     */
    public PayrocPager<AchDepositFee> listAchDepositFees() {
        return this.rawClient.listAchDepositFees().body();
    }

    /**
     * Retrieve a list of ACH deposit fees.
     * <blockquote>
     * <p><strong>Important:</strong> You must provide a value for either the 'date' query parameter or the 'achDepositId' query parameter.</p>
     * </blockquote>
     */
    public PayrocPager<AchDepositFee> listAchDepositFees(ListReportingSettlementAchDepositFeesRequest request) {
        return this.rawClient.listAchDepositFees(request).body();
    }

    /**
     * Retrieve a list of ACH deposit fees.
     * <blockquote>
     * <p><strong>Important:</strong> You must provide a value for either the 'date' query parameter or the 'achDepositId' query parameter.</p>
     * </blockquote>
     */
    public PayrocPager<AchDepositFee> listAchDepositFees(
            ListReportingSettlementAchDepositFeesRequest request, RequestOptions requestOptions) {
        return this.rawClient.listAchDepositFees(request, requestOptions).body();
    }
}
