/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.resources.cardpayments.refunds.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PaymentReversal.Builder.class)
public final class PaymentReversal {
    private final String idempotencyKey;

    private final Optional<String> operator;

    private final Optional<Long> amount;

    private final Map<String, Object> additionalProperties;

    private PaymentReversal(
            String idempotencyKey,
            Optional<String> operator,
            Optional<Long> amount,
            Map<String, Object> additionalProperties) {
        this.idempotencyKey = idempotencyKey;
        this.operator = operator;
        this.amount = amount;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique identifier that you generate for each request. You must use the <a href="https://www.rfc-editor.org/rfc/rfc4122">UUID v4 format</a> for the identifier. For more information about the idempotency key, go to <a href="https://docs.payroc.com/api/idempotency">Idempotency</a>.
     */
    @JsonIgnore
    public String getIdempotencyKey() {
        return idempotencyKey;
    }

    /**
     * @return Operator who reversed the payment.
     */
    @JsonProperty("operator")
    public Optional<String> getOperator() {
        return operator;
    }

    /**
     * @return Amount of the payment that the merchant wants to reverse. The value is in the currency’s lowest denomination, for example, cents.
     * <strong>Note:</strong> If the merchant doesn’t send an amount, we reverse the total amount of the transaction.
     */
    @JsonProperty("amount")
    public Optional<Long> getAmount() {
        return amount;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PaymentReversal && equalTo((PaymentReversal) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PaymentReversal other) {
        return idempotencyKey.equals(other.idempotencyKey)
                && operator.equals(other.operator)
                && amount.equals(other.amount);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.idempotencyKey, this.operator, this.amount);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdempotencyKeyStage builder() {
        return new Builder();
    }

    public interface IdempotencyKeyStage {
        /**
         * <p>Unique identifier that you generate for each request. You must use the <a href="https://www.rfc-editor.org/rfc/rfc4122">UUID v4 format</a> for the identifier. For more information about the idempotency key, go to <a href="https://docs.payroc.com/api/idempotency">Idempotency</a>.</p>
         */
        _FinalStage idempotencyKey(@NotNull String idempotencyKey);

        Builder from(PaymentReversal other);
    }

    public interface _FinalStage {
        PaymentReversal build();

        /**
         * <p>Operator who reversed the payment.</p>
         */
        _FinalStage operator(Optional<String> operator);

        _FinalStage operator(String operator);

        /**
         * <p>Amount of the payment that the merchant wants to reverse. The value is in the currency’s lowest denomination, for example, cents.
         * <strong>Note:</strong> If the merchant doesn’t send an amount, we reverse the total amount of the transaction.</p>
         */
        _FinalStage amount(Optional<Long> amount);

        _FinalStage amount(Long amount);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdempotencyKeyStage, _FinalStage {
        private String idempotencyKey;

        private Optional<Long> amount = Optional.empty();

        private Optional<String> operator = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PaymentReversal other) {
            idempotencyKey(other.getIdempotencyKey());
            operator(other.getOperator());
            amount(other.getAmount());
            return this;
        }

        /**
         * <p>Unique identifier that you generate for each request. You must use the <a href="https://www.rfc-editor.org/rfc/rfc4122">UUID v4 format</a> for the identifier. For more information about the idempotency key, go to <a href="https://docs.payroc.com/api/idempotency">Idempotency</a>.</p>
         * <p>Unique identifier that you generate for each request. You must use the <a href="https://www.rfc-editor.org/rfc/rfc4122">UUID v4 format</a> for the identifier. For more information about the idempotency key, go to <a href="https://docs.payroc.com/api/idempotency">Idempotency</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage idempotencyKey(@NotNull String idempotencyKey) {
            this.idempotencyKey = Objects.requireNonNull(idempotencyKey, "idempotencyKey must not be null");
            return this;
        }

        /**
         * <p>Amount of the payment that the merchant wants to reverse. The value is in the currency’s lowest denomination, for example, cents.
         * <strong>Note:</strong> If the merchant doesn’t send an amount, we reverse the total amount of the transaction.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage amount(Long amount) {
            this.amount = Optional.ofNullable(amount);
            return this;
        }

        /**
         * <p>Amount of the payment that the merchant wants to reverse. The value is in the currency’s lowest denomination, for example, cents.
         * <strong>Note:</strong> If the merchant doesn’t send an amount, we reverse the total amount of the transaction.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "amount", nulls = Nulls.SKIP)
        public _FinalStage amount(Optional<Long> amount) {
            this.amount = amount;
            return this;
        }

        /**
         * <p>Operator who reversed the payment.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage operator(String operator) {
            this.operator = Optional.ofNullable(operator);
            return this;
        }

        /**
         * <p>Operator who reversed the payment.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "operator", nulls = Nulls.SKIP)
        public _FinalStage operator(Optional<String> operator) {
            this.operator = operator;
            return this;
        }

        @java.lang.Override
        public PaymentReversal build() {
            return new PaymentReversal(idempotencyKey, operator, amount, additionalProperties);
        }
    }
}
