/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.resources.boarding.pricingintents;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.payroc.api.core.ClientOptions;
import com.payroc.api.core.MediaTypes;
import com.payroc.api.core.ObjectMappers;
import com.payroc.api.core.PayrocApiApiException;
import com.payroc.api.core.PayrocApiException;
import com.payroc.api.core.PayrocApiHttpResponse;
import com.payroc.api.core.QueryStringMapper;
import com.payroc.api.core.RequestOptions;
import com.payroc.api.core.pagination.AsyncPayrocPager;
import com.payroc.api.errors.BadRequestError;
import com.payroc.api.errors.ConflictError;
import com.payroc.api.errors.ForbiddenError;
import com.payroc.api.errors.InternalServerError;
import com.payroc.api.errors.NotAcceptableError;
import com.payroc.api.errors.NotFoundError;
import com.payroc.api.errors.UnauthorizedError;
import com.payroc.api.resources.boarding.pricingintents.requests.CreatePricingIntentsRequest;
import com.payroc.api.resources.boarding.pricingintents.requests.DeletePricingIntentsRequest;
import com.payroc.api.resources.boarding.pricingintents.requests.ListPricingIntentsRequest;
import com.payroc.api.resources.boarding.pricingintents.requests.PartiallyUpdatePricingIntentsRequest;
import com.payroc.api.resources.boarding.pricingintents.requests.RetrievePricingIntentsRequest;
import com.payroc.api.resources.boarding.pricingintents.requests.UpdatePricingIntentsRequest;
import com.payroc.api.types.FiveHundred;
import com.payroc.api.types.FourHundred;
import com.payroc.api.types.FourHundredFour;
import com.payroc.api.types.FourHundredNine;
import com.payroc.api.types.FourHundredOne;
import com.payroc.api.types.FourHundredSix;
import com.payroc.api.types.PaginatedPricingIntent;
import com.payroc.api.types.PricingIntent50;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawPricingIntentsClient {
    protected final ClientOptions clientOptions;

    public AsyncRawPricingIntentsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Use this method to return a <a href="https://docs.payroc.com/api/pagination">paginated</a> list of pricing intents associated with the ISV.
     * <p><strong>Note:</strong> If you want to view the details of a specific pricing intent and you have its pricingIntentId, use our <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/retrieve">Retrieve Pricing Intent</a> method.</p>
     * <p>Our gateway returns the following information about each pricing intent in the list:</p>
     * <ul>
     * <li>Information about the fees, including the base fees, gateway fees, and processor fees.</li>
     * <li>Status of the pricing intent, including whether we approved the pricing intent.</li>
     * </ul>
     * <p>For each pricing intent, we also return its pricingIntentId which you can use to perform follow-on actions.</p>
     */
    public CompletableFuture<PayrocApiHttpResponse<CompletableFuture<AsyncPayrocPager<PricingIntent50>>>> list() {
        return list(ListPricingIntentsRequest.builder().build());
    }

    /**
     * Use this method to return a <a href="https://docs.payroc.com/api/pagination">paginated</a> list of pricing intents associated with the ISV.
     * <p><strong>Note:</strong> If you want to view the details of a specific pricing intent and you have its pricingIntentId, use our <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/retrieve">Retrieve Pricing Intent</a> method.</p>
     * <p>Our gateway returns the following information about each pricing intent in the list:</p>
     * <ul>
     * <li>Information about the fees, including the base fees, gateway fees, and processor fees.</li>
     * <li>Status of the pricing intent, including whether we approved the pricing intent.</li>
     * </ul>
     * <p>For each pricing intent, we also return its pricingIntentId which you can use to perform follow-on actions.</p>
     */
    public CompletableFuture<PayrocApiHttpResponse<CompletableFuture<AsyncPayrocPager<PricingIntent50>>>> list(
            RequestOptions requestOptions) {
        return list(ListPricingIntentsRequest.builder().build(), requestOptions);
    }

    /**
     * Use this method to return a <a href="https://docs.payroc.com/api/pagination">paginated</a> list of pricing intents associated with the ISV.
     * <p><strong>Note:</strong> If you want to view the details of a specific pricing intent and you have its pricingIntentId, use our <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/retrieve">Retrieve Pricing Intent</a> method.</p>
     * <p>Our gateway returns the following information about each pricing intent in the list:</p>
     * <ul>
     * <li>Information about the fees, including the base fees, gateway fees, and processor fees.</li>
     * <li>Status of the pricing intent, including whether we approved the pricing intent.</li>
     * </ul>
     * <p>For each pricing intent, we also return its pricingIntentId which you can use to perform follow-on actions.</p>
     */
    public CompletableFuture<PayrocApiHttpResponse<CompletableFuture<AsyncPayrocPager<PricingIntent50>>>> list(
            ListPricingIntentsRequest request) {
        return list(request, null);
    }

    /**
     * Use this method to return a <a href="https://docs.payroc.com/api/pagination">paginated</a> list of pricing intents associated with the ISV.
     * <p><strong>Note:</strong> If you want to view the details of a specific pricing intent and you have its pricingIntentId, use our <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/retrieve">Retrieve Pricing Intent</a> method.</p>
     * <p>Our gateway returns the following information about each pricing intent in the list:</p>
     * <ul>
     * <li>Information about the fees, including the base fees, gateway fees, and processor fees.</li>
     * <li>Status of the pricing intent, including whether we approved the pricing intent.</li>
     * </ul>
     * <p>For each pricing intent, we also return its pricingIntentId which you can use to perform follow-on actions.</p>
     */
    public CompletableFuture<PayrocApiHttpResponse<CompletableFuture<AsyncPayrocPager<PricingIntent50>>>> list(
            ListPricingIntentsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getApiURL())
                .newBuilder()
                .addPathSegments("pricing-intents");
        if (request.getBefore().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "before", request.getBefore().get(), false);
        }
        if (request.getAfter().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "after", request.getAfter().get(), false);
        }
        if (request.getLimit().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "limit", request.getLimit().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<PayrocApiHttpResponse<CompletableFuture<AsyncPayrocPager<PricingIntent50>>>> future =
                new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        PaginatedPricingIntent parsedResponse =
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PaginatedPricingIntent.class);
                        future.complete(new PayrocApiHttpResponse<>(
                                AsyncPayrocPager.createAsync(parsedResponse, clientOptions, requestOptions), response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundred.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredOne.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FiveHundred.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new PayrocApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new PayrocApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PayrocApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Use this method to create a pricing intent that you can assign to a processing account.
     * <p>In the request, you must provide the following:</p>
     * <ul>
     * <li>Processing fees, including the pricing program and the fee to process each transaction.</li>
     * <li>Gateway fees, including the fee for each transaction handled by our gateway.</li>
     * <li>Base fees, including maintenance and PCI fees.</li>
     * </ul>
     * <p>In the response, our gateway returns information about the pricing intent and the pricingIntentId, which you need for the following methods:</p>
     * <ul>
     * <li><a href="https://docs.payroc.com/api/schema/boarding/merchant-platforms/create">Create Merchant Platform</a> - Assign the pricing intent to a processing account, when you create the merchant platform and its processing accounts.</li>
     * <li><a href="https://docs.payroc.com/api/schema/boarding/merchant-platforms/create-processing-account">Create Processing Account</a> - Assign the pricing intent to a processing account.</li>
     * <li><a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/retrieve">Retrieve Pricing Intent</a> - Retrieve information about a pricing intent.</li>
     * <li><a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/update">Update Pricing Intent</a> - Update the details of a pricing intent.</li>
     * <li><a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/delete">Delete Pricing Intent</a> - Delete a pricing intent.</li>
     * <li><a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/partially-update">Partially Update Pricing Intent</a> - Partially update the details of a pricing intent.</li>
     * </ul>
     */
    public CompletableFuture<PayrocApiHttpResponse<PricingIntent50>> create(CreatePricingIntentsRequest request) {
        return create(request, null);
    }

    /**
     * Use this method to create a pricing intent that you can assign to a processing account.
     * <p>In the request, you must provide the following:</p>
     * <ul>
     * <li>Processing fees, including the pricing program and the fee to process each transaction.</li>
     * <li>Gateway fees, including the fee for each transaction handled by our gateway.</li>
     * <li>Base fees, including maintenance and PCI fees.</li>
     * </ul>
     * <p>In the response, our gateway returns information about the pricing intent and the pricingIntentId, which you need for the following methods:</p>
     * <ul>
     * <li><a href="https://docs.payroc.com/api/schema/boarding/merchant-platforms/create">Create Merchant Platform</a> - Assign the pricing intent to a processing account, when you create the merchant platform and its processing accounts.</li>
     * <li><a href="https://docs.payroc.com/api/schema/boarding/merchant-platforms/create-processing-account">Create Processing Account</a> - Assign the pricing intent to a processing account.</li>
     * <li><a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/retrieve">Retrieve Pricing Intent</a> - Retrieve information about a pricing intent.</li>
     * <li><a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/update">Update Pricing Intent</a> - Update the details of a pricing intent.</li>
     * <li><a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/delete">Delete Pricing Intent</a> - Delete a pricing intent.</li>
     * <li><a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/partially-update">Partially Update Pricing Intent</a> - Partially update the details of a pricing intent.</li>
     * </ul>
     */
    public CompletableFuture<PayrocApiHttpResponse<PricingIntent50>> create(
            CreatePricingIntentsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getApiURL())
                .newBuilder()
                .addPathSegments("pricing-intents");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        _requestBuilder.addHeader("Idempotency-Key", request.getIdempotencyKey());
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<PayrocApiHttpResponse<PricingIntent50>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new PayrocApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PricingIntent50.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundred.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredOne.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 406:
                                future.completeExceptionally(new NotAcceptableError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredSix.class),
                                        response));
                                return;
                            case 409:
                                future.completeExceptionally(new ConflictError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredNine.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FiveHundred.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new PayrocApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new PayrocApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PayrocApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Use this method to retrieve information about a pricing intent.
     * <p>To retrieve a pricing intent, you need its pricingIntentId. Our gateway returned the pricingIntentId in the response of the <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/create">Create Pricing Intent</a> method.</p>
     * <p><strong>Note:</strong> If you don't have the pricingIntentId, use our <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/list">List Pricing Intents</a> method to search for the pricing intent.</p>
     * <p>Our gateway returns the following information about the pricing intent:</p>
     * <ul>
     * <li>Information about the fees, including the base fees, gateway fees, and processor fees.</li>
     * <li>Status of the pricing intent, including whether we approved the pricing intent.</li>
     * </ul>
     */
    public CompletableFuture<PayrocApiHttpResponse<PricingIntent50>> retrieve(String pricingIntentId) {
        return retrieve(pricingIntentId, RetrievePricingIntentsRequest.builder().build());
    }

    /**
     * Use this method to retrieve information about a pricing intent.
     * <p>To retrieve a pricing intent, you need its pricingIntentId. Our gateway returned the pricingIntentId in the response of the <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/create">Create Pricing Intent</a> method.</p>
     * <p><strong>Note:</strong> If you don't have the pricingIntentId, use our <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/list">List Pricing Intents</a> method to search for the pricing intent.</p>
     * <p>Our gateway returns the following information about the pricing intent:</p>
     * <ul>
     * <li>Information about the fees, including the base fees, gateway fees, and processor fees.</li>
     * <li>Status of the pricing intent, including whether we approved the pricing intent.</li>
     * </ul>
     */
    public CompletableFuture<PayrocApiHttpResponse<PricingIntent50>> retrieve(
            String pricingIntentId, RequestOptions requestOptions) {
        return retrieve(pricingIntentId, RetrievePricingIntentsRequest.builder().build(), requestOptions);
    }

    /**
     * Use this method to retrieve information about a pricing intent.
     * <p>To retrieve a pricing intent, you need its pricingIntentId. Our gateway returned the pricingIntentId in the response of the <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/create">Create Pricing Intent</a> method.</p>
     * <p><strong>Note:</strong> If you don't have the pricingIntentId, use our <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/list">List Pricing Intents</a> method to search for the pricing intent.</p>
     * <p>Our gateway returns the following information about the pricing intent:</p>
     * <ul>
     * <li>Information about the fees, including the base fees, gateway fees, and processor fees.</li>
     * <li>Status of the pricing intent, including whether we approved the pricing intent.</li>
     * </ul>
     */
    public CompletableFuture<PayrocApiHttpResponse<PricingIntent50>> retrieve(
            String pricingIntentId, RetrievePricingIntentsRequest request) {
        return retrieve(pricingIntentId, request, null);
    }

    /**
     * Use this method to retrieve information about a pricing intent.
     * <p>To retrieve a pricing intent, you need its pricingIntentId. Our gateway returned the pricingIntentId in the response of the <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/create">Create Pricing Intent</a> method.</p>
     * <p><strong>Note:</strong> If you don't have the pricingIntentId, use our <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/list">List Pricing Intents</a> method to search for the pricing intent.</p>
     * <p>Our gateway returns the following information about the pricing intent:</p>
     * <ul>
     * <li>Information about the fees, including the base fees, gateway fees, and processor fees.</li>
     * <li>Status of the pricing intent, including whether we approved the pricing intent.</li>
     * </ul>
     */
    public CompletableFuture<PayrocApiHttpResponse<PricingIntent50>> retrieve(
            String pricingIntentId, RetrievePricingIntentsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getApiURL())
                .newBuilder()
                .addPathSegments("pricing-intents")
                .addPathSegment(pricingIntentId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<PayrocApiHttpResponse<PricingIntent50>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new PayrocApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PricingIntent50.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundred.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredOne.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredFour.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FiveHundred.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new PayrocApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new PayrocApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PayrocApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Use this method to update the details of a pricing intent. If you update a pricing intent, it won't affect merchant that you've previously onboarded.
     * <p>To update a pricing intent, you need its pricingIntentId. Our gateway returned the pricingIntentId in the response of the <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/create">Create Pricing Intent</a> method.</p>
     * <p><strong>Note:</strong> If you don't have the pricingIntentId, use our <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/list">List Pricing Intents</a> method to search for the pricing intent.</p>
     * <p>You can update the following details about a pricing intent:</p>
     * <ul>
     * <li>Fees, including the base fees, processor fees, and gateway fees.</li>
     * <li>Custom name for the pricing intent.</li>
     * <li>Additional services that merchants can sign up for.</li>
     * </ul>
     */
    public CompletableFuture<PayrocApiHttpResponse<Void>> update(
            String pricingIntentId, UpdatePricingIntentsRequest request) {
        return update(pricingIntentId, request, null);
    }

    /**
     * Use this method to update the details of a pricing intent. If you update a pricing intent, it won't affect merchant that you've previously onboarded.
     * <p>To update a pricing intent, you need its pricingIntentId. Our gateway returned the pricingIntentId in the response of the <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/create">Create Pricing Intent</a> method.</p>
     * <p><strong>Note:</strong> If you don't have the pricingIntentId, use our <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/list">List Pricing Intents</a> method to search for the pricing intent.</p>
     * <p>You can update the following details about a pricing intent:</p>
     * <ul>
     * <li>Fees, including the base fees, processor fees, and gateway fees.</li>
     * <li>Custom name for the pricing intent.</li>
     * <li>Additional services that merchants can sign up for.</li>
     * </ul>
     */
    public CompletableFuture<PayrocApiHttpResponse<Void>> update(
            String pricingIntentId, UpdatePricingIntentsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getApiURL())
                .newBuilder()
                .addPathSegments("pricing-intents")
                .addPathSegment(pricingIntentId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new PayrocApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PUT", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<PayrocApiHttpResponse<Void>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new PayrocApiHttpResponse<>(null, response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundred.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredOne.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredFour.class),
                                        response));
                                return;
                            case 406:
                                future.completeExceptionally(new NotAcceptableError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredSix.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FiveHundred.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new PayrocApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new PayrocApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PayrocApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Use this method to delete a pricing intent.
     * <blockquote>
     * <p><strong>Important:</strong> When you delete a pricing intent, you can't recover it. You also won't be able to assign the pricing intent to a merchant's boarding application.</p>
     * </blockquote>
     * <p>To delete a pricing intent, you need its pricingIntentId. Our gateway returned the pricingIntentId in the response of the <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/create">Create Pricing Intent</a> method.</p>
     * <p><strong>Note:</strong> If you don't have the pricingIntentId, use our <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/list">List Pricing Intents</a> method to search for the pricing intent.</p>
     */
    public CompletableFuture<PayrocApiHttpResponse<Void>> delete(String pricingIntentId) {
        return delete(pricingIntentId, DeletePricingIntentsRequest.builder().build());
    }

    /**
     * Use this method to delete a pricing intent.
     * <blockquote>
     * <p><strong>Important:</strong> When you delete a pricing intent, you can't recover it. You also won't be able to assign the pricing intent to a merchant's boarding application.</p>
     * </blockquote>
     * <p>To delete a pricing intent, you need its pricingIntentId. Our gateway returned the pricingIntentId in the response of the <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/create">Create Pricing Intent</a> method.</p>
     * <p><strong>Note:</strong> If you don't have the pricingIntentId, use our <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/list">List Pricing Intents</a> method to search for the pricing intent.</p>
     */
    public CompletableFuture<PayrocApiHttpResponse<Void>> delete(
            String pricingIntentId, RequestOptions requestOptions) {
        return delete(pricingIntentId, DeletePricingIntentsRequest.builder().build(), requestOptions);
    }

    /**
     * Use this method to delete a pricing intent.
     * <blockquote>
     * <p><strong>Important:</strong> When you delete a pricing intent, you can't recover it. You also won't be able to assign the pricing intent to a merchant's boarding application.</p>
     * </blockquote>
     * <p>To delete a pricing intent, you need its pricingIntentId. Our gateway returned the pricingIntentId in the response of the <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/create">Create Pricing Intent</a> method.</p>
     * <p><strong>Note:</strong> If you don't have the pricingIntentId, use our <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/list">List Pricing Intents</a> method to search for the pricing intent.</p>
     */
    public CompletableFuture<PayrocApiHttpResponse<Void>> delete(
            String pricingIntentId, DeletePricingIntentsRequest request) {
        return delete(pricingIntentId, request, null);
    }

    /**
     * Use this method to delete a pricing intent.
     * <blockquote>
     * <p><strong>Important:</strong> When you delete a pricing intent, you can't recover it. You also won't be able to assign the pricing intent to a merchant's boarding application.</p>
     * </blockquote>
     * <p>To delete a pricing intent, you need its pricingIntentId. Our gateway returned the pricingIntentId in the response of the <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/create">Create Pricing Intent</a> method.</p>
     * <p><strong>Note:</strong> If you don't have the pricingIntentId, use our <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/list">List Pricing Intents</a> method to search for the pricing intent.</p>
     */
    public CompletableFuture<PayrocApiHttpResponse<Void>> delete(
            String pricingIntentId, DeletePricingIntentsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getApiURL())
                .newBuilder()
                .addPathSegments("pricing-intents")
                .addPathSegment(pricingIntentId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<PayrocApiHttpResponse<Void>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new PayrocApiHttpResponse<>(null, response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredOne.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredFour.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FiveHundred.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new PayrocApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new PayrocApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PayrocApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Use this method to partially update a pricing intent. Structure your request to follow the <a href="https://datatracker.ietf.org/doc/html/rfc6902">RFC 6902</a> standard.
     * <p>If you update a pricing intent, it won't affect merchants you've previously onboarded.</p>
     * <p>To update a pricing intent, you need its pricingIntentId. Our gateway returned the pricingIntentId in the response of the <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/create">Create Pricing Intent</a> method.</p>
     * <p><strong>Note:</strong> If you don't have the pricingIntentId, use our <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/list">List Pricing Intents</a> method to search for the pricing intent.</p>
     * <p>You can update the following details about a pricing intent:</p>
     * <ul>
     * <li>Fees, including the base fees, processor fees, and gateway fees.</li>
     * <li>Custom name for the pricing intent.</li>
     * <li>Additional services that merchants can sign up for.</li>
     * </ul>
     */
    public CompletableFuture<PayrocApiHttpResponse<PricingIntent50>> partiallyUpdate(
            String pricingIntentId, PartiallyUpdatePricingIntentsRequest request) {
        return partiallyUpdate(pricingIntentId, request, null);
    }

    /**
     * Use this method to partially update a pricing intent. Structure your request to follow the <a href="https://datatracker.ietf.org/doc/html/rfc6902">RFC 6902</a> standard.
     * <p>If you update a pricing intent, it won't affect merchants you've previously onboarded.</p>
     * <p>To update a pricing intent, you need its pricingIntentId. Our gateway returned the pricingIntentId in the response of the <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/create">Create Pricing Intent</a> method.</p>
     * <p><strong>Note:</strong> If you don't have the pricingIntentId, use our <a href="https://docs.payroc.com/api/schema/boarding/pricing-intents/list">List Pricing Intents</a> method to search for the pricing intent.</p>
     * <p>You can update the following details about a pricing intent:</p>
     * <ul>
     * <li>Fees, including the base fees, processor fees, and gateway fees.</li>
     * <li>Custom name for the pricing intent.</li>
     * <li>Additional services that merchants can sign up for.</li>
     * </ul>
     */
    public CompletableFuture<PayrocApiHttpResponse<PricingIntent50>> partiallyUpdate(
            String pricingIntentId, PartiallyUpdatePricingIntentsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getApiURL())
                .newBuilder()
                .addPathSegments("pricing-intents")
                .addPathSegment(pricingIntentId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        _requestBuilder.addHeader("Idempotency-Key", request.getIdempotencyKey());
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<PayrocApiHttpResponse<PricingIntent50>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new PayrocApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PricingIntent50.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundred.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredOne.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredFour.class),
                                        response));
                                return;
                            case 406:
                                future.completeExceptionally(new NotAcceptableError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredSix.class),
                                        response));
                                return;
                            case 409:
                                future.completeExceptionally(new ConflictError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredNine.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FiveHundred.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new PayrocApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new PayrocApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PayrocApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
