/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.resources.banktransferpayments;

import com.payroc.api.core.ClientOptions;
import com.payroc.api.core.Suppliers;
import com.payroc.api.resources.banktransferpayments.payments.PaymentsClient;
import com.payroc.api.resources.banktransferpayments.refunds.RefundsClient;
import java.util.function.Supplier;

public class BankTransferPaymentsClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<PaymentsClient> paymentsClient;

    protected final Supplier<RefundsClient> refundsClient;

    public BankTransferPaymentsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.paymentsClient = Suppliers.memoize(() -> new PaymentsClient(clientOptions));
        this.refundsClient = Suppliers.memoize(() -> new RefundsClient(clientOptions));
    }

    public PaymentsClient payments() {
        return this.paymentsClient.get();
    }

    public RefundsClient refunds() {
        return this.refundsClient.get();
    }
}
