/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.resources.tokenization;

import com.payroc.api.core.ClientOptions;
import com.payroc.api.core.Suppliers;
import com.payroc.api.resources.tokenization.securetokens.SecureTokensClient;
import com.payroc.api.resources.tokenization.singleusetokens.SingleUseTokensClient;
import java.util.function.Supplier;

public class TokenizationClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<SecureTokensClient> secureTokensClient;

    protected final Supplier<SingleUseTokensClient> singleUseTokensClient;

    public TokenizationClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.secureTokensClient = Suppliers.memoize(() -> new SecureTokensClient(clientOptions));
        this.singleUseTokensClient = Suppliers.memoize(() -> new SingleUseTokensClient(clientOptions));
    }

    public SecureTokensClient secureTokens() {
        return this.secureTokensClient.get();
    }

    public SingleUseTokensClient singleUseTokens() {
        return this.singleUseTokensClient.get();
    }
}
