/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.resources.payroccloud.paymentinstructions;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.payroc.api.core.ClientOptions;
import com.payroc.api.core.MediaTypes;
import com.payroc.api.core.ObjectMappers;
import com.payroc.api.core.PayrocApiApiException;
import com.payroc.api.core.PayrocApiException;
import com.payroc.api.core.PayrocApiHttpResponse;
import com.payroc.api.core.RequestOptions;
import com.payroc.api.errors.BadRequestError;
import com.payroc.api.errors.ConflictError;
import com.payroc.api.errors.ForbiddenError;
import com.payroc.api.errors.InternalServerError;
import com.payroc.api.errors.NotAcceptableError;
import com.payroc.api.errors.NotFoundError;
import com.payroc.api.errors.UnauthorizedError;
import com.payroc.api.errors.UnsupportedMediaTypeError;
import com.payroc.api.resources.payroccloud.paymentinstructions.requests.DeletePaymentInstructionsRequest;
import com.payroc.api.resources.payroccloud.paymentinstructions.requests.PaymentInstructionRequest;
import com.payroc.api.resources.payroccloud.paymentinstructions.requests.RetrievePaymentInstructionsRequest;
import com.payroc.api.types.FiveHundred;
import com.payroc.api.types.FourHundred;
import com.payroc.api.types.FourHundredFifteen;
import com.payroc.api.types.FourHundredFour;
import com.payroc.api.types.FourHundredNine;
import com.payroc.api.types.FourHundredOne;
import com.payroc.api.types.FourHundredSix;
import com.payroc.api.types.PaymentInstruction;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawPaymentInstructionsClient {
    protected final ClientOptions clientOptions;

    public RawPaymentInstructionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Use this method to submit an instruction request to initiate a sale on a payment device.
     * <p>In the request, include the order amount and currency.</p>
     * <p>When you send a successful request, our gateway returns information about the payment instruction and a paymentInstructionId, which you need for the following methods:</p>
     * <ul>
     * <li><a href="https://docs.payroc.com/api/schema/payroc-cloud/payment-instructions/retrieve">Retrieve payment instruction</a> - View the details of the payment instruction.</li>
     * <li><a href="https://docs.payroc.com/api/schema/payroc-cloud/payment-instructions/delete">Cancel payment instruction</a> - Cancel the payment instruction.</li>
     * </ul>
     */
    public PayrocApiHttpResponse<PaymentInstruction> submit(String serialNumber, PaymentInstructionRequest request) {
        return submit(serialNumber, request, null);
    }

    /**
     * Use this method to submit an instruction request to initiate a sale on a payment device.
     * <p>In the request, include the order amount and currency.</p>
     * <p>When you send a successful request, our gateway returns information about the payment instruction and a paymentInstructionId, which you need for the following methods:</p>
     * <ul>
     * <li><a href="https://docs.payroc.com/api/schema/payroc-cloud/payment-instructions/retrieve">Retrieve payment instruction</a> - View the details of the payment instruction.</li>
     * <li><a href="https://docs.payroc.com/api/schema/payroc-cloud/payment-instructions/delete">Cancel payment instruction</a> - Cancel the payment instruction.</li>
     * </ul>
     */
    public PayrocApiHttpResponse<PaymentInstruction> submit(
            String serialNumber, PaymentInstructionRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getApiURL())
                .newBuilder()
                .addPathSegments("devices")
                .addPathSegment(serialNumber)
                .addPathSegments("payment-instructions");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        _requestBuilder.addHeader("Idempotency-Key", request.getIdempotencyKey());
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new PayrocApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PaymentInstruction.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundred.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredOne.class),
                                response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredFour.class),
                                response);
                    case 406:
                        throw new NotAcceptableError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredSix.class),
                                response);
                    case 409:
                        throw new ConflictError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredNine.class),
                                response);
                    case 415:
                        throw new UnsupportedMediaTypeError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredFifteen.class),
                                response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FiveHundred.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new PayrocApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new PayrocApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Use this method to retrieve information about a payment instruction.
     * <p>To retrieve a payment instruction, you need its paymentInstructionId. Our gateway returned the paymentInstructionId in the response of the <a href="https://docs.payroc.com/api/schema/payroc-cloud/payment-instructions/submit">Submit Payment Instruction</a> method.</p>
     * <p>Our gateway returns the status of the payment instruction. If the payment device completed the payment instruction, the response also includes a link to the payment.</p>
     */
    public PayrocApiHttpResponse<PaymentInstruction> retrieve(String paymentInstructionId) {
        return retrieve(
                paymentInstructionId,
                RetrievePaymentInstructionsRequest.builder().build());
    }

    /**
     * Use this method to retrieve information about a payment instruction.
     * <p>To retrieve a payment instruction, you need its paymentInstructionId. Our gateway returned the paymentInstructionId in the response of the <a href="https://docs.payroc.com/api/schema/payroc-cloud/payment-instructions/submit">Submit Payment Instruction</a> method.</p>
     * <p>Our gateway returns the status of the payment instruction. If the payment device completed the payment instruction, the response also includes a link to the payment.</p>
     */
    public PayrocApiHttpResponse<PaymentInstruction> retrieve(
            String paymentInstructionId, RequestOptions requestOptions) {
        return retrieve(
                paymentInstructionId,
                RetrievePaymentInstructionsRequest.builder().build(),
                requestOptions);
    }

    /**
     * Use this method to retrieve information about a payment instruction.
     * <p>To retrieve a payment instruction, you need its paymentInstructionId. Our gateway returned the paymentInstructionId in the response of the <a href="https://docs.payroc.com/api/schema/payroc-cloud/payment-instructions/submit">Submit Payment Instruction</a> method.</p>
     * <p>Our gateway returns the status of the payment instruction. If the payment device completed the payment instruction, the response also includes a link to the payment.</p>
     */
    public PayrocApiHttpResponse<PaymentInstruction> retrieve(
            String paymentInstructionId, RetrievePaymentInstructionsRequest request) {
        return retrieve(paymentInstructionId, request, null);
    }

    /**
     * Use this method to retrieve information about a payment instruction.
     * <p>To retrieve a payment instruction, you need its paymentInstructionId. Our gateway returned the paymentInstructionId in the response of the <a href="https://docs.payroc.com/api/schema/payroc-cloud/payment-instructions/submit">Submit Payment Instruction</a> method.</p>
     * <p>Our gateway returns the status of the payment instruction. If the payment device completed the payment instruction, the response also includes a link to the payment.</p>
     */
    public PayrocApiHttpResponse<PaymentInstruction> retrieve(
            String paymentInstructionId, RetrievePaymentInstructionsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getApiURL())
                .newBuilder()
                .addPathSegments("payment-instructions")
                .addPathSegment(paymentInstructionId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new PayrocApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PaymentInstruction.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundred.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredOne.class),
                                response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredFour.class),
                                response);
                    case 406:
                        throw new NotAcceptableError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredSix.class),
                                response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FiveHundred.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new PayrocApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new PayrocApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Use this method to cancel a payment instruction.
     * <p>You can cancel a payment instruction only if its status is <code>inProgress</code>. To retrieve the status of a payment instruction, use our <a href="https://docs.payroc.com/api/schema/payroc-cloud/payment-instructions/retrieve">Retrieve Payment Instruction</a> method.</p>
     * <p>To cancel a payment instruction, you need its paymentInstructionId. Our gateway returned the paymentInstructionId in the response of the <a href="https://docs.payroc.com/api/schema/payroc-cloud/payment-instructions/submit">Submit Payment Instruction</a> method.</p>
     */
    public PayrocApiHttpResponse<Void> delete(String paymentInstructionId) {
        return delete(
                paymentInstructionId, DeletePaymentInstructionsRequest.builder().build());
    }

    /**
     * Use this method to cancel a payment instruction.
     * <p>You can cancel a payment instruction only if its status is <code>inProgress</code>. To retrieve the status of a payment instruction, use our <a href="https://docs.payroc.com/api/schema/payroc-cloud/payment-instructions/retrieve">Retrieve Payment Instruction</a> method.</p>
     * <p>To cancel a payment instruction, you need its paymentInstructionId. Our gateway returned the paymentInstructionId in the response of the <a href="https://docs.payroc.com/api/schema/payroc-cloud/payment-instructions/submit">Submit Payment Instruction</a> method.</p>
     */
    public PayrocApiHttpResponse<Void> delete(String paymentInstructionId, RequestOptions requestOptions) {
        return delete(
                paymentInstructionId, DeletePaymentInstructionsRequest.builder().build(), requestOptions);
    }

    /**
     * Use this method to cancel a payment instruction.
     * <p>You can cancel a payment instruction only if its status is <code>inProgress</code>. To retrieve the status of a payment instruction, use our <a href="https://docs.payroc.com/api/schema/payroc-cloud/payment-instructions/retrieve">Retrieve Payment Instruction</a> method.</p>
     * <p>To cancel a payment instruction, you need its paymentInstructionId. Our gateway returned the paymentInstructionId in the response of the <a href="https://docs.payroc.com/api/schema/payroc-cloud/payment-instructions/submit">Submit Payment Instruction</a> method.</p>
     */
    public PayrocApiHttpResponse<Void> delete(String paymentInstructionId, DeletePaymentInstructionsRequest request) {
        return delete(paymentInstructionId, request, null);
    }

    /**
     * Use this method to cancel a payment instruction.
     * <p>You can cancel a payment instruction only if its status is <code>inProgress</code>. To retrieve the status of a payment instruction, use our <a href="https://docs.payroc.com/api/schema/payroc-cloud/payment-instructions/retrieve">Retrieve Payment Instruction</a> method.</p>
     * <p>To cancel a payment instruction, you need its paymentInstructionId. Our gateway returned the paymentInstructionId in the response of the <a href="https://docs.payroc.com/api/schema/payroc-cloud/payment-instructions/submit">Submit Payment Instruction</a> method.</p>
     */
    public PayrocApiHttpResponse<Void> delete(
            String paymentInstructionId, DeletePaymentInstructionsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getApiURL())
                .newBuilder()
                .addPathSegments("payment-instructions")
                .addPathSegment(paymentInstructionId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new PayrocApiHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundred.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredOne.class),
                                response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredFour.class),
                                response);
                    case 406:
                        throw new NotAcceptableError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredSix.class),
                                response);
                    case 409:
                        throw new ConflictError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredNine.class),
                                response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FiveHundred.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new PayrocApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new PayrocApiException("Network error executing HTTP request", e);
        }
    }
}
