/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.resources.hostedfields;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.payroc.api.core.ClientOptions;
import com.payroc.api.core.MediaTypes;
import com.payroc.api.core.ObjectMappers;
import com.payroc.api.core.PayrocApiApiException;
import com.payroc.api.core.PayrocApiException;
import com.payroc.api.core.PayrocApiHttpResponse;
import com.payroc.api.core.RequestOptions;
import com.payroc.api.errors.BadRequestError;
import com.payroc.api.errors.ConflictError;
import com.payroc.api.errors.ForbiddenError;
import com.payroc.api.errors.InternalServerError;
import com.payroc.api.errors.NotAcceptableError;
import com.payroc.api.errors.UnauthorizedError;
import com.payroc.api.errors.UnsupportedMediaTypeError;
import com.payroc.api.resources.hostedfields.requests.HostedFieldsCreateSessionRequest;
import com.payroc.api.types.FiveHundred;
import com.payroc.api.types.FourHundred;
import com.payroc.api.types.FourHundredFifteen;
import com.payroc.api.types.FourHundredNine;
import com.payroc.api.types.FourHundredOne;
import com.payroc.api.types.FourHundredSix;
import com.payroc.api.types.HostedFieldsCreateSessionResponse;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawHostedFieldsClient {
    protected final ClientOptions clientOptions;

    public RawHostedFieldsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Use this method to create a Hosted Fields session token. You need to generate a new session token each time you load Hosted Fields on a webpage.
     * <p>In your request, you need to indicate whether the merchant is using Hosted Fields to run a sale, save payment details, or update saved payment details.</p>
     * <p>In the response, our gateway returns the session token and the time that it expires. You need the session token when you configure the JavaScript for Hosted Fields.</p>
     * <p>For more information about adding Hosted Fields to a webpage, go to <a href="https://docs.payroc.com/guides/take-payments/hosted-fields">Hosted Fields</a>.</p>
     */
    public PayrocApiHttpResponse<HostedFieldsCreateSessionResponse> create(
            String processingTerminalId, HostedFieldsCreateSessionRequest request) {
        return create(processingTerminalId, request, null);
    }

    /**
     * Use this method to create a Hosted Fields session token. You need to generate a new session token each time you load Hosted Fields on a webpage.
     * <p>In your request, you need to indicate whether the merchant is using Hosted Fields to run a sale, save payment details, or update saved payment details.</p>
     * <p>In the response, our gateway returns the session token and the time that it expires. You need the session token when you configure the JavaScript for Hosted Fields.</p>
     * <p>For more information about adding Hosted Fields to a webpage, go to <a href="https://docs.payroc.com/guides/take-payments/hosted-fields">Hosted Fields</a>.</p>
     */
    public PayrocApiHttpResponse<HostedFieldsCreateSessionResponse> create(
            String processingTerminalId, HostedFieldsCreateSessionRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getApiURL())
                .newBuilder()
                .addPathSegments("processing-terminals")
                .addPathSegment(processingTerminalId)
                .addPathSegments("hosted-fields-sessions");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        _requestBuilder.addHeader("Idempotency-Key", request.getIdempotencyKey());
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new PayrocApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBodyString, HostedFieldsCreateSessionResponse.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundred.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredOne.class),
                                response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 406:
                        throw new NotAcceptableError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredSix.class),
                                response);
                    case 409:
                        throw new ConflictError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredNine.class),
                                response);
                    case 415:
                        throw new UnsupportedMediaTypeError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredFifteen.class),
                                response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FiveHundred.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new PayrocApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new PayrocApiException("Network error executing HTTP request", e);
        }
    }
}
