/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.resources.paymentlinks.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ListPaymentLinksRequestChargeType {
    public static final ListPaymentLinksRequestChargeType PRESET =
            new ListPaymentLinksRequestChargeType(Value.PRESET, "preset");

    public static final ListPaymentLinksRequestChargeType PROMPT =
            new ListPaymentLinksRequestChargeType(Value.PROMPT, "prompt");

    private final Value value;

    private final String string;

    ListPaymentLinksRequestChargeType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ListPaymentLinksRequestChargeType
                        && this.string.equals(((ListPaymentLinksRequestChargeType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case PRESET:
                return visitor.visitPreset();
            case PROMPT:
                return visitor.visitPrompt();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ListPaymentLinksRequestChargeType valueOf(String value) {
        switch (value) {
            case "preset":
                return PRESET;
            case "prompt":
                return PROMPT;
            default:
                return new ListPaymentLinksRequestChargeType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PRESET,

        PROMPT,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitPreset();

        T visitPrompt();

        T visitUnknown(String unknownType);
    }
}
