/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.resources.boarding.processingaccounts.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateTerminalOrderShippingAddress.Builder.class)
public final class CreateTerminalOrderShippingAddress {
    private final String recipientName;

    private final Optional<String> businessName;

    private final String addressLine1;

    private final Optional<String> addressLine2;

    private final String city;

    private final String state;

    private final String postalCode;

    private final String email;

    private final Optional<String> phone;

    private final Map<String, Object> additionalProperties;

    private CreateTerminalOrderShippingAddress(
            String recipientName,
            Optional<String> businessName,
            String addressLine1,
            Optional<String> addressLine2,
            String city,
            String state,
            String postalCode,
            String email,
            Optional<String> phone,
            Map<String, Object> additionalProperties) {
        this.recipientName = recipientName;
        this.businessName = businessName;
        this.addressLine1 = addressLine1;
        this.addressLine2 = addressLine2;
        this.city = city;
        this.state = state;
        this.postalCode = postalCode;
        this.email = email;
        this.phone = phone;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Name of the person receiving the shipment.
     */
    @JsonProperty("recipientName")
    public String getRecipientName() {
        return recipientName;
    }

    /**
     * @return Name of the business receiving the shipment.
     */
    @JsonProperty("businessName")
    public Optional<String> getBusinessName() {
        return businessName;
    }

    /**
     * @return First line of the shipment address.
     */
    @JsonProperty("addressLine1")
    public String getAddressLine1() {
        return addressLine1;
    }

    /**
     * @return Second line of the shipment address.
     */
    @JsonProperty("addressLine2")
    public Optional<String> getAddressLine2() {
        return addressLine2;
    }

    /**
     * @return City of the shipment address.
     */
    @JsonProperty("city")
    public String getCity() {
        return city;
    }

    /**
     * @return State of the shipment address.
     */
    @JsonProperty("state")
    public String getState() {
        return state;
    }

    /**
     * @return Postal code of the shipment address.
     */
    @JsonProperty("postalCode")
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * @return Contact email address for the shipment.
     */
    @JsonProperty("email")
    public String getEmail() {
        return email;
    }

    /**
     * @return Contact number for the shipment.
     */
    @JsonProperty("phone")
    public Optional<String> getPhone() {
        return phone;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateTerminalOrderShippingAddress
                && equalTo((CreateTerminalOrderShippingAddress) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateTerminalOrderShippingAddress other) {
        return recipientName.equals(other.recipientName)
                && businessName.equals(other.businessName)
                && addressLine1.equals(other.addressLine1)
                && addressLine2.equals(other.addressLine2)
                && city.equals(other.city)
                && state.equals(other.state)
                && postalCode.equals(other.postalCode)
                && email.equals(other.email)
                && phone.equals(other.phone);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.recipientName,
                this.businessName,
                this.addressLine1,
                this.addressLine2,
                this.city,
                this.state,
                this.postalCode,
                this.email,
                this.phone);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static RecipientNameStage builder() {
        return new Builder();
    }

    public interface RecipientNameStage {
        /**
         * <p>Name of the person receiving the shipment.</p>
         */
        AddressLine1Stage recipientName(@NotNull String recipientName);

        Builder from(CreateTerminalOrderShippingAddress other);
    }

    public interface AddressLine1Stage {
        /**
         * <p>First line of the shipment address.</p>
         */
        CityStage addressLine1(@NotNull String addressLine1);
    }

    public interface CityStage {
        /**
         * <p>City of the shipment address.</p>
         */
        StateStage city(@NotNull String city);
    }

    public interface StateStage {
        /**
         * <p>State of the shipment address.</p>
         */
        PostalCodeStage state(@NotNull String state);
    }

    public interface PostalCodeStage {
        /**
         * <p>Postal code of the shipment address.</p>
         */
        EmailStage postalCode(@NotNull String postalCode);
    }

    public interface EmailStage {
        /**
         * <p>Contact email address for the shipment.</p>
         */
        _FinalStage email(@NotNull String email);
    }

    public interface _FinalStage {
        CreateTerminalOrderShippingAddress build();

        /**
         * <p>Name of the business receiving the shipment.</p>
         */
        _FinalStage businessName(Optional<String> businessName);

        _FinalStage businessName(String businessName);

        /**
         * <p>Second line of the shipment address.</p>
         */
        _FinalStage addressLine2(Optional<String> addressLine2);

        _FinalStage addressLine2(String addressLine2);

        /**
         * <p>Contact number for the shipment.</p>
         */
        _FinalStage phone(Optional<String> phone);

        _FinalStage phone(String phone);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements RecipientNameStage,
                    AddressLine1Stage,
                    CityStage,
                    StateStage,
                    PostalCodeStage,
                    EmailStage,
                    _FinalStage {
        private String recipientName;

        private String addressLine1;

        private String city;

        private String state;

        private String postalCode;

        private String email;

        private Optional<String> phone = Optional.empty();

        private Optional<String> addressLine2 = Optional.empty();

        private Optional<String> businessName = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateTerminalOrderShippingAddress other) {
            recipientName(other.getRecipientName());
            businessName(other.getBusinessName());
            addressLine1(other.getAddressLine1());
            addressLine2(other.getAddressLine2());
            city(other.getCity());
            state(other.getState());
            postalCode(other.getPostalCode());
            email(other.getEmail());
            phone(other.getPhone());
            return this;
        }

        /**
         * <p>Name of the person receiving the shipment.</p>
         * <p>Name of the person receiving the shipment.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("recipientName")
        public AddressLine1Stage recipientName(@NotNull String recipientName) {
            this.recipientName = Objects.requireNonNull(recipientName, "recipientName must not be null");
            return this;
        }

        /**
         * <p>First line of the shipment address.</p>
         * <p>First line of the shipment address.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("addressLine1")
        public CityStage addressLine1(@NotNull String addressLine1) {
            this.addressLine1 = Objects.requireNonNull(addressLine1, "addressLine1 must not be null");
            return this;
        }

        /**
         * <p>City of the shipment address.</p>
         * <p>City of the shipment address.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("city")
        public StateStage city(@NotNull String city) {
            this.city = Objects.requireNonNull(city, "city must not be null");
            return this;
        }

        /**
         * <p>State of the shipment address.</p>
         * <p>State of the shipment address.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("state")
        public PostalCodeStage state(@NotNull String state) {
            this.state = Objects.requireNonNull(state, "state must not be null");
            return this;
        }

        /**
         * <p>Postal code of the shipment address.</p>
         * <p>Postal code of the shipment address.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("postalCode")
        public EmailStage postalCode(@NotNull String postalCode) {
            this.postalCode = Objects.requireNonNull(postalCode, "postalCode must not be null");
            return this;
        }

        /**
         * <p>Contact email address for the shipment.</p>
         * <p>Contact email address for the shipment.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("email")
        public _FinalStage email(@NotNull String email) {
            this.email = Objects.requireNonNull(email, "email must not be null");
            return this;
        }

        /**
         * <p>Contact number for the shipment.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage phone(String phone) {
            this.phone = Optional.ofNullable(phone);
            return this;
        }

        /**
         * <p>Contact number for the shipment.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "phone", nulls = Nulls.SKIP)
        public _FinalStage phone(Optional<String> phone) {
            this.phone = phone;
            return this;
        }

        /**
         * <p>Second line of the shipment address.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addressLine2(String addressLine2) {
            this.addressLine2 = Optional.ofNullable(addressLine2);
            return this;
        }

        /**
         * <p>Second line of the shipment address.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "addressLine2", nulls = Nulls.SKIP)
        public _FinalStage addressLine2(Optional<String> addressLine2) {
            this.addressLine2 = addressLine2;
            return this;
        }

        /**
         * <p>Name of the business receiving the shipment.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage businessName(String businessName) {
            this.businessName = Optional.ofNullable(businessName);
            return this;
        }

        /**
         * <p>Name of the business receiving the shipment.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "businessName", nulls = Nulls.SKIP)
        public _FinalStage businessName(Optional<String> businessName) {
            this.businessName = businessName;
            return this;
        }

        @java.lang.Override
        public CreateTerminalOrderShippingAddress build() {
            return new CreateTerminalOrderShippingAddress(
                    recipientName,
                    businessName,
                    addressLine1,
                    addressLine2,
                    city,
                    state,
                    postalCode,
                    email,
                    phone,
                    additionalProperties);
        }
    }
}
