/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.resources.boarding.processingaccounts.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.annotation.JsonValue;
import com.payroc.api.types.PricingAgreementReminder;
import java.util.Objects;
import java.util.Optional;

public final class CreateReminderProcessingAccountsResponse {
    private final Value value;

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    private CreateReminderProcessingAccountsResponse(Value value) {
        this.value = value;
    }

    public <T> T visit(Visitor<T> visitor) {
        return value.visit(visitor);
    }

    public static CreateReminderProcessingAccountsResponse pricingAgreement(PricingAgreementReminder value) {
        return new CreateReminderProcessingAccountsResponse(new PricingAgreementValue(value));
    }

    public boolean isPricingAgreement() {
        return value instanceof PricingAgreementValue;
    }

    public boolean _isUnknown() {
        return value instanceof _UnknownValue;
    }

    public Optional<PricingAgreementReminder> getPricingAgreement() {
        if (isPricingAgreement()) {
            return Optional.of(((PricingAgreementValue) value).value);
        }
        return Optional.empty();
    }

    public Optional<Object> _getUnknown() {
        if (_isUnknown()) {
            return Optional.of(((_UnknownValue) value).value);
        }
        return Optional.empty();
    }

    @JsonValue
    private Value getValue() {
        return this.value;
    }

    public interface Visitor<T> {
        T visitPricingAgreement(PricingAgreementReminder pricingAgreement);

        T _visitUnknown(Object unknownType);
    }

    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = true, defaultImpl = _UnknownValue.class)
    @JsonSubTypes(@JsonSubTypes.Type(PricingAgreementValue.class))
    @JsonIgnoreProperties(ignoreUnknown = true)
    private interface Value {
        <T> T visit(Visitor<T> visitor);
    }

    @JsonTypeName("pricingAgreement")
    @JsonIgnoreProperties("type")
    private static final class PricingAgreementValue implements Value {
        @JsonUnwrapped
        private PricingAgreementReminder value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private PricingAgreementValue() {}

        private PricingAgreementValue(PricingAgreementReminder value) {
            this.value = value;
        }

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor.visitPricingAgreement(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof PricingAgreementValue && equalTo((PricingAgreementValue) other);
        }

        private boolean equalTo(PricingAgreementValue other) {
            return value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.value);
        }

        @java.lang.Override
        public String toString() {
            return "CreateReminderProcessingAccountsResponse{" + "value: " + value + "}";
        }
    }

    @JsonIgnoreProperties("type")
    private static final class _UnknownValue implements Value {
        private String type;

        @JsonValue
        private Object value;

        @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
        private _UnknownValue(@JsonProperty("value") Object value) {}

        @java.lang.Override
        public <T> T visit(Visitor<T> visitor) {
            return visitor._visitUnknown(value);
        }

        @java.lang.Override
        public boolean equals(Object other) {
            if (this == other) return true;
            return other instanceof _UnknownValue && equalTo((_UnknownValue) other);
        }

        private boolean equalTo(_UnknownValue other) {
            return type.equals(other.type) && value.equals(other.value);
        }

        @java.lang.Override
        public int hashCode() {
            return Objects.hash(this.type, this.value);
        }

        @java.lang.Override
        public String toString() {
            return "CreateReminderProcessingAccountsResponse{" + "type: " + type + ", value: " + value + "}";
        }
    }
}
