/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.resources.funding.fundinginstructions.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import com.payroc.api.types.IInstruction;
import com.payroc.api.types.InstructionMerchantsItem;
import com.payroc.api.types.InstructionStatus;
import com.payroc.api.types.Link;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListFundingInstructionsResponseDataItem.Builder.class)
public final class ListFundingInstructionsResponseDataItem implements IInstruction {
    private final Optional<Integer> instructionId;

    private final Optional<String> createdDate;

    private final Optional<String> lastModifiedDate;

    private final Optional<InstructionStatus> status;

    private final Optional<List<InstructionMerchantsItem>> merchants;

    private final Optional<Map<String, String>> metadata;

    private final Optional<Link> link;

    private final Map<String, Object> additionalProperties;

    private ListFundingInstructionsResponseDataItem(
            Optional<Integer> instructionId,
            Optional<String> createdDate,
            Optional<String> lastModifiedDate,
            Optional<InstructionStatus> status,
            Optional<List<InstructionMerchantsItem>> merchants,
            Optional<Map<String, String>> metadata,
            Optional<Link> link,
            Map<String, Object> additionalProperties) {
        this.instructionId = instructionId;
        this.createdDate = createdDate;
        this.lastModifiedDate = lastModifiedDate;
        this.status = status;
        this.merchants = merchants;
        this.metadata = metadata;
        this.link = link;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique identifier that we assigned to the funding instruction.
     */
    @JsonProperty("instructionId")
    @java.lang.Override
    public Optional<Integer> getInstructionId() {
        return instructionId;
    }

    /**
     * @return Date that we created the funding instruction. The date format follows the <a href="https://www.iso.org/iso-8601-date-and-time-format.html">ISO 8601</a> standard.
     */
    @JsonProperty("createdDate")
    @java.lang.Override
    public Optional<String> getCreatedDate() {
        return createdDate;
    }

    /**
     * @return Date of the most recent change to the funding instruction. The date format follows the <a href="https://www.iso.org/iso-8601-date-and-time-format.html">ISO 8601</a> standard.
     */
    @JsonProperty("lastModifiedDate")
    @java.lang.Override
    public Optional<String> getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * @return Status of the funding instruction. Our gateway returns one of the following values:
     * <ul>
     * <li><code>accepted</code> - We have received the funding instruction but have not yet reviewed it.</li>
     * <li><code>pending</code> - We have received the funding instruction and we are reviewing it.</li>
     * <li><code>completed</code> - We have reviewed and processed the funding instruction.</li>
     * </ul>
     */
    @JsonProperty("status")
    public Optional<InstructionStatus> getStatus() {
        return status;
    }

    /**
     * @return Array of merchants objects. Each object specifies the merchant whose funding balance we distribute and who you want to send the funds to.
     */
    @JsonProperty("merchants")
    public Optional<List<InstructionMerchantsItem>> getMerchants() {
        return merchants;
    }

    /**
     * @return <a href="https://docs.payroc.com/api/metadata">Metadata</a> object you can use to include custom data with your request.
     */
    @JsonProperty("metadata")
    @java.lang.Override
    public Optional<Map<String, String>> getMetadata() {
        return metadata;
    }

    @JsonProperty("link")
    public Optional<Link> getLink() {
        return link;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListFundingInstructionsResponseDataItem
                && equalTo((ListFundingInstructionsResponseDataItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListFundingInstructionsResponseDataItem other) {
        return instructionId.equals(other.instructionId)
                && createdDate.equals(other.createdDate)
                && lastModifiedDate.equals(other.lastModifiedDate)
                && status.equals(other.status)
                && merchants.equals(other.merchants)
                && metadata.equals(other.metadata)
                && link.equals(other.link);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.instructionId,
                this.createdDate,
                this.lastModifiedDate,
                this.status,
                this.merchants,
                this.metadata,
                this.link);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> instructionId = Optional.empty();

        private Optional<String> createdDate = Optional.empty();

        private Optional<String> lastModifiedDate = Optional.empty();

        private Optional<InstructionStatus> status = Optional.empty();

        private Optional<List<InstructionMerchantsItem>> merchants = Optional.empty();

        private Optional<Map<String, String>> metadata = Optional.empty();

        private Optional<Link> link = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListFundingInstructionsResponseDataItem other) {
            instructionId(other.getInstructionId());
            createdDate(other.getCreatedDate());
            lastModifiedDate(other.getLastModifiedDate());
            status(other.getStatus());
            merchants(other.getMerchants());
            metadata(other.getMetadata());
            link(other.getLink());
            return this;
        }

        /**
         * <p>Unique identifier that we assigned to the funding instruction.</p>
         */
        @JsonSetter(value = "instructionId", nulls = Nulls.SKIP)
        public Builder instructionId(Optional<Integer> instructionId) {
            this.instructionId = instructionId;
            return this;
        }

        public Builder instructionId(Integer instructionId) {
            this.instructionId = Optional.ofNullable(instructionId);
            return this;
        }

        /**
         * <p>Date that we created the funding instruction. The date format follows the <a href="https://www.iso.org/iso-8601-date-and-time-format.html">ISO 8601</a> standard.</p>
         */
        @JsonSetter(value = "createdDate", nulls = Nulls.SKIP)
        public Builder createdDate(Optional<String> createdDate) {
            this.createdDate = createdDate;
            return this;
        }

        public Builder createdDate(String createdDate) {
            this.createdDate = Optional.ofNullable(createdDate);
            return this;
        }

        /**
         * <p>Date of the most recent change to the funding instruction. The date format follows the <a href="https://www.iso.org/iso-8601-date-and-time-format.html">ISO 8601</a> standard.</p>
         */
        @JsonSetter(value = "lastModifiedDate", nulls = Nulls.SKIP)
        public Builder lastModifiedDate(Optional<String> lastModifiedDate) {
            this.lastModifiedDate = lastModifiedDate;
            return this;
        }

        public Builder lastModifiedDate(String lastModifiedDate) {
            this.lastModifiedDate = Optional.ofNullable(lastModifiedDate);
            return this;
        }

        /**
         * <p>Status of the funding instruction. Our gateway returns one of the following values:</p>
         * <ul>
         * <li><code>accepted</code> - We have received the funding instruction but have not yet reviewed it.</li>
         * <li><code>pending</code> - We have received the funding instruction and we are reviewing it.</li>
         * <li><code>completed</code> - We have reviewed and processed the funding instruction.</li>
         * </ul>
         */
        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public Builder status(Optional<InstructionStatus> status) {
            this.status = status;
            return this;
        }

        public Builder status(InstructionStatus status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        /**
         * <p>Array of merchants objects. Each object specifies the merchant whose funding balance we distribute and who you want to send the funds to.</p>
         */
        @JsonSetter(value = "merchants", nulls = Nulls.SKIP)
        public Builder merchants(Optional<List<InstructionMerchantsItem>> merchants) {
            this.merchants = merchants;
            return this;
        }

        public Builder merchants(List<InstructionMerchantsItem> merchants) {
            this.merchants = Optional.ofNullable(merchants);
            return this;
        }

        /**
         * <p><a href="https://docs.payroc.com/api/metadata">Metadata</a> object you can use to include custom data with your request.</p>
         */
        @JsonSetter(value = "metadata", nulls = Nulls.SKIP)
        public Builder metadata(Optional<Map<String, String>> metadata) {
            this.metadata = metadata;
            return this;
        }

        public Builder metadata(Map<String, String> metadata) {
            this.metadata = Optional.ofNullable(metadata);
            return this;
        }

        @JsonSetter(value = "link", nulls = Nulls.SKIP)
        public Builder link(Optional<Link> link) {
            this.link = link;
            return this;
        }

        public Builder link(Link link) {
            this.link = Optional.ofNullable(link);
            return this;
        }

        public ListFundingInstructionsResponseDataItem build() {
            return new ListFundingInstructionsResponseDataItem(
                    instructionId,
                    createdDate,
                    lastModifiedDate,
                    status,
                    merchants,
                    metadata,
                    link,
                    additionalProperties);
        }
    }
}
