/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api;

import com.payroc.api.core.ClientOptions;
import com.payroc.api.core.Suppliers;
import com.payroc.api.resources.applepaysessions.ApplePaySessionsClient;
import com.payroc.api.resources.auth.AuthClient;
import com.payroc.api.resources.banktransferpayments.BankTransferPaymentsClient;
import com.payroc.api.resources.boarding.BoardingClient;
import com.payroc.api.resources.cardpayments.CardPaymentsClient;
import com.payroc.api.resources.funding.FundingClient;
import com.payroc.api.resources.hostedfields.HostedFieldsClient;
import com.payroc.api.resources.notifications.NotificationsClient;
import com.payroc.api.resources.paymentfeatures.PaymentFeaturesClient;
import com.payroc.api.resources.paymentlinks.PaymentLinksClient;
import com.payroc.api.resources.payroccloud.PayrocCloudClient;
import com.payroc.api.resources.repeatpayments.RepeatPaymentsClient;
import com.payroc.api.resources.reporting.ReportingClient;
import com.payroc.api.resources.tokenization.TokenizationClient;
import java.util.function.Supplier;

public class PayrocApiClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<PaymentLinksClient> paymentLinksClient;

    protected final Supplier<HostedFieldsClient> hostedFieldsClient;

    protected final Supplier<ApplePaySessionsClient> applePaySessionsClient;

    protected final Supplier<AuthClient> authClient;

    protected final Supplier<FundingClient> fundingClient;

    protected final Supplier<BankTransferPaymentsClient> bankTransferPaymentsClient;

    protected final Supplier<BoardingClient> boardingClient;

    protected final Supplier<CardPaymentsClient> cardPaymentsClient;

    protected final Supplier<NotificationsClient> notificationsClient;

    protected final Supplier<PaymentFeaturesClient> paymentFeaturesClient;

    protected final Supplier<PayrocCloudClient> payrocCloudClient;

    protected final Supplier<RepeatPaymentsClient> repeatPaymentsClient;

    protected final Supplier<ReportingClient> reportingClient;

    protected final Supplier<TokenizationClient> tokenizationClient;

    public PayrocApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.paymentLinksClient = Suppliers.memoize(() -> new PaymentLinksClient(clientOptions));
        this.hostedFieldsClient = Suppliers.memoize(() -> new HostedFieldsClient(clientOptions));
        this.applePaySessionsClient = Suppliers.memoize(() -> new ApplePaySessionsClient(clientOptions));
        this.authClient = Suppliers.memoize(() -> new AuthClient(clientOptions));
        this.fundingClient = Suppliers.memoize(() -> new FundingClient(clientOptions));
        this.bankTransferPaymentsClient = Suppliers.memoize(() -> new BankTransferPaymentsClient(clientOptions));
        this.boardingClient = Suppliers.memoize(() -> new BoardingClient(clientOptions));
        this.cardPaymentsClient = Suppliers.memoize(() -> new CardPaymentsClient(clientOptions));
        this.notificationsClient = Suppliers.memoize(() -> new NotificationsClient(clientOptions));
        this.paymentFeaturesClient = Suppliers.memoize(() -> new PaymentFeaturesClient(clientOptions));
        this.payrocCloudClient = Suppliers.memoize(() -> new PayrocCloudClient(clientOptions));
        this.repeatPaymentsClient = Suppliers.memoize(() -> new RepeatPaymentsClient(clientOptions));
        this.reportingClient = Suppliers.memoize(() -> new ReportingClient(clientOptions));
        this.tokenizationClient = Suppliers.memoize(() -> new TokenizationClient(clientOptions));
    }

    public PaymentLinksClient paymentLinks() {
        return this.paymentLinksClient.get();
    }

    public HostedFieldsClient hostedFields() {
        return this.hostedFieldsClient.get();
    }

    public ApplePaySessionsClient applePaySessions() {
        return this.applePaySessionsClient.get();
    }

    public AuthClient auth() {
        return this.authClient.get();
    }

    public FundingClient funding() {
        return this.fundingClient.get();
    }

    public BankTransferPaymentsClient bankTransferPayments() {
        return this.bankTransferPaymentsClient.get();
    }

    public BoardingClient boarding() {
        return this.boardingClient.get();
    }

    public CardPaymentsClient cardPayments() {
        return this.cardPaymentsClient.get();
    }

    public NotificationsClient notifications() {
        return this.notificationsClient.get();
    }

    public PaymentFeaturesClient paymentFeatures() {
        return this.paymentFeaturesClient.get();
    }

    public PayrocCloudClient payrocCloud() {
        return this.payrocCloudClient.get();
    }

    public RepeatPaymentsClient repeatPayments() {
        return this.repeatPaymentsClient.get();
    }

    public ReportingClient reporting() {
        return this.reportingClient.get();
    }

    public TokenizationClient tokenization() {
        return this.tokenizationClient.get();
    }

    public static PayrocApiClientBuilder builder() {
        return new PayrocApiClientBuilder();
    }
}
