/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Address.Builder.class)
public final class Address implements IAddress {
    private final String address1;

    private final Optional<String> address2;

    private final Optional<String> address3;

    private final String city;

    private final String state;

    private final String country;

    private final String postalCode;

    private final Map<String, Object> additionalProperties;

    private Address(
            String address1,
            Optional<String> address2,
            Optional<String> address3,
            String city,
            String state,
            String country,
            String postalCode,
            Map<String, Object> additionalProperties) {
        this.address1 = address1;
        this.address2 = address2;
        this.address3 = address3;
        this.city = city;
        this.state = state;
        this.country = country;
        this.postalCode = postalCode;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Address line 1.
     */
    @JsonProperty("address1")
    @java.lang.Override
    public String getAddress1() {
        return address1;
    }

    /**
     * @return Address line 2.
     */
    @JsonProperty("address2")
    @java.lang.Override
    public Optional<String> getAddress2() {
        return address2;
    }

    /**
     * @return Address line 3.
     */
    @JsonProperty("address3")
    @java.lang.Override
    public Optional<String> getAddress3() {
        return address3;
    }

    /**
     * @return City.
     */
    @JsonProperty("city")
    @java.lang.Override
    public String getCity() {
        return city;
    }

    /**
     * @return Name of the state or state abbreviation.
     */
    @JsonProperty("state")
    @java.lang.Override
    public String getState() {
        return state;
    }

    /**
     * @return Two-digit country code for the country that the business operates in. The format follows the <a href="https://www.iso.org/iso-3166-country-codes.html">ISO-3166-1</a> standard.
     */
    @JsonProperty("country")
    @java.lang.Override
    public String getCountry() {
        return country;
    }

    /**
     * @return Zip code or postal code.
     */
    @JsonProperty("postalCode")
    @java.lang.Override
    public String getPostalCode() {
        return postalCode;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Address && equalTo((Address) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Address other) {
        return address1.equals(other.address1)
                && address2.equals(other.address2)
                && address3.equals(other.address3)
                && city.equals(other.city)
                && state.equals(other.state)
                && country.equals(other.country)
                && postalCode.equals(other.postalCode);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.address1, this.address2, this.address3, this.city, this.state, this.country, this.postalCode);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Address1Stage builder() {
        return new Builder();
    }

    public interface Address1Stage {
        /**
         * <p>Address line 1.</p>
         */
        CityStage address1(@NotNull String address1);

        Builder from(Address other);
    }

    public interface CityStage {
        /**
         * <p>City.</p>
         */
        StateStage city(@NotNull String city);
    }

    public interface StateStage {
        /**
         * <p>Name of the state or state abbreviation.</p>
         */
        CountryStage state(@NotNull String state);
    }

    public interface CountryStage {
        /**
         * <p>Two-digit country code for the country that the business operates in. The format follows the <a href="https://www.iso.org/iso-3166-country-codes.html">ISO-3166-1</a> standard.</p>
         */
        PostalCodeStage country(@NotNull String country);
    }

    public interface PostalCodeStage {
        /**
         * <p>Zip code or postal code.</p>
         */
        _FinalStage postalCode(@NotNull String postalCode);
    }

    public interface _FinalStage {
        Address build();

        /**
         * <p>Address line 2.</p>
         */
        _FinalStage address2(Optional<String> address2);

        _FinalStage address2(String address2);

        /**
         * <p>Address line 3.</p>
         */
        _FinalStage address3(Optional<String> address3);

        _FinalStage address3(String address3);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements Address1Stage, CityStage, StateStage, CountryStage, PostalCodeStage, _FinalStage {
        private String address1;

        private String city;

        private String state;

        private String country;

        private String postalCode;

        private Optional<String> address3 = Optional.empty();

        private Optional<String> address2 = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(Address other) {
            address1(other.getAddress1());
            address2(other.getAddress2());
            address3(other.getAddress3());
            city(other.getCity());
            state(other.getState());
            country(other.getCountry());
            postalCode(other.getPostalCode());
            return this;
        }

        /**
         * <p>Address line 1.</p>
         * <p>Address line 1.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("address1")
        public CityStage address1(@NotNull String address1) {
            this.address1 = Objects.requireNonNull(address1, "address1 must not be null");
            return this;
        }

        /**
         * <p>City.</p>
         * <p>City.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("city")
        public StateStage city(@NotNull String city) {
            this.city = Objects.requireNonNull(city, "city must not be null");
            return this;
        }

        /**
         * <p>Name of the state or state abbreviation.</p>
         * <p>Name of the state or state abbreviation.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("state")
        public CountryStage state(@NotNull String state) {
            this.state = Objects.requireNonNull(state, "state must not be null");
            return this;
        }

        /**
         * <p>Two-digit country code for the country that the business operates in. The format follows the <a href="https://www.iso.org/iso-3166-country-codes.html">ISO-3166-1</a> standard.</p>
         * <p>Two-digit country code for the country that the business operates in. The format follows the <a href="https://www.iso.org/iso-3166-country-codes.html">ISO-3166-1</a> standard.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("country")
        public PostalCodeStage country(@NotNull String country) {
            this.country = Objects.requireNonNull(country, "country must not be null");
            return this;
        }

        /**
         * <p>Zip code or postal code.</p>
         * <p>Zip code or postal code.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("postalCode")
        public _FinalStage postalCode(@NotNull String postalCode) {
            this.postalCode = Objects.requireNonNull(postalCode, "postalCode must not be null");
            return this;
        }

        /**
         * <p>Address line 3.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage address3(String address3) {
            this.address3 = Optional.ofNullable(address3);
            return this;
        }

        /**
         * <p>Address line 3.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "address3", nulls = Nulls.SKIP)
        public _FinalStage address3(Optional<String> address3) {
            this.address3 = address3;
            return this;
        }

        /**
         * <p>Address line 2.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage address2(String address2) {
            this.address2 = Optional.ofNullable(address2);
            return this;
        }

        /**
         * <p>Address line 2.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "address2", nulls = Nulls.SKIP)
        public _FinalStage address2(Optional<String> address2) {
            this.address2 = address2;
            return this;
        }

        @java.lang.Override
        public Address build() {
            return new Address(address1, address2, address3, city, state, country, postalCode, additionalProperties);
        }
    }
}
