/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class BankTransferResultStatus {
    public static final BankTransferResultStatus DECLINED = new BankTransferResultStatus(Value.DECLINED, "declined");

    public static final BankTransferResultStatus REVERSAL = new BankTransferResultStatus(Value.REVERSAL, "reversal");

    public static final BankTransferResultStatus COMPLETE = new BankTransferResultStatus(Value.COMPLETE, "complete");

    public static final BankTransferResultStatus PENDING = new BankTransferResultStatus(Value.PENDING, "pending");

    public static final BankTransferResultStatus ADMIN = new BankTransferResultStatus(Value.ADMIN, "admin");

    public static final BankTransferResultStatus RETURNED = new BankTransferResultStatus(Value.RETURNED, "returned");

    public static final BankTransferResultStatus READY = new BankTransferResultStatus(Value.READY, "ready");

    private final Value value;

    private final String string;

    BankTransferResultStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof BankTransferResultStatus
                        && this.string.equals(((BankTransferResultStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DECLINED:
                return visitor.visitDeclined();
            case REVERSAL:
                return visitor.visitReversal();
            case COMPLETE:
                return visitor.visitComplete();
            case PENDING:
                return visitor.visitPending();
            case ADMIN:
                return visitor.visitAdmin();
            case RETURNED:
                return visitor.visitReturned();
            case READY:
                return visitor.visitReady();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static BankTransferResultStatus valueOf(String value) {
        switch (value) {
            case "declined":
                return DECLINED;
            case "reversal":
                return REVERSAL;
            case "complete":
                return COMPLETE;
            case "pending":
                return PENDING;
            case "admin":
                return ADMIN;
            case "returned":
                return RETURNED;
            case "ready":
                return READY;
            default:
                return new BankTransferResultStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        READY,

        PENDING,

        DECLINED,

        COMPLETE,

        ADMIN,

        REVERSAL,

        RETURNED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitReady();

        T visitPending();

        T visitDeclined();

        T visitComplete();

        T visitAdmin();

        T visitReversal();

        T visitReturned();

        T visitUnknown(String unknownType);
    }
}
