/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BankTransferRefund.Builder.class)
public final class BankTransferRefund {
    private final String refundId;

    private final String processingTerminalId;

    private final BankTransferRefundOrder order;

    private final Optional<BankTransferCustomer> customer;

    private final BankTransferRefundBankAccount bankAccount;

    private final Optional<PaymentSummary> payment;

    private final BankTransferResult transactionResult;

    private final Optional<List<CustomField>> customFields;

    private final Map<String, Object> additionalProperties;

    private BankTransferRefund(
            String refundId,
            String processingTerminalId,
            BankTransferRefundOrder order,
            Optional<BankTransferCustomer> customer,
            BankTransferRefundBankAccount bankAccount,
            Optional<PaymentSummary> payment,
            BankTransferResult transactionResult,
            Optional<List<CustomField>> customFields,
            Map<String, Object> additionalProperties) {
        this.refundId = refundId;
        this.processingTerminalId = processingTerminalId;
        this.order = order;
        this.customer = customer;
        this.bankAccount = bankAccount;
        this.payment = payment;
        this.transactionResult = transactionResult;
        this.customFields = customFields;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique identifier that our gateway assigned to the refund.
     */
    @JsonProperty("refundId")
    public String getRefundId() {
        return refundId;
    }

    /**
     * @return Unique identifier that we assigned to the terminal.
     */
    @JsonProperty("processingTerminalId")
    public String getProcessingTerminalId() {
        return processingTerminalId;
    }

    @JsonProperty("order")
    public BankTransferRefundOrder getOrder() {
        return order;
    }

    @JsonProperty("customer")
    public Optional<BankTransferCustomer> getCustomer() {
        return customer;
    }

    /**
     * @return Polymorphic object that contains bank account information.
     * <p>The value of the type field determines which variant you should use:</p>
     * <ul>
     * <li><code>ach</code> - Automated Clearing House (ACH) details</li>
     * <li><code>pad</code> - Pre-authorized debit (PAD) details</li>
     * </ul>
     */
    @JsonProperty("bankAccount")
    public BankTransferRefundBankAccount getBankAccount() {
        return bankAccount;
    }

    @JsonProperty("payment")
    public Optional<PaymentSummary> getPayment() {
        return payment;
    }

    @JsonProperty("transactionResult")
    public BankTransferResult getTransactionResult() {
        return transactionResult;
    }

    /**
     * @return Array of customField objects.
     */
    @JsonProperty("customFields")
    public Optional<List<CustomField>> getCustomFields() {
        return customFields;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BankTransferRefund && equalTo((BankTransferRefund) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BankTransferRefund other) {
        return refundId.equals(other.refundId)
                && processingTerminalId.equals(other.processingTerminalId)
                && order.equals(other.order)
                && customer.equals(other.customer)
                && bankAccount.equals(other.bankAccount)
                && payment.equals(other.payment)
                && transactionResult.equals(other.transactionResult)
                && customFields.equals(other.customFields);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.refundId,
                this.processingTerminalId,
                this.order,
                this.customer,
                this.bankAccount,
                this.payment,
                this.transactionResult,
                this.customFields);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static RefundIdStage builder() {
        return new Builder();
    }

    public interface RefundIdStage {
        /**
         * <p>Unique identifier that our gateway assigned to the refund.</p>
         */
        ProcessingTerminalIdStage refundId(@NotNull String refundId);

        Builder from(BankTransferRefund other);
    }

    public interface ProcessingTerminalIdStage {
        /**
         * <p>Unique identifier that we assigned to the terminal.</p>
         */
        OrderStage processingTerminalId(@NotNull String processingTerminalId);
    }

    public interface OrderStage {
        BankAccountStage order(@NotNull BankTransferRefundOrder order);
    }

    public interface BankAccountStage {
        /**
         * <p>Polymorphic object that contains bank account information.</p>
         * <p>The value of the type field determines which variant you should use:</p>
         * <ul>
         * <li><code>ach</code> - Automated Clearing House (ACH) details</li>
         * <li><code>pad</code> - Pre-authorized debit (PAD) details</li>
         * </ul>
         */
        TransactionResultStage bankAccount(@NotNull BankTransferRefundBankAccount bankAccount);
    }

    public interface TransactionResultStage {
        _FinalStage transactionResult(@NotNull BankTransferResult transactionResult);
    }

    public interface _FinalStage {
        BankTransferRefund build();

        _FinalStage customer(Optional<BankTransferCustomer> customer);

        _FinalStage customer(BankTransferCustomer customer);

        _FinalStage payment(Optional<PaymentSummary> payment);

        _FinalStage payment(PaymentSummary payment);

        /**
         * <p>Array of customField objects.</p>
         */
        _FinalStage customFields(Optional<List<CustomField>> customFields);

        _FinalStage customFields(List<CustomField> customFields);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements RefundIdStage,
                    ProcessingTerminalIdStage,
                    OrderStage,
                    BankAccountStage,
                    TransactionResultStage,
                    _FinalStage {
        private String refundId;

        private String processingTerminalId;

        private BankTransferRefundOrder order;

        private BankTransferRefundBankAccount bankAccount;

        private BankTransferResult transactionResult;

        private Optional<List<CustomField>> customFields = Optional.empty();

        private Optional<PaymentSummary> payment = Optional.empty();

        private Optional<BankTransferCustomer> customer = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(BankTransferRefund other) {
            refundId(other.getRefundId());
            processingTerminalId(other.getProcessingTerminalId());
            order(other.getOrder());
            customer(other.getCustomer());
            bankAccount(other.getBankAccount());
            payment(other.getPayment());
            transactionResult(other.getTransactionResult());
            customFields(other.getCustomFields());
            return this;
        }

        /**
         * <p>Unique identifier that our gateway assigned to the refund.</p>
         * <p>Unique identifier that our gateway assigned to the refund.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("refundId")
        public ProcessingTerminalIdStage refundId(@NotNull String refundId) {
            this.refundId = Objects.requireNonNull(refundId, "refundId must not be null");
            return this;
        }

        /**
         * <p>Unique identifier that we assigned to the terminal.</p>
         * <p>Unique identifier that we assigned to the terminal.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("processingTerminalId")
        public OrderStage processingTerminalId(@NotNull String processingTerminalId) {
            this.processingTerminalId =
                    Objects.requireNonNull(processingTerminalId, "processingTerminalId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("order")
        public BankAccountStage order(@NotNull BankTransferRefundOrder order) {
            this.order = Objects.requireNonNull(order, "order must not be null");
            return this;
        }

        /**
         * <p>Polymorphic object that contains bank account information.</p>
         * <p>The value of the type field determines which variant you should use:</p>
         * <ul>
         * <li><code>ach</code> - Automated Clearing House (ACH) details</li>
         * <li><code>pad</code> - Pre-authorized debit (PAD) details</li>
         * </ul>
         * <p>Polymorphic object that contains bank account information.</p>
         * <p>The value of the type field determines which variant you should use:</p>
         * <ul>
         * <li><code>ach</code> - Automated Clearing House (ACH) details</li>
         * <li><code>pad</code> - Pre-authorized debit (PAD) details</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("bankAccount")
        public TransactionResultStage bankAccount(@NotNull BankTransferRefundBankAccount bankAccount) {
            this.bankAccount = Objects.requireNonNull(bankAccount, "bankAccount must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("transactionResult")
        public _FinalStage transactionResult(@NotNull BankTransferResult transactionResult) {
            this.transactionResult = Objects.requireNonNull(transactionResult, "transactionResult must not be null");
            return this;
        }

        /**
         * <p>Array of customField objects.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage customFields(List<CustomField> customFields) {
            this.customFields = Optional.ofNullable(customFields);
            return this;
        }

        /**
         * <p>Array of customField objects.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "customFields", nulls = Nulls.SKIP)
        public _FinalStage customFields(Optional<List<CustomField>> customFields) {
            this.customFields = customFields;
            return this;
        }

        @java.lang.Override
        public _FinalStage payment(PaymentSummary payment) {
            this.payment = Optional.ofNullable(payment);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "payment", nulls = Nulls.SKIP)
        public _FinalStage payment(Optional<PaymentSummary> payment) {
            this.payment = payment;
            return this;
        }

        @java.lang.Override
        public _FinalStage customer(BankTransferCustomer customer) {
            this.customer = Optional.ofNullable(customer);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "customer", nulls = Nulls.SKIP)
        public _FinalStage customer(Optional<BankTransferCustomer> customer) {
            this.customer = customer;
            return this;
        }

        @java.lang.Override
        public BankTransferRefund build() {
            return new BankTransferRefund(
                    refundId,
                    processingTerminalId,
                    order,
                    customer,
                    bankAccount,
                    payment,
                    transactionResult,
                    customFields,
                    additionalProperties);
        }
    }
}
