/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Business.Builder.class)
public final class Business {
    private final String name;

    private final String taxId;

    private final BusinessOrganizationType organizationType;

    private final Optional<BusinessCountryOfOperation> countryOfOperation;

    private final List<LegalAddress> addresses;

    private final List<ContactMethod> contactMethods;

    private final Map<String, Object> additionalProperties;

    private Business(
            String name,
            String taxId,
            BusinessOrganizationType organizationType,
            Optional<BusinessCountryOfOperation> countryOfOperation,
            List<LegalAddress> addresses,
            List<ContactMethod> contactMethods,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.taxId = taxId;
        this.organizationType = organizationType;
        this.countryOfOperation = countryOfOperation;
        this.addresses = addresses;
        this.contactMethods = contactMethods;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Legal name of the business.
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return Tax ID of the business.
     */
    @JsonProperty("taxId")
    public String getTaxId() {
        return taxId;
    }

    /**
     * @return Type of organization.
     */
    @JsonProperty("organizationType")
    public BusinessOrganizationType getOrganizationType() {
        return organizationType;
    }

    /**
     * @return Two-digit code for the country that the business operates in. The format follows the <a href="https://www.iso.org/iso-3166-country-codes.html">ISO-3166</a> standard.
     */
    @JsonProperty("countryOfOperation")
    public Optional<BusinessCountryOfOperation> getCountryOfOperation() {
        return countryOfOperation;
    }

    /**
     * @return Object that contains the addresses for the business.
     */
    @JsonProperty("addresses")
    public List<LegalAddress> getAddresses() {
        return addresses;
    }

    /**
     * @return Array of contactMethod objects. One contact method must be an email address.
     */
    @JsonProperty("contactMethods")
    public List<ContactMethod> getContactMethods() {
        return contactMethods;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Business && equalTo((Business) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Business other) {
        return name.equals(other.name)
                && taxId.equals(other.taxId)
                && organizationType.equals(other.organizationType)
                && countryOfOperation.equals(other.countryOfOperation)
                && addresses.equals(other.addresses)
                && contactMethods.equals(other.contactMethods);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.name,
                this.taxId,
                this.organizationType,
                this.countryOfOperation,
                this.addresses,
                this.contactMethods);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        /**
         * <p>Legal name of the business.</p>
         */
        TaxIdStage name(@NotNull String name);

        Builder from(Business other);
    }

    public interface TaxIdStage {
        /**
         * <p>Tax ID of the business.</p>
         */
        OrganizationTypeStage taxId(@NotNull String taxId);
    }

    public interface OrganizationTypeStage {
        /**
         * <p>Type of organization.</p>
         */
        _FinalStage organizationType(@NotNull BusinessOrganizationType organizationType);
    }

    public interface _FinalStage {
        Business build();

        /**
         * <p>Two-digit code for the country that the business operates in. The format follows the <a href="https://www.iso.org/iso-3166-country-codes.html">ISO-3166</a> standard.</p>
         */
        _FinalStage countryOfOperation(Optional<BusinessCountryOfOperation> countryOfOperation);

        _FinalStage countryOfOperation(BusinessCountryOfOperation countryOfOperation);

        /**
         * <p>Object that contains the addresses for the business.</p>
         */
        _FinalStage addresses(List<LegalAddress> addresses);

        _FinalStage addAddresses(LegalAddress addresses);

        _FinalStage addAllAddresses(List<LegalAddress> addresses);

        /**
         * <p>Array of contactMethod objects. One contact method must be an email address.</p>
         */
        _FinalStage contactMethods(List<ContactMethod> contactMethods);

        _FinalStage addContactMethods(ContactMethod contactMethods);

        _FinalStage addAllContactMethods(List<ContactMethod> contactMethods);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, TaxIdStage, OrganizationTypeStage, _FinalStage {
        private String name;

        private String taxId;

        private BusinessOrganizationType organizationType;

        private List<ContactMethod> contactMethods = new ArrayList<>();

        private List<LegalAddress> addresses = new ArrayList<>();

        private Optional<BusinessCountryOfOperation> countryOfOperation = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(Business other) {
            name(other.getName());
            taxId(other.getTaxId());
            organizationType(other.getOrganizationType());
            countryOfOperation(other.getCountryOfOperation());
            addresses(other.getAddresses());
            contactMethods(other.getContactMethods());
            return this;
        }

        /**
         * <p>Legal name of the business.</p>
         * <p>Legal name of the business.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public TaxIdStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Tax ID of the business.</p>
         * <p>Tax ID of the business.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("taxId")
        public OrganizationTypeStage taxId(@NotNull String taxId) {
            this.taxId = Objects.requireNonNull(taxId, "taxId must not be null");
            return this;
        }

        /**
         * <p>Type of organization.</p>
         * <p>Type of organization.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("organizationType")
        public _FinalStage organizationType(@NotNull BusinessOrganizationType organizationType) {
            this.organizationType = Objects.requireNonNull(organizationType, "organizationType must not be null");
            return this;
        }

        /**
         * <p>Array of contactMethod objects. One contact method must be an email address.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllContactMethods(List<ContactMethod> contactMethods) {
            if (contactMethods != null) {
                this.contactMethods.addAll(contactMethods);
            }
            return this;
        }

        /**
         * <p>Array of contactMethod objects. One contact method must be an email address.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addContactMethods(ContactMethod contactMethods) {
            this.contactMethods.add(contactMethods);
            return this;
        }

        /**
         * <p>Array of contactMethod objects. One contact method must be an email address.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "contactMethods", nulls = Nulls.SKIP)
        public _FinalStage contactMethods(List<ContactMethod> contactMethods) {
            this.contactMethods.clear();
            if (contactMethods != null) {
                this.contactMethods.addAll(contactMethods);
            }
            return this;
        }

        /**
         * <p>Object that contains the addresses for the business.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllAddresses(List<LegalAddress> addresses) {
            if (addresses != null) {
                this.addresses.addAll(addresses);
            }
            return this;
        }

        /**
         * <p>Object that contains the addresses for the business.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAddresses(LegalAddress addresses) {
            this.addresses.add(addresses);
            return this;
        }

        /**
         * <p>Object that contains the addresses for the business.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "addresses", nulls = Nulls.SKIP)
        public _FinalStage addresses(List<LegalAddress> addresses) {
            this.addresses.clear();
            if (addresses != null) {
                this.addresses.addAll(addresses);
            }
            return this;
        }

        /**
         * <p>Two-digit code for the country that the business operates in. The format follows the <a href="https://www.iso.org/iso-3166-country-codes.html">ISO-3166</a> standard.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage countryOfOperation(BusinessCountryOfOperation countryOfOperation) {
            this.countryOfOperation = Optional.ofNullable(countryOfOperation);
            return this;
        }

        /**
         * <p>Two-digit code for the country that the business operates in. The format follows the <a href="https://www.iso.org/iso-3166-country-codes.html">ISO-3166</a> standard.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "countryOfOperation", nulls = Nulls.SKIP)
        public _FinalStage countryOfOperation(Optional<BusinessCountryOfOperation> countryOfOperation) {
            this.countryOfOperation = countryOfOperation;
            return this;
        }

        @java.lang.Override
        public Business build() {
            return new Business(
                    name, taxId, organizationType, countryOfOperation, addresses, contactMethods, additionalProperties);
        }
    }
}
