/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CardVerificationResult.Builder.class)
public final class CardVerificationResult {
    private final Optional<String> operator;

    private final String processingTerminalId;

    private final Optional<Card> card;

    private final boolean verified;

    private final Optional<TransactionResult> transactionResult;

    private final Map<String, Object> additionalProperties;

    private CardVerificationResult(
            Optional<String> operator,
            String processingTerminalId,
            Optional<Card> card,
            boolean verified,
            Optional<TransactionResult> transactionResult,
            Map<String, Object> additionalProperties) {
        this.operator = operator;
        this.processingTerminalId = processingTerminalId;
        this.card = card;
        this.verified = verified;
        this.transactionResult = transactionResult;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Operator who requested to verify the card.
     */
    @JsonProperty("operator")
    public Optional<String> getOperator() {
        return operator;
    }

    /**
     * @return Unique identifier that we assigned to the terminal.
     */
    @JsonProperty("processingTerminalId")
    public String getProcessingTerminalId() {
        return processingTerminalId;
    }

    @JsonProperty("card")
    public Optional<Card> getCard() {
        return card;
    }

    /**
     * @return Indicates if the card details are valid:
     * <ul>
     * <li><code>true</code> - Card details are valid.</li>
     * <li><code>false</code> - Card details are not valid.</li>
     * </ul>
     */
    @JsonProperty("verified")
    public boolean getVerified() {
        return verified;
    }

    @JsonProperty("transactionResult")
    public Optional<TransactionResult> getTransactionResult() {
        return transactionResult;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CardVerificationResult && equalTo((CardVerificationResult) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CardVerificationResult other) {
        return operator.equals(other.operator)
                && processingTerminalId.equals(other.processingTerminalId)
                && card.equals(other.card)
                && verified == other.verified
                && transactionResult.equals(other.transactionResult);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.operator, this.processingTerminalId, this.card, this.verified, this.transactionResult);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ProcessingTerminalIdStage builder() {
        return new Builder();
    }

    public interface ProcessingTerminalIdStage {
        /**
         * <p>Unique identifier that we assigned to the terminal.</p>
         */
        VerifiedStage processingTerminalId(@NotNull String processingTerminalId);

        Builder from(CardVerificationResult other);
    }

    public interface VerifiedStage {
        /**
         * <p>Indicates if the card details are valid:</p>
         * <ul>
         * <li><code>true</code> - Card details are valid.</li>
         * <li><code>false</code> - Card details are not valid.</li>
         * </ul>
         */
        _FinalStage verified(boolean verified);
    }

    public interface _FinalStage {
        CardVerificationResult build();

        /**
         * <p>Operator who requested to verify the card.</p>
         */
        _FinalStage operator(Optional<String> operator);

        _FinalStage operator(String operator);

        _FinalStage card(Optional<Card> card);

        _FinalStage card(Card card);

        _FinalStage transactionResult(Optional<TransactionResult> transactionResult);

        _FinalStage transactionResult(TransactionResult transactionResult);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ProcessingTerminalIdStage, VerifiedStage, _FinalStage {
        private String processingTerminalId;

        private boolean verified;

        private Optional<TransactionResult> transactionResult = Optional.empty();

        private Optional<Card> card = Optional.empty();

        private Optional<String> operator = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CardVerificationResult other) {
            operator(other.getOperator());
            processingTerminalId(other.getProcessingTerminalId());
            card(other.getCard());
            verified(other.getVerified());
            transactionResult(other.getTransactionResult());
            return this;
        }

        /**
         * <p>Unique identifier that we assigned to the terminal.</p>
         * <p>Unique identifier that we assigned to the terminal.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("processingTerminalId")
        public VerifiedStage processingTerminalId(@NotNull String processingTerminalId) {
            this.processingTerminalId =
                    Objects.requireNonNull(processingTerminalId, "processingTerminalId must not be null");
            return this;
        }

        /**
         * <p>Indicates if the card details are valid:</p>
         * <ul>
         * <li><code>true</code> - Card details are valid.</li>
         * <li><code>false</code> - Card details are not valid.</li>
         * </ul>
         * <p>Indicates if the card details are valid:</p>
         * <ul>
         * <li><code>true</code> - Card details are valid.</li>
         * <li><code>false</code> - Card details are not valid.</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("verified")
        public _FinalStage verified(boolean verified) {
            this.verified = verified;
            return this;
        }

        @java.lang.Override
        public _FinalStage transactionResult(TransactionResult transactionResult) {
            this.transactionResult = Optional.ofNullable(transactionResult);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "transactionResult", nulls = Nulls.SKIP)
        public _FinalStage transactionResult(Optional<TransactionResult> transactionResult) {
            this.transactionResult = transactionResult;
            return this;
        }

        @java.lang.Override
        public _FinalStage card(Card card) {
            this.card = Optional.ofNullable(card);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "card", nulls = Nulls.SKIP)
        public _FinalStage card(Optional<Card> card) {
            this.card = card;
            return this;
        }

        /**
         * <p>Operator who requested to verify the card.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage operator(String operator) {
            this.operator = Optional.ofNullable(operator);
            return this;
        }

        /**
         * <p>Operator who requested to verify the card.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "operator", nulls = Nulls.SKIP)
        public _FinalStage operator(Optional<String> operator) {
            this.operator = operator;
            return this;
        }

        @java.lang.Override
        public CardVerificationResult build() {
            return new CardVerificationResult(
                    operator, processingTerminalId, card, verified, transactionResult, additionalProperties);
        }
    }
}
