/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CardSummaryType {
    public static final CardSummaryType MASTER_CARD = new CardSummaryType(Value.MASTER_CARD, "masterCard");

    public static final CardSummaryType PRIVATE_LABEL = new CardSummaryType(Value.PRIVATE_LABEL, "privateLabel");

    public static final CardSummaryType AMEX_OPT_BLUE = new CardSummaryType(Value.AMEX_OPT_BLUE, "amexOptBlue");

    public static final CardSummaryType VOYAGER = new CardSummaryType(Value.VOYAGER, "voyager");

    public static final CardSummaryType UNKNOWN = new CardSummaryType(Value.UNKNOWN, "unknown");

    public static final CardSummaryType WRIGHT_EXPRESS = new CardSummaryType(Value.WRIGHT_EXPRESS, "wrightExpress");

    public static final CardSummaryType DEBIT = new CardSummaryType(Value.DEBIT, "debit");

    public static final CardSummaryType AMEX = new CardSummaryType(Value.AMEX, "amex");

    public static final CardSummaryType DISCOVER = new CardSummaryType(Value.DISCOVER, "discover");

    public static final CardSummaryType DISCOVER_RETAINED =
            new CardSummaryType(Value.DISCOVER_RETAINED, "discoverRetained");

    public static final CardSummaryType VISA = new CardSummaryType(Value.VISA, "visa");

    public static final CardSummaryType EBT = new CardSummaryType(Value.EBT, "ebt");

    public static final CardSummaryType STORED_VALUE = new CardSummaryType(Value.STORED_VALUE, "storedValue");

    public static final CardSummaryType JCB_NON_SETTLED = new CardSummaryType(Value.JCB_NON_SETTLED, "jcbNonSettled");

    public static final CardSummaryType FUELMAN = new CardSummaryType(Value.FUELMAN, "fuelman");

    public static final CardSummaryType DINERS_CLUB = new CardSummaryType(Value.DINERS_CLUB, "dinersClub");

    private final Value value;

    private final String string;

    CardSummaryType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CardSummaryType && this.string.equals(((CardSummaryType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case MASTER_CARD:
                return visitor.visitMasterCard();
            case PRIVATE_LABEL:
                return visitor.visitPrivateLabel();
            case AMEX_OPT_BLUE:
                return visitor.visitAmexOptBlue();
            case VOYAGER:
                return visitor.visitVoyager();
            case UNKNOWN:
                return visitor.visitUnknown();
            case WRIGHT_EXPRESS:
                return visitor.visitWrightExpress();
            case DEBIT:
                return visitor.visitDebit();
            case AMEX:
                return visitor.visitAmex();
            case DISCOVER:
                return visitor.visitDiscover();
            case DISCOVER_RETAINED:
                return visitor.visitDiscoverRetained();
            case VISA:
                return visitor.visitVisa();
            case EBT:
                return visitor.visitEbt();
            case STORED_VALUE:
                return visitor.visitStoredValue();
            case JCB_NON_SETTLED:
                return visitor.visitJcbNonSettled();
            case FUELMAN:
                return visitor.visitFuelman();
            case DINERS_CLUB:
                return visitor.visitDinersClub();
            case _UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CardSummaryType valueOf(String value) {
        switch (value) {
            case "masterCard":
                return MASTER_CARD;
            case "privateLabel":
                return PRIVATE_LABEL;
            case "amexOptBlue":
                return AMEX_OPT_BLUE;
            case "voyager":
                return VOYAGER;
            case "unknown":
                return UNKNOWN;
            case "wrightExpress":
                return WRIGHT_EXPRESS;
            case "debit":
                return DEBIT;
            case "amex":
                return AMEX;
            case "discover":
                return DISCOVER;
            case "discoverRetained":
                return DISCOVER_RETAINED;
            case "visa":
                return VISA;
            case "ebt":
                return EBT;
            case "storedValue":
                return STORED_VALUE;
            case "jcbNonSettled":
                return JCB_NON_SETTLED;
            case "fuelman":
                return FUELMAN;
            case "dinersClub":
                return DINERS_CLUB;
            default:
                return new CardSummaryType(Value._UNKNOWN, value);
        }
    }

    public enum Value {
        VISA,

        MASTER_CARD,

        DISCOVER,

        DEBIT,

        EBT,

        WRIGHT_EXPRESS,

        VOYAGER,

        AMEX,

        PRIVATE_LABEL,

        STORED_VALUE,

        DISCOVER_RETAINED,

        JCB_NON_SETTLED,

        DINERS_CLUB,

        AMEX_OPT_BLUE,

        FUELMAN,

        UNKNOWN,

        _UNKNOWN
    }

    public interface Visitor<T> {
        T visitVisa();

        T visitMasterCard();

        T visitDiscover();

        T visitDebit();

        T visitEbt();

        T visitWrightExpress();

        T visitVoyager();

        T visitAmex();

        T visitPrivateLabel();

        T visitStoredValue();

        T visitDiscoverRetained();

        T visitJcbNonSettled();

        T visitDinersClub();

        T visitAmexOptBlue();

        T visitFuelman();

        T visitUnknown();

        T visitUnknown(String unknownType);
    }
}
