/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CardEntryMethod {
    public static final CardEntryMethod ICC = new CardEntryMethod(Value.ICC, "icc");

    public static final CardEntryMethod CONTACTLESS_MSR = new CardEntryMethod(Value.CONTACTLESS_MSR, "contactlessMsr");

    public static final CardEntryMethod CONTACTLESS_ICC = new CardEntryMethod(Value.CONTACTLESS_ICC, "contactlessIcc");

    public static final CardEntryMethod KEYED = new CardEntryMethod(Value.KEYED, "keyed");

    public static final CardEntryMethod SWIPED = new CardEntryMethod(Value.SWIPED, "swiped");

    public static final CardEntryMethod SWIPED_FALLBACK = new CardEntryMethod(Value.SWIPED_FALLBACK, "swipedFallback");

    private final Value value;

    private final String string;

    CardEntryMethod(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CardEntryMethod && this.string.equals(((CardEntryMethod) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ICC:
                return visitor.visitIcc();
            case CONTACTLESS_MSR:
                return visitor.visitContactlessMsr();
            case CONTACTLESS_ICC:
                return visitor.visitContactlessIcc();
            case KEYED:
                return visitor.visitKeyed();
            case SWIPED:
                return visitor.visitSwiped();
            case SWIPED_FALLBACK:
                return visitor.visitSwipedFallback();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CardEntryMethod valueOf(String value) {
        switch (value) {
            case "icc":
                return ICC;
            case "contactlessMsr":
                return CONTACTLESS_MSR;
            case "contactlessIcc":
                return CONTACTLESS_ICC;
            case "keyed":
                return KEYED;
            case "swiped":
                return SWIPED;
            case "swipedFallback":
                return SWIPED_FALLBACK;
            default:
                return new CardEntryMethod(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ICC,

        KEYED,

        SWIPED,

        SWIPED_FALLBACK,

        CONTACTLESS_ICC,

        CONTACTLESS_MSR,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitIcc();

        T visitKeyed();

        T visitSwiped();

        T visitSwipedFallback();

        T visitContactlessIcc();

        T visitContactlessMsr();

        T visitUnknown(String unknownType);
    }
}
