/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ClosedLoopResponse.Builder.class)
public final class ClosedLoopResponse {
    private final String processingTerminalId;

    private final String closedLoopReadId;

    private final LocalDate readDate;

    private final Map<String, Object> data;

    private final Map<String, Object> additionalProperties;

    private ClosedLoopResponse(
            String processingTerminalId,
            String closedLoopReadId,
            LocalDate readDate,
            Map<String, Object> data,
            Map<String, Object> additionalProperties) {
        this.processingTerminalId = processingTerminalId;
        this.closedLoopReadId = closedLoopReadId;
        this.readDate = readDate;
        this.data = data;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique identifier that we assigned to the terminal.
     */
    @JsonProperty("processingTerminalId")
    public String getProcessingTerminalId() {
        return processingTerminalId;
    }

    /**
     * @return Unique identifier that we assigned to the closed-loop read.
     */
    @JsonProperty("closedLoopReadId")
    public String getClosedLoopReadId() {
        return closedLoopReadId;
    }

    /**
     * @return Date that the payment device read the closed-loop card. Our gateway returns this value in <strong>YYYY-MM-DD</strong> format.
     */
    @JsonProperty("readDate")
    public LocalDate getReadDate() {
        return readDate;
    }

    /**
     * @return Unstructured payload from the card.
     */
    @JsonProperty("data")
    public Map<String, Object> getData() {
        return data;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ClosedLoopResponse && equalTo((ClosedLoopResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ClosedLoopResponse other) {
        return processingTerminalId.equals(other.processingTerminalId)
                && closedLoopReadId.equals(other.closedLoopReadId)
                && readDate.equals(other.readDate)
                && data.equals(other.data);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.processingTerminalId, this.closedLoopReadId, this.readDate, this.data);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ProcessingTerminalIdStage builder() {
        return new Builder();
    }

    public interface ProcessingTerminalIdStage {
        /**
         * <p>Unique identifier that we assigned to the terminal.</p>
         */
        ClosedLoopReadIdStage processingTerminalId(@NotNull String processingTerminalId);

        Builder from(ClosedLoopResponse other);
    }

    public interface ClosedLoopReadIdStage {
        /**
         * <p>Unique identifier that we assigned to the closed-loop read.</p>
         */
        ReadDateStage closedLoopReadId(@NotNull String closedLoopReadId);
    }

    public interface ReadDateStage {
        /**
         * <p>Date that the payment device read the closed-loop card. Our gateway returns this value in <strong>YYYY-MM-DD</strong> format.</p>
         */
        _FinalStage readDate(@NotNull LocalDate readDate);
    }

    public interface _FinalStage {
        ClosedLoopResponse build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Unstructured payload from the card.</p>
         */
        _FinalStage data(Map<String, Object> data);

        _FinalStage putAllData(Map<String, Object> data);

        _FinalStage data(String key, Object value);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ProcessingTerminalIdStage, ClosedLoopReadIdStage, ReadDateStage, _FinalStage {
        private String processingTerminalId;

        private String closedLoopReadId;

        private LocalDate readDate;

        private Map<String, Object> data = new LinkedHashMap<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ClosedLoopResponse other) {
            processingTerminalId(other.getProcessingTerminalId());
            closedLoopReadId(other.getClosedLoopReadId());
            readDate(other.getReadDate());
            data(other.getData());
            return this;
        }

        /**
         * <p>Unique identifier that we assigned to the terminal.</p>
         * <p>Unique identifier that we assigned to the terminal.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("processingTerminalId")
        public ClosedLoopReadIdStage processingTerminalId(@NotNull String processingTerminalId) {
            this.processingTerminalId =
                    Objects.requireNonNull(processingTerminalId, "processingTerminalId must not be null");
            return this;
        }

        /**
         * <p>Unique identifier that we assigned to the closed-loop read.</p>
         * <p>Unique identifier that we assigned to the closed-loop read.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("closedLoopReadId")
        public ReadDateStage closedLoopReadId(@NotNull String closedLoopReadId) {
            this.closedLoopReadId = Objects.requireNonNull(closedLoopReadId, "closedLoopReadId must not be null");
            return this;
        }

        /**
         * <p>Date that the payment device read the closed-loop card. Our gateway returns this value in <strong>YYYY-MM-DD</strong> format.</p>
         * <p>Date that the payment device read the closed-loop card. Our gateway returns this value in <strong>YYYY-MM-DD</strong> format.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("readDate")
        public _FinalStage readDate(@NotNull LocalDate readDate) {
            this.readDate = Objects.requireNonNull(readDate, "readDate must not be null");
            return this;
        }

        /**
         * <p>Unstructured payload from the card.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage data(String key, Object value) {
            this.data.put(key, value);
            return this;
        }

        /**
         * <p>Unstructured payload from the card.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage putAllData(Map<String, Object> data) {
            if (data != null) {
                this.data.putAll(data);
            }
            return this;
        }

        /**
         * <p>Unstructured payload from the card.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public _FinalStage data(Map<String, Object> data) {
            this.data.clear();
            if (data != null) {
                this.data.putAll(data);
            }
            return this;
        }

        @java.lang.Override
        public ClosedLoopResponse build() {
            return new ClosedLoopResponse(processingTerminalId, closedLoopReadId, readDate, data, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
