/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class DigitalWalletPayloadAccountType {
    public static final DigitalWalletPayloadAccountType CHECKING =
            new DigitalWalletPayloadAccountType(Value.CHECKING, "checking");

    public static final DigitalWalletPayloadAccountType SAVINGS =
            new DigitalWalletPayloadAccountType(Value.SAVINGS, "savings");

    private final Value value;

    private final String string;

    DigitalWalletPayloadAccountType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof DigitalWalletPayloadAccountType
                        && this.string.equals(((DigitalWalletPayloadAccountType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case CHECKING:
                return visitor.visitChecking();
            case SAVINGS:
                return visitor.visitSavings();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static DigitalWalletPayloadAccountType valueOf(String value) {
        switch (value) {
            case "checking":
                return CHECKING;
            case "savings":
                return SAVINGS;
            default:
                return new DigitalWalletPayloadAccountType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        CHECKING,

        SAVINGS,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitChecking();

        T visitSavings();

        T visitUnknown(String unknownType);
    }
}
