/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class EbtDetailsBenefitCategory {
    public static final EbtDetailsBenefitCategory FOOD_STAMP =
            new EbtDetailsBenefitCategory(Value.FOOD_STAMP, "foodStamp");

    public static final EbtDetailsBenefitCategory CASH = new EbtDetailsBenefitCategory(Value.CASH, "cash");

    private final Value value;

    private final String string;

    EbtDetailsBenefitCategory(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof EbtDetailsBenefitCategory
                        && this.string.equals(((EbtDetailsBenefitCategory) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case FOOD_STAMP:
                return visitor.visitFoodStamp();
            case CASH:
                return visitor.visitCash();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static EbtDetailsBenefitCategory valueOf(String value) {
        switch (value) {
            case "foodStamp":
                return FOOD_STAMP;
            case "cash":
                return CASH;
            default:
                return new EbtDetailsBenefitCategory(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        CASH,

        FOOD_STAMP,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitCash();

        T visitFoodStamp();

        T visitUnknown(String unknownType);
    }
}
