/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FourHundredFour.Builder.class)
public final class FourHundredFour {
    private final String type;

    private final String title;

    private final int status;

    private final String detail;

    private final Optional<String> resource;

    private final Map<String, Object> additionalProperties;

    private FourHundredFour(
            String type,
            String title,
            int status,
            String detail,
            Optional<String> resource,
            Map<String, Object> additionalProperties) {
        this.type = type;
        this.title = title;
        this.status = status;
        this.detail = detail;
        this.resource = resource;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return URI reference identifying the problem type
     */
    @JsonProperty("type")
    public String getType() {
        return type;
    }

    /**
     * @return Short description of the issue.
     */
    @JsonProperty("title")
    public String getTitle() {
        return title;
    }

    /**
     * @return Http status code
     */
    @JsonProperty("status")
    public int getStatus() {
        return status;
    }

    /**
     * @return Explanation of the problem
     */
    @JsonProperty("detail")
    public String getDetail() {
        return detail;
    }

    /**
     * @return Resource that was not found
     */
    @JsonProperty("resource")
    public Optional<String> getResource() {
        return resource;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FourHundredFour && equalTo((FourHundredFour) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FourHundredFour other) {
        return type.equals(other.type)
                && title.equals(other.title)
                && status == other.status
                && detail.equals(other.detail)
                && resource.equals(other.resource);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type, this.title, this.status, this.detail, this.resource);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TypeStage builder() {
        return new Builder();
    }

    public interface TypeStage {
        /**
         * <p>URI reference identifying the problem type</p>
         */
        TitleStage type(@NotNull String type);

        Builder from(FourHundredFour other);
    }

    public interface TitleStage {
        /**
         * <p>Short description of the issue.</p>
         */
        StatusStage title(@NotNull String title);
    }

    public interface StatusStage {
        /**
         * <p>Http status code</p>
         */
        DetailStage status(int status);
    }

    public interface DetailStage {
        /**
         * <p>Explanation of the problem</p>
         */
        _FinalStage detail(@NotNull String detail);
    }

    public interface _FinalStage {
        FourHundredFour build();

        /**
         * <p>Resource that was not found</p>
         */
        _FinalStage resource(Optional<String> resource);

        _FinalStage resource(String resource);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, TitleStage, StatusStage, DetailStage, _FinalStage {
        private String type;

        private String title;

        private int status;

        private String detail;

        private Optional<String> resource = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(FourHundredFour other) {
            type(other.getType());
            title(other.getTitle());
            status(other.getStatus());
            detail(other.getDetail());
            resource(other.getResource());
            return this;
        }

        /**
         * <p>URI reference identifying the problem type</p>
         * <p>URI reference identifying the problem type</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("type")
        public TitleStage type(@NotNull String type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        /**
         * <p>Short description of the issue.</p>
         * <p>Short description of the issue.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("title")
        public StatusStage title(@NotNull String title) {
            this.title = Objects.requireNonNull(title, "title must not be null");
            return this;
        }

        /**
         * <p>Http status code</p>
         * <p>Http status code</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("status")
        public DetailStage status(int status) {
            this.status = status;
            return this;
        }

        /**
         * <p>Explanation of the problem</p>
         * <p>Explanation of the problem</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("detail")
        public _FinalStage detail(@NotNull String detail) {
            this.detail = Objects.requireNonNull(detail, "detail must not be null");
            return this;
        }

        /**
         * <p>Resource that was not found</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage resource(String resource) {
            this.resource = Optional.ofNullable(resource);
            return this;
        }

        /**
         * <p>Resource that was not found</p>
         */
        @java.lang.Override
        @JsonSetter(value = "resource", nulls = Nulls.SKIP)
        public _FinalStage resource(Optional<String> resource) {
            this.resource = resource;
            return this;
        }

        @java.lang.Override
        public FourHundredFour build() {
            return new FourHundredFour(type, title, status, detail, resource, additionalProperties);
        }
    }
}
