/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FundingAccount.Builder.class)
public final class FundingAccount {
    private final Optional<Integer> fundingAccountId;

    private final Optional<OffsetDateTime> createdDate;

    private final Optional<OffsetDateTime> lastModifiedDate;

    private final Optional<FundingAccountStatus> status;

    private final FundingAccountType type;

    private final FundingAccountUse use;

    private final String nameOnAccount;

    private final List<PaymentMethodsItem> paymentMethods;

    private final Optional<Map<String, String>> metadata;

    private final Optional<List<Link>> links;

    private final Map<String, Object> additionalProperties;

    private FundingAccount(
            Optional<Integer> fundingAccountId,
            Optional<OffsetDateTime> createdDate,
            Optional<OffsetDateTime> lastModifiedDate,
            Optional<FundingAccountStatus> status,
            FundingAccountType type,
            FundingAccountUse use,
            String nameOnAccount,
            List<PaymentMethodsItem> paymentMethods,
            Optional<Map<String, String>> metadata,
            Optional<List<Link>> links,
            Map<String, Object> additionalProperties) {
        this.fundingAccountId = fundingAccountId;
        this.createdDate = createdDate;
        this.lastModifiedDate = lastModifiedDate;
        this.status = status;
        this.type = type;
        this.use = use;
        this.nameOnAccount = nameOnAccount;
        this.paymentMethods = paymentMethods;
        this.metadata = metadata;
        this.links = links;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique identifier that we assigned to the funding account.
     */
    @JsonProperty("fundingAccountId")
    public Optional<Integer> getFundingAccountId() {
        return fundingAccountId;
    }

    /**
     * @return Date and time that we received your request to create the funding account in our system.
     */
    @JsonProperty("createdDate")
    public Optional<OffsetDateTime> getCreatedDate() {
        return createdDate;
    }

    /**
     * @return Date and time that the funding account was last modified.
     */
    @JsonProperty("lastModifiedDate")
    public Optional<OffsetDateTime> getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * @return Status of the funding account. The value is one of the following:
     * <ul>
     * <li><code>approved</code> - We approved the funding account.</li>
     * <li><code>rejected</code> - We rejected the funding account.</li>
     * <li><code>pending</code> - We have not yet approved the funding account.</li>
     * <li><code>hold</code> - Our Risk team have temporarily placed a hold on the funding account.</li>
     * </ul>
     */
    @JsonProperty("status")
    public Optional<FundingAccountStatus> getStatus() {
        return status;
    }

    /**
     * @return Type of funding account.
     */
    @JsonProperty("type")
    public FundingAccountType getType() {
        return type;
    }

    /**
     * @return Indicates if we send funds or withdraw funds from the account.
     * <ul>
     * <li><code>credit</code> - Send funds to the account.</li>
     * <li><code>debit</code> - Withdraw funds from the account.</li>
     * <li><code>creditAndDebit</code> - Send funds and withdraw funds from the account.</li>
     * </ul>
     * <p><strong>Note:</strong> If the funding account is associated with a funding recipient, we accept only a value of <code>credit</code>.</p>
     */
    @JsonProperty("use")
    public FundingAccountUse getUse() {
        return use;
    }

    /**
     * @return Name of the account holder.
     */
    @JsonProperty("nameOnAccount")
    public String getNameOnAccount() {
        return nameOnAccount;
    }

    /**
     * @return Array of paymentMethod objects.
     */
    @JsonProperty("paymentMethods")
    public List<PaymentMethodsItem> getPaymentMethods() {
        return paymentMethods;
    }

    /**
     * @return <a href="https://docs.payroc.com/api/metadata">Metadata</a> object you can use to include custom data with your request.
     */
    @JsonProperty("metadata")
    public Optional<Map<String, String>> getMetadata() {
        return metadata;
    }

    /**
     * @return Array of HATEOAS links.
     */
    @JsonProperty("links")
    public Optional<List<Link>> getLinks() {
        return links;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FundingAccount && equalTo((FundingAccount) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FundingAccount other) {
        return fundingAccountId.equals(other.fundingAccountId)
                && createdDate.equals(other.createdDate)
                && lastModifiedDate.equals(other.lastModifiedDate)
                && status.equals(other.status)
                && type.equals(other.type)
                && use.equals(other.use)
                && nameOnAccount.equals(other.nameOnAccount)
                && paymentMethods.equals(other.paymentMethods)
                && metadata.equals(other.metadata)
                && links.equals(other.links);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.fundingAccountId,
                this.createdDate,
                this.lastModifiedDate,
                this.status,
                this.type,
                this.use,
                this.nameOnAccount,
                this.paymentMethods,
                this.metadata,
                this.links);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TypeStage builder() {
        return new Builder();
    }

    public interface TypeStage {
        /**
         * <p>Type of funding account.</p>
         */
        UseStage type(@NotNull FundingAccountType type);

        Builder from(FundingAccount other);
    }

    public interface UseStage {
        /**
         * <p>Indicates if we send funds or withdraw funds from the account.</p>
         * <ul>
         * <li><code>credit</code> - Send funds to the account.</li>
         * <li><code>debit</code> - Withdraw funds from the account.</li>
         * <li><code>creditAndDebit</code> - Send funds and withdraw funds from the account.</li>
         * </ul>
         * <p><strong>Note:</strong> If the funding account is associated with a funding recipient, we accept only a value of <code>credit</code>.</p>
         */
        NameOnAccountStage use(@NotNull FundingAccountUse use);
    }

    public interface NameOnAccountStage {
        /**
         * <p>Name of the account holder.</p>
         */
        _FinalStage nameOnAccount(@NotNull String nameOnAccount);
    }

    public interface _FinalStage {
        FundingAccount build();

        /**
         * <p>Unique identifier that we assigned to the funding account.</p>
         */
        _FinalStage fundingAccountId(Optional<Integer> fundingAccountId);

        _FinalStage fundingAccountId(Integer fundingAccountId);

        /**
         * <p>Date and time that we received your request to create the funding account in our system.</p>
         */
        _FinalStage createdDate(Optional<OffsetDateTime> createdDate);

        _FinalStage createdDate(OffsetDateTime createdDate);

        /**
         * <p>Date and time that the funding account was last modified.</p>
         */
        _FinalStage lastModifiedDate(Optional<OffsetDateTime> lastModifiedDate);

        _FinalStage lastModifiedDate(OffsetDateTime lastModifiedDate);

        /**
         * <p>Status of the funding account. The value is one of the following:</p>
         * <ul>
         * <li><code>approved</code> - We approved the funding account.</li>
         * <li><code>rejected</code> - We rejected the funding account.</li>
         * <li><code>pending</code> - We have not yet approved the funding account.</li>
         * <li><code>hold</code> - Our Risk team have temporarily placed a hold on the funding account.</li>
         * </ul>
         */
        _FinalStage status(Optional<FundingAccountStatus> status);

        _FinalStage status(FundingAccountStatus status);

        /**
         * <p>Array of paymentMethod objects.</p>
         */
        _FinalStage paymentMethods(List<PaymentMethodsItem> paymentMethods);

        _FinalStage addPaymentMethods(PaymentMethodsItem paymentMethods);

        _FinalStage addAllPaymentMethods(List<PaymentMethodsItem> paymentMethods);

        /**
         * <p><a href="https://docs.payroc.com/api/metadata">Metadata</a> object you can use to include custom data with your request.</p>
         */
        _FinalStage metadata(Optional<Map<String, String>> metadata);

        _FinalStage metadata(Map<String, String> metadata);

        /**
         * <p>Array of HATEOAS links.</p>
         */
        _FinalStage links(Optional<List<Link>> links);

        _FinalStage links(List<Link> links);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, UseStage, NameOnAccountStage, _FinalStage {
        private FundingAccountType type;

        private FundingAccountUse use;

        private String nameOnAccount;

        private Optional<List<Link>> links = Optional.empty();

        private Optional<Map<String, String>> metadata = Optional.empty();

        private List<PaymentMethodsItem> paymentMethods = new ArrayList<>();

        private Optional<FundingAccountStatus> status = Optional.empty();

        private Optional<OffsetDateTime> lastModifiedDate = Optional.empty();

        private Optional<OffsetDateTime> createdDate = Optional.empty();

        private Optional<Integer> fundingAccountId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(FundingAccount other) {
            fundingAccountId(other.getFundingAccountId());
            createdDate(other.getCreatedDate());
            lastModifiedDate(other.getLastModifiedDate());
            status(other.getStatus());
            type(other.getType());
            use(other.getUse());
            nameOnAccount(other.getNameOnAccount());
            paymentMethods(other.getPaymentMethods());
            metadata(other.getMetadata());
            links(other.getLinks());
            return this;
        }

        /**
         * <p>Type of funding account.</p>
         * <p>Type of funding account.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("type")
        public UseStage type(@NotNull FundingAccountType type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        /**
         * <p>Indicates if we send funds or withdraw funds from the account.</p>
         * <ul>
         * <li><code>credit</code> - Send funds to the account.</li>
         * <li><code>debit</code> - Withdraw funds from the account.</li>
         * <li><code>creditAndDebit</code> - Send funds and withdraw funds from the account.</li>
         * </ul>
         * <p><strong>Note:</strong> If the funding account is associated with a funding recipient, we accept only a value of <code>credit</code>.</p>
         * <p>Indicates if we send funds or withdraw funds from the account.</p>
         * <ul>
         * <li><code>credit</code> - Send funds to the account.</li>
         * <li><code>debit</code> - Withdraw funds from the account.</li>
         * <li><code>creditAndDebit</code> - Send funds and withdraw funds from the account.</li>
         * </ul>
         * <p><strong>Note:</strong> If the funding account is associated with a funding recipient, we accept only a value of <code>credit</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("use")
        public NameOnAccountStage use(@NotNull FundingAccountUse use) {
            this.use = Objects.requireNonNull(use, "use must not be null");
            return this;
        }

        /**
         * <p>Name of the account holder.</p>
         * <p>Name of the account holder.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("nameOnAccount")
        public _FinalStage nameOnAccount(@NotNull String nameOnAccount) {
            this.nameOnAccount = Objects.requireNonNull(nameOnAccount, "nameOnAccount must not be null");
            return this;
        }

        /**
         * <p>Array of HATEOAS links.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage links(List<Link> links) {
            this.links = Optional.ofNullable(links);
            return this;
        }

        /**
         * <p>Array of HATEOAS links.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "links", nulls = Nulls.SKIP)
        public _FinalStage links(Optional<List<Link>> links) {
            this.links = links;
            return this;
        }

        /**
         * <p><a href="https://docs.payroc.com/api/metadata">Metadata</a> object you can use to include custom data with your request.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage metadata(Map<String, String> metadata) {
            this.metadata = Optional.ofNullable(metadata);
            return this;
        }

        /**
         * <p><a href="https://docs.payroc.com/api/metadata">Metadata</a> object you can use to include custom data with your request.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "metadata", nulls = Nulls.SKIP)
        public _FinalStage metadata(Optional<Map<String, String>> metadata) {
            this.metadata = metadata;
            return this;
        }

        /**
         * <p>Array of paymentMethod objects.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllPaymentMethods(List<PaymentMethodsItem> paymentMethods) {
            if (paymentMethods != null) {
                this.paymentMethods.addAll(paymentMethods);
            }
            return this;
        }

        /**
         * <p>Array of paymentMethod objects.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addPaymentMethods(PaymentMethodsItem paymentMethods) {
            this.paymentMethods.add(paymentMethods);
            return this;
        }

        /**
         * <p>Array of paymentMethod objects.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "paymentMethods", nulls = Nulls.SKIP)
        public _FinalStage paymentMethods(List<PaymentMethodsItem> paymentMethods) {
            this.paymentMethods.clear();
            if (paymentMethods != null) {
                this.paymentMethods.addAll(paymentMethods);
            }
            return this;
        }

        /**
         * <p>Status of the funding account. The value is one of the following:</p>
         * <ul>
         * <li><code>approved</code> - We approved the funding account.</li>
         * <li><code>rejected</code> - We rejected the funding account.</li>
         * <li><code>pending</code> - We have not yet approved the funding account.</li>
         * <li><code>hold</code> - Our Risk team have temporarily placed a hold on the funding account.</li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage status(FundingAccountStatus status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        /**
         * <p>Status of the funding account. The value is one of the following:</p>
         * <ul>
         * <li><code>approved</code> - We approved the funding account.</li>
         * <li><code>rejected</code> - We rejected the funding account.</li>
         * <li><code>pending</code> - We have not yet approved the funding account.</li>
         * <li><code>hold</code> - Our Risk team have temporarily placed a hold on the funding account.</li>
         * </ul>
         */
        @java.lang.Override
        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public _FinalStage status(Optional<FundingAccountStatus> status) {
            this.status = status;
            return this;
        }

        /**
         * <p>Date and time that the funding account was last modified.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage lastModifiedDate(OffsetDateTime lastModifiedDate) {
            this.lastModifiedDate = Optional.ofNullable(lastModifiedDate);
            return this;
        }

        /**
         * <p>Date and time that the funding account was last modified.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "lastModifiedDate", nulls = Nulls.SKIP)
        public _FinalStage lastModifiedDate(Optional<OffsetDateTime> lastModifiedDate) {
            this.lastModifiedDate = lastModifiedDate;
            return this;
        }

        /**
         * <p>Date and time that we received your request to create the funding account in our system.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage createdDate(OffsetDateTime createdDate) {
            this.createdDate = Optional.ofNullable(createdDate);
            return this;
        }

        /**
         * <p>Date and time that we received your request to create the funding account in our system.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "createdDate", nulls = Nulls.SKIP)
        public _FinalStage createdDate(Optional<OffsetDateTime> createdDate) {
            this.createdDate = createdDate;
            return this;
        }

        /**
         * <p>Unique identifier that we assigned to the funding account.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage fundingAccountId(Integer fundingAccountId) {
            this.fundingAccountId = Optional.ofNullable(fundingAccountId);
            return this;
        }

        /**
         * <p>Unique identifier that we assigned to the funding account.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "fundingAccountId", nulls = Nulls.SKIP)
        public _FinalStage fundingAccountId(Optional<Integer> fundingAccountId) {
            this.fundingAccountId = fundingAccountId;
            return this;
        }

        @java.lang.Override
        public FundingAccount build() {
            return new FundingAccount(
                    fundingAccountId,
                    createdDate,
                    lastModifiedDate,
                    status,
                    type,
                    use,
                    nameOnAccount,
                    paymentMethods,
                    metadata,
                    links,
                    additionalProperties);
        }
    }
}
