/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = IccCardDetails.Builder.class)
public final class IccCardDetails {
    private final Optional<IccCardDetailsDowngradeTo> downgradeTo;

    private final EncryptionCapableDevice device;

    private final String iccData;

    private final Optional<String> firstDigitOfPan;

    private final Optional<String> cardholderSignature;

    private final Optional<EbtDetailsWithVoucher> ebtDetails;

    private final Map<String, Object> additionalProperties;

    private IccCardDetails(
            Optional<IccCardDetailsDowngradeTo> downgradeTo,
            EncryptionCapableDevice device,
            String iccData,
            Optional<String> firstDigitOfPan,
            Optional<String> cardholderSignature,
            Optional<EbtDetailsWithVoucher> ebtDetails,
            Map<String, Object> additionalProperties) {
        this.downgradeTo = downgradeTo;
        this.device = device;
        this.iccData = iccData;
        this.firstDigitOfPan = firstDigitOfPan;
        this.cardholderSignature = cardholderSignature;
        this.ebtDetails = ebtDetails;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return If an offline transaction is not approved using the initial entry method, reprocess the transaction using a downgraded entry method.
     * For example, an Integrated Circuit Card (ICC) transaction can be downgraded to a swiped transaction or a keyed transaction.
     */
    @JsonProperty("downgradeTo")
    public Optional<IccCardDetailsDowngradeTo> getDowngradeTo() {
        return downgradeTo;
    }

    @JsonProperty("device")
    public EncryptionCapableDevice getDevice() {
        return device;
    }

    /**
     * @return Cardholder data from the ICC. The data consists of EMV tags in Tag-Length-Value (TLV) format.
     */
    @JsonProperty("iccData")
    public String getIccData() {
        return iccData;
    }

    /**
     * @return First digit of the card number.
     */
    @JsonProperty("firstDigitOfPan")
    public Optional<String> getFirstDigitOfPan() {
        return firstDigitOfPan;
    }

    /**
     * @return Cardholder's signature. For more information about how to format the signature, go to <a href="https://docs.payroc.com/knowledge/basic-concepts/signature-capture">How to send a signature to our gateway</a>.
     */
    @JsonProperty("cardholderSignature")
    public Optional<String> getCardholderSignature() {
        return cardholderSignature;
    }

    @JsonProperty("ebtDetails")
    public Optional<EbtDetailsWithVoucher> getEbtDetails() {
        return ebtDetails;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof IccCardDetails && equalTo((IccCardDetails) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(IccCardDetails other) {
        return downgradeTo.equals(other.downgradeTo)
                && device.equals(other.device)
                && iccData.equals(other.iccData)
                && firstDigitOfPan.equals(other.firstDigitOfPan)
                && cardholderSignature.equals(other.cardholderSignature)
                && ebtDetails.equals(other.ebtDetails);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.downgradeTo,
                this.device,
                this.iccData,
                this.firstDigitOfPan,
                this.cardholderSignature,
                this.ebtDetails);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static DeviceStage builder() {
        return new Builder();
    }

    public interface DeviceStage {
        IccDataStage device(@NotNull EncryptionCapableDevice device);

        Builder from(IccCardDetails other);
    }

    public interface IccDataStage {
        /**
         * <p>Cardholder data from the ICC. The data consists of EMV tags in Tag-Length-Value (TLV) format.</p>
         */
        _FinalStage iccData(@NotNull String iccData);
    }

    public interface _FinalStage {
        IccCardDetails build();

        /**
         * <p>If an offline transaction is not approved using the initial entry method, reprocess the transaction using a downgraded entry method.
         * For example, an Integrated Circuit Card (ICC) transaction can be downgraded to a swiped transaction or a keyed transaction.</p>
         */
        _FinalStage downgradeTo(Optional<IccCardDetailsDowngradeTo> downgradeTo);

        _FinalStage downgradeTo(IccCardDetailsDowngradeTo downgradeTo);

        /**
         * <p>First digit of the card number.</p>
         */
        _FinalStage firstDigitOfPan(Optional<String> firstDigitOfPan);

        _FinalStage firstDigitOfPan(String firstDigitOfPan);

        /**
         * <p>Cardholder's signature. For more information about how to format the signature, go to <a href="https://docs.payroc.com/knowledge/basic-concepts/signature-capture">How to send a signature to our gateway</a>.</p>
         */
        _FinalStage cardholderSignature(Optional<String> cardholderSignature);

        _FinalStage cardholderSignature(String cardholderSignature);

        _FinalStage ebtDetails(Optional<EbtDetailsWithVoucher> ebtDetails);

        _FinalStage ebtDetails(EbtDetailsWithVoucher ebtDetails);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements DeviceStage, IccDataStage, _FinalStage {
        private EncryptionCapableDevice device;

        private String iccData;

        private Optional<EbtDetailsWithVoucher> ebtDetails = Optional.empty();

        private Optional<String> cardholderSignature = Optional.empty();

        private Optional<String> firstDigitOfPan = Optional.empty();

        private Optional<IccCardDetailsDowngradeTo> downgradeTo = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(IccCardDetails other) {
            downgradeTo(other.getDowngradeTo());
            device(other.getDevice());
            iccData(other.getIccData());
            firstDigitOfPan(other.getFirstDigitOfPan());
            cardholderSignature(other.getCardholderSignature());
            ebtDetails(other.getEbtDetails());
            return this;
        }

        @java.lang.Override
        @JsonSetter("device")
        public IccDataStage device(@NotNull EncryptionCapableDevice device) {
            this.device = Objects.requireNonNull(device, "device must not be null");
            return this;
        }

        /**
         * <p>Cardholder data from the ICC. The data consists of EMV tags in Tag-Length-Value (TLV) format.</p>
         * <p>Cardholder data from the ICC. The data consists of EMV tags in Tag-Length-Value (TLV) format.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("iccData")
        public _FinalStage iccData(@NotNull String iccData) {
            this.iccData = Objects.requireNonNull(iccData, "iccData must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage ebtDetails(EbtDetailsWithVoucher ebtDetails) {
            this.ebtDetails = Optional.ofNullable(ebtDetails);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "ebtDetails", nulls = Nulls.SKIP)
        public _FinalStage ebtDetails(Optional<EbtDetailsWithVoucher> ebtDetails) {
            this.ebtDetails = ebtDetails;
            return this;
        }

        /**
         * <p>Cardholder's signature. For more information about how to format the signature, go to <a href="https://docs.payroc.com/knowledge/basic-concepts/signature-capture">How to send a signature to our gateway</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage cardholderSignature(String cardholderSignature) {
            this.cardholderSignature = Optional.ofNullable(cardholderSignature);
            return this;
        }

        /**
         * <p>Cardholder's signature. For more information about how to format the signature, go to <a href="https://docs.payroc.com/knowledge/basic-concepts/signature-capture">How to send a signature to our gateway</a>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "cardholderSignature", nulls = Nulls.SKIP)
        public _FinalStage cardholderSignature(Optional<String> cardholderSignature) {
            this.cardholderSignature = cardholderSignature;
            return this;
        }

        /**
         * <p>First digit of the card number.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage firstDigitOfPan(String firstDigitOfPan) {
            this.firstDigitOfPan = Optional.ofNullable(firstDigitOfPan);
            return this;
        }

        /**
         * <p>First digit of the card number.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "firstDigitOfPan", nulls = Nulls.SKIP)
        public _FinalStage firstDigitOfPan(Optional<String> firstDigitOfPan) {
            this.firstDigitOfPan = firstDigitOfPan;
            return this;
        }

        /**
         * <p>If an offline transaction is not approved using the initial entry method, reprocess the transaction using a downgraded entry method.
         * For example, an Integrated Circuit Card (ICC) transaction can be downgraded to a swiped transaction or a keyed transaction.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage downgradeTo(IccCardDetailsDowngradeTo downgradeTo) {
            this.downgradeTo = Optional.ofNullable(downgradeTo);
            return this;
        }

        /**
         * <p>If an offline transaction is not approved using the initial entry method, reprocess the transaction using a downgraded entry method.
         * For example, an Integrated Circuit Card (ICC) transaction can be downgraded to a swiped transaction or a keyed transaction.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "downgradeTo", nulls = Nulls.SKIP)
        public _FinalStage downgradeTo(Optional<IccCardDetailsDowngradeTo> downgradeTo) {
            this.downgradeTo = downgradeTo;
            return this;
        }

        @java.lang.Override
        public IccCardDetails build() {
            return new IccCardDetails(
                    downgradeTo,
                    device,
                    iccData,
                    firstDigitOfPan,
                    cardholderSignature,
                    ebtDetails,
                    additionalProperties);
        }
    }
}
