/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class InstructionMerchantsItemRecipientsItemPaymentMethod {
    public static final InstructionMerchantsItemRecipientsItemPaymentMethod ACH =
            new InstructionMerchantsItemRecipientsItemPaymentMethod(Value.ACH, "ACH");

    private final Value value;

    private final String string;

    InstructionMerchantsItemRecipientsItemPaymentMethod(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof InstructionMerchantsItemRecipientsItemPaymentMethod
                        && this.string.equals(((InstructionMerchantsItemRecipientsItemPaymentMethod) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ACH:
                return visitor.visitAch();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static InstructionMerchantsItemRecipientsItemPaymentMethod valueOf(String value) {
        switch (value) {
            case "ACH":
                return ACH;
            default:
                return new InstructionMerchantsItemRecipientsItemPaymentMethod(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ACH,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAch();

        T visitUnknown(String unknownType);
    }
}
