/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = InterchangePlusPlusUs52.Builder.class)
public final class InterchangePlusPlusUs52 {
    private final InterchangePlusPlusUs52Fees fees;

    private final Map<String, Object> additionalProperties;

    private InterchangePlusPlusUs52(InterchangePlusPlusUs52Fees fees, Map<String, Object> additionalProperties) {
        this.fees = fees;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Object that contains information about the fees.
     */
    @JsonProperty("fees")
    public InterchangePlusPlusUs52Fees getFees() {
        return fees;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof InterchangePlusPlusUs52 && equalTo((InterchangePlusPlusUs52) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(InterchangePlusPlusUs52 other) {
        return fees.equals(other.fees);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.fees);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static FeesStage builder() {
        return new Builder();
    }

    public interface FeesStage {
        /**
         * <p>Object that contains information about the fees.</p>
         */
        _FinalStage fees(@NotNull InterchangePlusPlusUs52Fees fees);

        Builder from(InterchangePlusPlusUs52 other);
    }

    public interface _FinalStage {
        InterchangePlusPlusUs52 build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements FeesStage, _FinalStage {
        private InterchangePlusPlusUs52Fees fees;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(InterchangePlusPlusUs52 other) {
            fees(other.getFees());
            return this;
        }

        /**
         * <p>Object that contains information about the fees.</p>
         * <p>Object that contains information about the fees.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("fees")
        public _FinalStage fees(@NotNull InterchangePlusPlusUs52Fees fees) {
            this.fees = Objects.requireNonNull(fees, "fees must not be null");
            return this;
        }

        @java.lang.Override
        public InterchangePlusPlusUs52 build() {
            return new InterchangePlusPlusUs52(fees, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
