/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import java.util.List;
import java.util.Optional;

public interface IPricingAgreementUs52 {
    PricingAgreementUs52Country getCountry();

    PricingAgreementUs52Version getVersion();

    BaseUs getBase();

    Optional<PricingAgreementUs52Processor> getProcessor();

    Optional<GatewayUs52> getGateway();

    Optional<List<ServiceUs50>> getServices();
}
