/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import java.util.Optional;

public interface ISubscriptionRecurringOrderBase {
    Optional<Long> getAmount();

    Optional<String> getDescription();
}
