/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PatchCopy.Builder.class)
public final class PatchCopy {
    private final String from;

    private final String path;

    private final Map<String, Object> additionalProperties;

    private PatchCopy(String from, String path, Map<String, Object> additionalProperties) {
        this.from = from;
        this.path = path;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Location of the value that you want to copy.
     * The format for this value is JSON Pointer.
     */
    @JsonProperty("from")
    public String getFrom() {
        return from;
    }

    /**
     * @return Location where you want to copy the value to.
     * The format for this value is JSON Pointer.
     */
    @JsonProperty("path")
    public String getPath() {
        return path;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PatchCopy && equalTo((PatchCopy) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PatchCopy other) {
        return from.equals(other.from) && path.equals(other.path);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.from, this.path);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static FromStage builder() {
        return new Builder();
    }

    public interface FromStage {
        /**
         * <p>Location of the value that you want to copy.
         * The format for this value is JSON Pointer.</p>
         */
        PathStage from(@NotNull String from);

        Builder from(PatchCopy other);
    }

    public interface PathStage {
        /**
         * <p>Location where you want to copy the value to.
         * The format for this value is JSON Pointer.</p>
         */
        _FinalStage path(@NotNull String path);
    }

    public interface _FinalStage {
        PatchCopy build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements FromStage, PathStage, _FinalStage {
        private String from;

        private String path;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PatchCopy other) {
            from(other.getFrom());
            path(other.getPath());
            return this;
        }

        /**
         * <p>Location of the value that you want to copy.
         * The format for this value is JSON Pointer.</p>
         * <p>Location of the value that you want to copy.
         * The format for this value is JSON Pointer.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("from")
        public PathStage from(@NotNull String from) {
            this.from = Objects.requireNonNull(from, "from must not be null");
            return this;
        }

        /**
         * <p>Location where you want to copy the value to.
         * The format for this value is JSON Pointer.</p>
         * <p>Location where you want to copy the value to.
         * The format for this value is JSON Pointer.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("path")
        public _FinalStage path(@NotNull String path) {
            this.path = Objects.requireNonNull(path, "path must not be null");
            return this;
        }

        @java.lang.Override
        public PatchCopy build() {
            return new PatchCopy(from, path, additionalProperties);
        }
    }
}
