/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PricingAgreementUs50Country {
    public static final PricingAgreementUs50Country US = new PricingAgreementUs50Country(Value.US, "US");

    private final Value value;

    private final String string;

    PricingAgreementUs50Country(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PricingAgreementUs50Country
                        && this.string.equals(((PricingAgreementUs50Country) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case US:
                return visitor.visitUs();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PricingAgreementUs50Country valueOf(String value) {
        switch (value) {
            case "US":
                return US;
            default:
                return new PricingAgreementUs50Country(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        US,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitUs();

        T visitUnknown(String unknownType);
    }
}
