/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ProcessingCardAcceptanceSpecialityCardsAmericanExpressDirect.Builder.class)
public final class ProcessingCardAcceptanceSpecialityCardsAmericanExpressDirect {
    private final Optional<Boolean> enabled;

    private final Optional<String> merchantNumber;

    private final Map<String, Object> additionalProperties;

    private ProcessingCardAcceptanceSpecialityCardsAmericanExpressDirect(
            Optional<Boolean> enabled, Optional<String> merchantNumber, Map<String, Object> additionalProperties) {
        this.enabled = enabled;
        this.merchantNumber = merchantNumber;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Indicates if the merchant accepts American Express Direct.
     */
    @JsonProperty("enabled")
    public Optional<Boolean> getEnabled() {
        return enabled;
    }

    /**
     * @return If the merchant accepts American Express Direct, provide their American Express merchant number.
     */
    @JsonProperty("merchantNumber")
    public Optional<String> getMerchantNumber() {
        return merchantNumber;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ProcessingCardAcceptanceSpecialityCardsAmericanExpressDirect
                && equalTo((ProcessingCardAcceptanceSpecialityCardsAmericanExpressDirect) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ProcessingCardAcceptanceSpecialityCardsAmericanExpressDirect other) {
        return enabled.equals(other.enabled) && merchantNumber.equals(other.merchantNumber);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.enabled, this.merchantNumber);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> enabled = Optional.empty();

        private Optional<String> merchantNumber = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ProcessingCardAcceptanceSpecialityCardsAmericanExpressDirect other) {
            enabled(other.getEnabled());
            merchantNumber(other.getMerchantNumber());
            return this;
        }

        /**
         * <p>Indicates if the merchant accepts American Express Direct.</p>
         */
        @JsonSetter(value = "enabled", nulls = Nulls.SKIP)
        public Builder enabled(Optional<Boolean> enabled) {
            this.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            this.enabled = Optional.ofNullable(enabled);
            return this;
        }

        /**
         * <p>If the merchant accepts American Express Direct, provide their American Express merchant number.</p>
         */
        @JsonSetter(value = "merchantNumber", nulls = Nulls.SKIP)
        public Builder merchantNumber(Optional<String> merchantNumber) {
            this.merchantNumber = merchantNumber;
            return this;
        }

        public Builder merchantNumber(String merchantNumber) {
            this.merchantNumber = Optional.ofNullable(merchantNumber);
            return this;
        }

        public ProcessingCardAcceptanceSpecialityCardsAmericanExpressDirect build() {
            return new ProcessingCardAcceptanceSpecialityCardsAmericanExpressDirect(
                    enabled, merchantNumber, additionalProperties);
        }
    }
}
