/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class RawCardDetailsDowngradeTo {
    public static final RawCardDetailsDowngradeTo KEYED = new RawCardDetailsDowngradeTo(Value.KEYED, "keyed");

    public static final RawCardDetailsDowngradeTo SWIPED = new RawCardDetailsDowngradeTo(Value.SWIPED, "swiped");

    private final Value value;

    private final String string;

    RawCardDetailsDowngradeTo(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof RawCardDetailsDowngradeTo
                        && this.string.equals(((RawCardDetailsDowngradeTo) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case KEYED:
                return visitor.visitKeyed();
            case SWIPED:
                return visitor.visitSwiped();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static RawCardDetailsDowngradeTo valueOf(String value) {
        switch (value) {
            case "keyed":
                return KEYED;
            case "swiped":
                return SWIPED;
            default:
                return new RawCardDetailsDowngradeTo(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        KEYED,

        SWIPED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitKeyed();

        T visitSwiped();

        T visitUnknown(String unknownType);
    }
}
