/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class RefundSummaryStatus {
    public static final RefundSummaryStatus DECLINED = new RefundSummaryStatus(Value.DECLINED, "declined");

    public static final RefundSummaryStatus REVERSAL = new RefundSummaryStatus(Value.REVERSAL, "reversal");

    public static final RefundSummaryStatus COMPLETE = new RefundSummaryStatus(Value.COMPLETE, "complete");

    public static final RefundSummaryStatus PICKUP = new RefundSummaryStatus(Value.PICKUP, "pickup");

    public static final RefundSummaryStatus PENDING = new RefundSummaryStatus(Value.PENDING, "pending");

    public static final RefundSummaryStatus ADMIN = new RefundSummaryStatus(Value.ADMIN, "admin");

    public static final RefundSummaryStatus RETURNED = new RefundSummaryStatus(Value.RETURNED, "returned");

    public static final RefundSummaryStatus READY = new RefundSummaryStatus(Value.READY, "ready");

    public static final RefundSummaryStatus ACCEPTED = new RefundSummaryStatus(Value.ACCEPTED, "accepted");

    public static final RefundSummaryStatus EXPIRED = new RefundSummaryStatus(Value.EXPIRED, "expired");

    public static final RefundSummaryStatus REFERRAL = new RefundSummaryStatus(Value.REFERRAL, "referral");

    private final Value value;

    private final String string;

    RefundSummaryStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof RefundSummaryStatus && this.string.equals(((RefundSummaryStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DECLINED:
                return visitor.visitDeclined();
            case REVERSAL:
                return visitor.visitReversal();
            case COMPLETE:
                return visitor.visitComplete();
            case PICKUP:
                return visitor.visitPickup();
            case PENDING:
                return visitor.visitPending();
            case ADMIN:
                return visitor.visitAdmin();
            case RETURNED:
                return visitor.visitReturned();
            case READY:
                return visitor.visitReady();
            case ACCEPTED:
                return visitor.visitAccepted();
            case EXPIRED:
                return visitor.visitExpired();
            case REFERRAL:
                return visitor.visitReferral();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static RefundSummaryStatus valueOf(String value) {
        switch (value) {
            case "declined":
                return DECLINED;
            case "reversal":
                return REVERSAL;
            case "complete":
                return COMPLETE;
            case "pickup":
                return PICKUP;
            case "pending":
                return PENDING;
            case "admin":
                return ADMIN;
            case "returned":
                return RETURNED;
            case "ready":
                return READY;
            case "accepted":
                return ACCEPTED;
            case "expired":
                return EXPIRED;
            case "referral":
                return REFERRAL;
            default:
                return new RefundSummaryStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        READY,

        PENDING,

        DECLINED,

        COMPLETE,

        REFERRAL,

        PICKUP,

        REVERSAL,

        RETURNED,

        ADMIN,

        EXPIRED,

        ACCEPTED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitReady();

        T visitPending();

        T visitDeclined();

        T visitComplete();

        T visitReferral();

        T visitPickup();

        T visitReversal();

        T visitReturned();

        T visitAdmin();

        T visitExpired();

        T visitAccepted();

        T visitUnknown(String unknownType);
    }
}
