/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class SchemasCredentialOnFileMitAgreement {
    public static final SchemasCredentialOnFileMitAgreement RECURRING =
            new SchemasCredentialOnFileMitAgreement(Value.RECURRING, "recurring");

    public static final SchemasCredentialOnFileMitAgreement INSTALLMENT =
            new SchemasCredentialOnFileMitAgreement(Value.INSTALLMENT, "installment");

    public static final SchemasCredentialOnFileMitAgreement UNSCHEDULED =
            new SchemasCredentialOnFileMitAgreement(Value.UNSCHEDULED, "unscheduled");

    private final Value value;

    private final String string;

    SchemasCredentialOnFileMitAgreement(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof SchemasCredentialOnFileMitAgreement
                        && this.string.equals(((SchemasCredentialOnFileMitAgreement) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case RECURRING:
                return visitor.visitRecurring();
            case INSTALLMENT:
                return visitor.visitInstallment();
            case UNSCHEDULED:
                return visitor.visitUnscheduled();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SchemasCredentialOnFileMitAgreement valueOf(String value) {
        switch (value) {
            case "recurring":
                return RECURRING;
            case "installment":
                return INSTALLMENT;
            case "unscheduled":
                return UNSCHEDULED;
            default:
                return new SchemasCredentialOnFileMitAgreement(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        UNSCHEDULED,

        RECURRING,

        INSTALLMENT,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitUnscheduled();

        T visitRecurring();

        T visitInstallment();

        T visitUnknown(String unknownType);
    }
}
