/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class SecurityCheckCvvResult {
    public static final SecurityCheckCvvResult M = new SecurityCheckCvvResult(Value.M, "M");

    public static final SecurityCheckCvvResult N = new SecurityCheckCvvResult(Value.N, "N");

    public static final SecurityCheckCvvResult U = new SecurityCheckCvvResult(Value.U, "U");

    public static final SecurityCheckCvvResult P = new SecurityCheckCvvResult(Value.P, "P");

    private final Value value;

    private final String string;

    SecurityCheckCvvResult(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof SecurityCheckCvvResult
                        && this.string.equals(((SecurityCheckCvvResult) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case M:
                return visitor.visitM();
            case N:
                return visitor.visitN();
            case U:
                return visitor.visitU();
            case P:
                return visitor.visitP();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SecurityCheckCvvResult valueOf(String value) {
        switch (value) {
            case "M":
                return M;
            case "N":
                return N;
            case "U":
                return U;
            case "P":
                return P;
            default:
                return new SecurityCheckCvvResult(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        M,

        N,

        P,

        U,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitM();

        T visitN();

        T visitP();

        T visitU();

        T visitUnknown(String unknownType);
    }
}
