/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class SingleUseTokenPayloadSecCode {
    public static final SingleUseTokenPayloadSecCode CCD = new SingleUseTokenPayloadSecCode(Value.CCD, "ccd");

    public static final SingleUseTokenPayloadSecCode WEB = new SingleUseTokenPayloadSecCode(Value.WEB, "web");

    public static final SingleUseTokenPayloadSecCode PPD = new SingleUseTokenPayloadSecCode(Value.PPD, "ppd");

    public static final SingleUseTokenPayloadSecCode TEL = new SingleUseTokenPayloadSecCode(Value.TEL, "tel");

    private final Value value;

    private final String string;

    SingleUseTokenPayloadSecCode(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof SingleUseTokenPayloadSecCode
                        && this.string.equals(((SingleUseTokenPayloadSecCode) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case CCD:
                return visitor.visitCcd();
            case WEB:
                return visitor.visitWeb();
            case PPD:
                return visitor.visitPpd();
            case TEL:
                return visitor.visitTel();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SingleUseTokenPayloadSecCode valueOf(String value) {
        switch (value) {
            case "ccd":
                return CCD;
            case "web":
                return WEB;
            case "ppd":
                return PPD;
            case "tel":
                return TEL;
            default:
                return new SingleUseTokenPayloadSecCode(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        WEB,

        TEL,

        CCD,

        PPD,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitWeb();

        T visitTel();

        T visitCcd();

        T visitPpd();

        T visitUnknown(String unknownType);
    }
}
