/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = StatusAdjustment.Builder.class)
public final class StatusAdjustment {
    private final StatusAdjustmentToStatus toStatus;

    private final Map<String, Object> additionalProperties;

    private StatusAdjustment(StatusAdjustmentToStatus toStatus, Map<String, Object> additionalProperties) {
        this.toStatus = toStatus;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Status that you want to change the transaction to.
     */
    @JsonProperty("toStatus")
    public StatusAdjustmentToStatus getToStatus() {
        return toStatus;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof StatusAdjustment && equalTo((StatusAdjustment) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(StatusAdjustment other) {
        return toStatus.equals(other.toStatus);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.toStatus);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ToStatusStage builder() {
        return new Builder();
    }

    public interface ToStatusStage {
        /**
         * <p>Status that you want to change the transaction to.</p>
         */
        _FinalStage toStatus(@NotNull StatusAdjustmentToStatus toStatus);

        Builder from(StatusAdjustment other);
    }

    public interface _FinalStage {
        StatusAdjustment build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ToStatusStage, _FinalStage {
        private StatusAdjustmentToStatus toStatus;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(StatusAdjustment other) {
            toStatus(other.getToStatus());
            return this;
        }

        /**
         * <p>Status that you want to change the transaction to.</p>
         * <p>Status that you want to change the transaction to.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("toStatus")
        public _FinalStage toStatus(@NotNull StatusAdjustmentToStatus toStatus) {
            this.toStatus = Objects.requireNonNull(toStatus, "toStatus must not be null");
            return this;
        }

        @java.lang.Override
        public StatusAdjustment build() {
            return new StatusAdjustment(toStatus, additionalProperties);
        }
    }
}
