/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TerminalOrderShippingPreferences.Builder.class)
public final class TerminalOrderShippingPreferences {
    private final Optional<TerminalOrderShippingPreferencesMethod> method;

    private final Optional<Boolean> saturdayDelivery;

    private final Map<String, Object> additionalProperties;

    private TerminalOrderShippingPreferences(
            Optional<TerminalOrderShippingPreferencesMethod> method,
            Optional<Boolean> saturdayDelivery,
            Map<String, Object> additionalProperties) {
        this.method = method;
        this.saturdayDelivery = saturdayDelivery;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Shipping method for the terminal order. Send one of the following values:
     * <ul>
     * <li><code>nextDay</code> - We schedule the order to be delivered the next day.</li>
     * <li><code>ground</code> - We ship the order with ground shipping.</li>
     * </ul>
     */
    @JsonProperty("method")
    public Optional<TerminalOrderShippingPreferencesMethod> getMethod() {
        return method;
    }

    /**
     * @return Indicates if we can schedule the terminal order to be delivered on a Saturday.
     */
    @JsonProperty("saturdayDelivery")
    public Optional<Boolean> getSaturdayDelivery() {
        return saturdayDelivery;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TerminalOrderShippingPreferences && equalTo((TerminalOrderShippingPreferences) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TerminalOrderShippingPreferences other) {
        return method.equals(other.method) && saturdayDelivery.equals(other.saturdayDelivery);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.method, this.saturdayDelivery);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<TerminalOrderShippingPreferencesMethod> method = Optional.empty();

        private Optional<Boolean> saturdayDelivery = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TerminalOrderShippingPreferences other) {
            method(other.getMethod());
            saturdayDelivery(other.getSaturdayDelivery());
            return this;
        }

        /**
         * <p>Shipping method for the terminal order. Send one of the following values:</p>
         * <ul>
         * <li><code>nextDay</code> - We schedule the order to be delivered the next day.</li>
         * <li><code>ground</code> - We ship the order with ground shipping.</li>
         * </ul>
         */
        @JsonSetter(value = "method", nulls = Nulls.SKIP)
        public Builder method(Optional<TerminalOrderShippingPreferencesMethod> method) {
            this.method = method;
            return this;
        }

        public Builder method(TerminalOrderShippingPreferencesMethod method) {
            this.method = Optional.ofNullable(method);
            return this;
        }

        /**
         * <p>Indicates if we can schedule the terminal order to be delivered on a Saturday.</p>
         */
        @JsonSetter(value = "saturdayDelivery", nulls = Nulls.SKIP)
        public Builder saturdayDelivery(Optional<Boolean> saturdayDelivery) {
            this.saturdayDelivery = saturdayDelivery;
            return this;
        }

        public Builder saturdayDelivery(Boolean saturdayDelivery) {
            this.saturdayDelivery = Optional.ofNullable(saturdayDelivery);
            return this;
        }

        public TerminalOrderShippingPreferences build() {
            return new TerminalOrderShippingPreferences(method, saturdayDelivery, additionalProperties);
        }
    }
}
