/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TerminalOrderOrderItemsItem.Builder.class)
public final class TerminalOrderOrderItemsItem implements IOrderItem, ILinks {
    private final OrderItemType type;

    private final String solutionTemplateId;

    private final Optional<Float> solutionQuantity;

    private final Optional<OrderItemDeviceCondition> deviceCondition;

    private final Optional<OrderItemSolutionSetup> solutionSetup;

    private final Optional<List<ProcessingTerminalSummary>> links;

    private final Map<String, Object> additionalProperties;

    private TerminalOrderOrderItemsItem(
            OrderItemType type,
            String solutionTemplateId,
            Optional<Float> solutionQuantity,
            Optional<OrderItemDeviceCondition> deviceCondition,
            Optional<OrderItemSolutionSetup> solutionSetup,
            Optional<List<ProcessingTerminalSummary>> links,
            Map<String, Object> additionalProperties) {
        this.type = type;
        this.solutionTemplateId = solutionTemplateId;
        this.solutionQuantity = solutionQuantity;
        this.deviceCondition = deviceCondition;
        this.solutionSetup = solutionSetup;
        this.links = links;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Type of item.
     */
    @JsonProperty("type")
    public OrderItemType getType() {
        return type;
    }

    /**
     * @return Unique identifier of the solution. Send one of the following values:
     * <ul>
     * <li><code>Roc Services_DX8000</code></li>
     * <li><code>Roc Services_DX4000</code></li>
     * <li><code>Roc Services_Web</code></li>
     * <li><code>Roc Services_Mobile</code></li>
     * <li><code>Payroc DX8000</code></li>
     * <li><code>Payroc DX4000</code></li>
     * <li><code>Payroc RX7000_Cloud</code></li>
     * <li><code>Payroc DX8000_Cloud</code></li>
     * <li><code>Payroc DX4000_Cloud</code></li>
     * <li><code>Payroc A920Pro</code></li>
     * <li><code>Payroc A80</code></li>
     * <li><code>Payroc A920Pro_Cloud</code></li>
     * <li><code>Payroc A80_Cloud</code></li>
     * <li><code>Roc Terminal Plus_N950</code></li>
     * <li><code>Roc Terminal Plus_N950-S</code></li>
     * <li><code>Roc Terminal Plus_X800</code></li>
     * <li><code>Gateway_Payroc</code></li>
     * <li><code>VAR_Only_TSYS</code></li>
     * <li><code>ROC Services Chipper3X</code></li>
     * <li><code>BBPOS Chipper 3X</code></li>
     * <li><code>Augusta EMV</code></li>
     * <li><code>Ingenico - AXIUM Full Functional Base</code></li>
     * <li><code>Pax A920 Charging Base</code></li>
     * <li><code>Pax A920 Comms Base</code></li>
     * <li><code>A920 Pro Ethernet</code></li>
     * <li><code>Axium Bundle</code></li>
     * </ul>
     */
    @JsonProperty("solutionTemplateId")
    @java.lang.Override
    public String getSolutionTemplateId() {
        return solutionTemplateId;
    }

    /**
     * @return Quantity of the solution.
     */
    @JsonProperty("solutionQuantity")
    @java.lang.Override
    public Optional<Float> getSolutionQuantity() {
        return solutionQuantity;
    }

    /**
     * @return Indicates if the order contains a new item or a refurbished item.
     */
    @JsonProperty("deviceCondition")
    public Optional<OrderItemDeviceCondition> getDeviceCondition() {
        return deviceCondition;
    }

    /**
     * @return Object that contains the settings for the solution, including gateway settings, device settings, and application settings.
     */
    @JsonProperty("solutionSetup")
    public Optional<OrderItemSolutionSetup> getSolutionSetup() {
        return solutionSetup;
    }

    @JsonProperty("links")
    @java.lang.Override
    public Optional<List<ProcessingTerminalSummary>> getLinks() {
        return links;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TerminalOrderOrderItemsItem && equalTo((TerminalOrderOrderItemsItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TerminalOrderOrderItemsItem other) {
        return type.equals(other.type)
                && solutionTemplateId.equals(other.solutionTemplateId)
                && solutionQuantity.equals(other.solutionQuantity)
                && deviceCondition.equals(other.deviceCondition)
                && solutionSetup.equals(other.solutionSetup)
                && links.equals(other.links);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.type,
                this.solutionTemplateId,
                this.solutionQuantity,
                this.deviceCondition,
                this.solutionSetup,
                this.links);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TypeStage builder() {
        return new Builder();
    }

    public interface TypeStage {
        /**
         * <p>Type of item.</p>
         */
        SolutionTemplateIdStage type(@NotNull OrderItemType type);

        Builder from(TerminalOrderOrderItemsItem other);
    }

    public interface SolutionTemplateIdStage {
        /**
         * <p>Unique identifier of the solution. Send one of the following values:</p>
         * <ul>
         * <li><code>Roc Services_DX8000</code></li>
         * <li><code>Roc Services_DX4000</code></li>
         * <li><code>Roc Services_Web</code></li>
         * <li><code>Roc Services_Mobile</code></li>
         * <li><code>Payroc DX8000</code></li>
         * <li><code>Payroc DX4000</code></li>
         * <li><code>Payroc RX7000_Cloud</code></li>
         * <li><code>Payroc DX8000_Cloud</code></li>
         * <li><code>Payroc DX4000_Cloud</code></li>
         * <li><code>Payroc A920Pro</code></li>
         * <li><code>Payroc A80</code></li>
         * <li><code>Payroc A920Pro_Cloud</code></li>
         * <li><code>Payroc A80_Cloud</code></li>
         * <li><code>Roc Terminal Plus_N950</code></li>
         * <li><code>Roc Terminal Plus_N950-S</code></li>
         * <li><code>Roc Terminal Plus_X800</code></li>
         * <li><code>Gateway_Payroc</code></li>
         * <li><code>VAR_Only_TSYS</code></li>
         * <li><code>ROC Services Chipper3X</code></li>
         * <li><code>BBPOS Chipper 3X</code></li>
         * <li><code>Augusta EMV</code></li>
         * <li><code>Ingenico - AXIUM Full Functional Base</code></li>
         * <li><code>Pax A920 Charging Base</code></li>
         * <li><code>Pax A920 Comms Base</code></li>
         * <li><code>A920 Pro Ethernet</code></li>
         * <li><code>Axium Bundle</code></li>
         * </ul>
         */
        _FinalStage solutionTemplateId(@NotNull String solutionTemplateId);
    }

    public interface _FinalStage {
        TerminalOrderOrderItemsItem build();

        /**
         * <p>Quantity of the solution.</p>
         */
        _FinalStage solutionQuantity(Optional<Float> solutionQuantity);

        _FinalStage solutionQuantity(Float solutionQuantity);

        /**
         * <p>Indicates if the order contains a new item or a refurbished item.</p>
         */
        _FinalStage deviceCondition(Optional<OrderItemDeviceCondition> deviceCondition);

        _FinalStage deviceCondition(OrderItemDeviceCondition deviceCondition);

        /**
         * <p>Object that contains the settings for the solution, including gateway settings, device settings, and application settings.</p>
         */
        _FinalStage solutionSetup(Optional<OrderItemSolutionSetup> solutionSetup);

        _FinalStage solutionSetup(OrderItemSolutionSetup solutionSetup);

        _FinalStage links(Optional<List<ProcessingTerminalSummary>> links);

        _FinalStage links(List<ProcessingTerminalSummary> links);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, SolutionTemplateIdStage, _FinalStage {
        private OrderItemType type;

        private String solutionTemplateId;

        private Optional<List<ProcessingTerminalSummary>> links = Optional.empty();

        private Optional<OrderItemSolutionSetup> solutionSetup = Optional.empty();

        private Optional<OrderItemDeviceCondition> deviceCondition = Optional.empty();

        private Optional<Float> solutionQuantity = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(TerminalOrderOrderItemsItem other) {
            type(other.getType());
            solutionTemplateId(other.getSolutionTemplateId());
            solutionQuantity(other.getSolutionQuantity());
            deviceCondition(other.getDeviceCondition());
            solutionSetup(other.getSolutionSetup());
            links(other.getLinks());
            return this;
        }

        /**
         * <p>Type of item.</p>
         * <p>Type of item.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("type")
        public SolutionTemplateIdStage type(@NotNull OrderItemType type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        /**
         * <p>Unique identifier of the solution. Send one of the following values:</p>
         * <ul>
         * <li><code>Roc Services_DX8000</code></li>
         * <li><code>Roc Services_DX4000</code></li>
         * <li><code>Roc Services_Web</code></li>
         * <li><code>Roc Services_Mobile</code></li>
         * <li><code>Payroc DX8000</code></li>
         * <li><code>Payroc DX4000</code></li>
         * <li><code>Payroc RX7000_Cloud</code></li>
         * <li><code>Payroc DX8000_Cloud</code></li>
         * <li><code>Payroc DX4000_Cloud</code></li>
         * <li><code>Payroc A920Pro</code></li>
         * <li><code>Payroc A80</code></li>
         * <li><code>Payroc A920Pro_Cloud</code></li>
         * <li><code>Payroc A80_Cloud</code></li>
         * <li><code>Roc Terminal Plus_N950</code></li>
         * <li><code>Roc Terminal Plus_N950-S</code></li>
         * <li><code>Roc Terminal Plus_X800</code></li>
         * <li><code>Gateway_Payroc</code></li>
         * <li><code>VAR_Only_TSYS</code></li>
         * <li><code>ROC Services Chipper3X</code></li>
         * <li><code>BBPOS Chipper 3X</code></li>
         * <li><code>Augusta EMV</code></li>
         * <li><code>Ingenico - AXIUM Full Functional Base</code></li>
         * <li><code>Pax A920 Charging Base</code></li>
         * <li><code>Pax A920 Comms Base</code></li>
         * <li><code>A920 Pro Ethernet</code></li>
         * <li><code>Axium Bundle</code></li>
         * </ul>
         * <p>Unique identifier of the solution. Send one of the following values:</p>
         * <ul>
         * <li><code>Roc Services_DX8000</code></li>
         * <li><code>Roc Services_DX4000</code></li>
         * <li><code>Roc Services_Web</code></li>
         * <li><code>Roc Services_Mobile</code></li>
         * <li><code>Payroc DX8000</code></li>
         * <li><code>Payroc DX4000</code></li>
         * <li><code>Payroc RX7000_Cloud</code></li>
         * <li><code>Payroc DX8000_Cloud</code></li>
         * <li><code>Payroc DX4000_Cloud</code></li>
         * <li><code>Payroc A920Pro</code></li>
         * <li><code>Payroc A80</code></li>
         * <li><code>Payroc A920Pro_Cloud</code></li>
         * <li><code>Payroc A80_Cloud</code></li>
         * <li><code>Roc Terminal Plus_N950</code></li>
         * <li><code>Roc Terminal Plus_N950-S</code></li>
         * <li><code>Roc Terminal Plus_X800</code></li>
         * <li><code>Gateway_Payroc</code></li>
         * <li><code>VAR_Only_TSYS</code></li>
         * <li><code>ROC Services Chipper3X</code></li>
         * <li><code>BBPOS Chipper 3X</code></li>
         * <li><code>Augusta EMV</code></li>
         * <li><code>Ingenico - AXIUM Full Functional Base</code></li>
         * <li><code>Pax A920 Charging Base</code></li>
         * <li><code>Pax A920 Comms Base</code></li>
         * <li><code>A920 Pro Ethernet</code></li>
         * <li><code>Axium Bundle</code></li>
         * </ul>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("solutionTemplateId")
        public _FinalStage solutionTemplateId(@NotNull String solutionTemplateId) {
            this.solutionTemplateId = Objects.requireNonNull(solutionTemplateId, "solutionTemplateId must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage links(List<ProcessingTerminalSummary> links) {
            this.links = Optional.ofNullable(links);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "links", nulls = Nulls.SKIP)
        public _FinalStage links(Optional<List<ProcessingTerminalSummary>> links) {
            this.links = links;
            return this;
        }

        /**
         * <p>Object that contains the settings for the solution, including gateway settings, device settings, and application settings.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage solutionSetup(OrderItemSolutionSetup solutionSetup) {
            this.solutionSetup = Optional.ofNullable(solutionSetup);
            return this;
        }

        /**
         * <p>Object that contains the settings for the solution, including gateway settings, device settings, and application settings.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "solutionSetup", nulls = Nulls.SKIP)
        public _FinalStage solutionSetup(Optional<OrderItemSolutionSetup> solutionSetup) {
            this.solutionSetup = solutionSetup;
            return this;
        }

        /**
         * <p>Indicates if the order contains a new item or a refurbished item.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage deviceCondition(OrderItemDeviceCondition deviceCondition) {
            this.deviceCondition = Optional.ofNullable(deviceCondition);
            return this;
        }

        /**
         * <p>Indicates if the order contains a new item or a refurbished item.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "deviceCondition", nulls = Nulls.SKIP)
        public _FinalStage deviceCondition(Optional<OrderItemDeviceCondition> deviceCondition) {
            this.deviceCondition = deviceCondition;
            return this;
        }

        /**
         * <p>Quantity of the solution.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage solutionQuantity(Float solutionQuantity) {
            this.solutionQuantity = Optional.ofNullable(solutionQuantity);
            return this;
        }

        /**
         * <p>Quantity of the solution.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "solutionQuantity", nulls = Nulls.SKIP)
        public _FinalStage solutionQuantity(Optional<Float> solutionQuantity) {
            this.solutionQuantity = solutionQuantity;
            return this;
        }

        @java.lang.Override
        public TerminalOrderOrderItemsItem build() {
            return new TerminalOrderOrderItemsItem(
                    type,
                    solutionTemplateId,
                    solutionQuantity,
                    deviceCondition,
                    solutionSetup,
                    links,
                    additionalProperties);
        }
    }
}
