/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Tiered3Fees.Builder.class)
public final class Tiered3Fees {
    private final QualRates mastercardVisaDiscover;

    private final Optional<Tiered3FeesAmex> amex;

    private final Optional<PinDebit> pinDebit;

    private final Optional<ElectronicBenefitsTransfer> electronicBenefitsTransfer;

    private final Optional<SpecialityCards> specialityCards;

    private final Map<String, Object> additionalProperties;

    private Tiered3Fees(
            QualRates mastercardVisaDiscover,
            Optional<Tiered3FeesAmex> amex,
            Optional<PinDebit> pinDebit,
            Optional<ElectronicBenefitsTransfer> electronicBenefitsTransfer,
            Optional<SpecialityCards> specialityCards,
            Map<String, Object> additionalProperties) {
        this.mastercardVisaDiscover = mastercardVisaDiscover;
        this.amex = amex;
        this.pinDebit = pinDebit;
        this.electronicBenefitsTransfer = electronicBenefitsTransfer;
        this.specialityCards = specialityCards;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Object that contains the fees for Mastercard, Visa, and Discover transactions.
     */
    @JsonProperty("mastercardVisaDiscover")
    public QualRates getMastercardVisaDiscover() {
        return mastercardVisaDiscover;
    }

    /**
     * @return Object that contains the fees for American Express transactions.
     */
    @JsonProperty("amex")
    public Optional<Tiered3FeesAmex> getAmex() {
        return amex;
    }

    @JsonProperty("pinDebit")
    public Optional<PinDebit> getPinDebit() {
        return pinDebit;
    }

    @JsonProperty("electronicBenefitsTransfer")
    public Optional<ElectronicBenefitsTransfer> getElectronicBenefitsTransfer() {
        return electronicBenefitsTransfer;
    }

    @JsonProperty("specialityCards")
    public Optional<SpecialityCards> getSpecialityCards() {
        return specialityCards;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Tiered3Fees && equalTo((Tiered3Fees) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Tiered3Fees other) {
        return mastercardVisaDiscover.equals(other.mastercardVisaDiscover)
                && amex.equals(other.amex)
                && pinDebit.equals(other.pinDebit)
                && electronicBenefitsTransfer.equals(other.electronicBenefitsTransfer)
                && specialityCards.equals(other.specialityCards);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.mastercardVisaDiscover,
                this.amex,
                this.pinDebit,
                this.electronicBenefitsTransfer,
                this.specialityCards);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static MastercardVisaDiscoverStage builder() {
        return new Builder();
    }

    public interface MastercardVisaDiscoverStage {
        /**
         * <p>Object that contains the fees for Mastercard, Visa, and Discover transactions.</p>
         */
        _FinalStage mastercardVisaDiscover(@NotNull QualRates mastercardVisaDiscover);

        Builder from(Tiered3Fees other);
    }

    public interface _FinalStage {
        Tiered3Fees build();

        /**
         * <p>Object that contains the fees for American Express transactions.</p>
         */
        _FinalStage amex(Optional<Tiered3FeesAmex> amex);

        _FinalStage amex(Tiered3FeesAmex amex);

        _FinalStage pinDebit(Optional<PinDebit> pinDebit);

        _FinalStage pinDebit(PinDebit pinDebit);

        _FinalStage electronicBenefitsTransfer(Optional<ElectronicBenefitsTransfer> electronicBenefitsTransfer);

        _FinalStage electronicBenefitsTransfer(ElectronicBenefitsTransfer electronicBenefitsTransfer);

        _FinalStage specialityCards(Optional<SpecialityCards> specialityCards);

        _FinalStage specialityCards(SpecialityCards specialityCards);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements MastercardVisaDiscoverStage, _FinalStage {
        private QualRates mastercardVisaDiscover;

        private Optional<SpecialityCards> specialityCards = Optional.empty();

        private Optional<ElectronicBenefitsTransfer> electronicBenefitsTransfer = Optional.empty();

        private Optional<PinDebit> pinDebit = Optional.empty();

        private Optional<Tiered3FeesAmex> amex = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(Tiered3Fees other) {
            mastercardVisaDiscover(other.getMastercardVisaDiscover());
            amex(other.getAmex());
            pinDebit(other.getPinDebit());
            electronicBenefitsTransfer(other.getElectronicBenefitsTransfer());
            specialityCards(other.getSpecialityCards());
            return this;
        }

        /**
         * <p>Object that contains the fees for Mastercard, Visa, and Discover transactions.</p>
         * <p>Object that contains the fees for Mastercard, Visa, and Discover transactions.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("mastercardVisaDiscover")
        public _FinalStage mastercardVisaDiscover(@NotNull QualRates mastercardVisaDiscover) {
            this.mastercardVisaDiscover =
                    Objects.requireNonNull(mastercardVisaDiscover, "mastercardVisaDiscover must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage specialityCards(SpecialityCards specialityCards) {
            this.specialityCards = Optional.ofNullable(specialityCards);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "specialityCards", nulls = Nulls.SKIP)
        public _FinalStage specialityCards(Optional<SpecialityCards> specialityCards) {
            this.specialityCards = specialityCards;
            return this;
        }

        @java.lang.Override
        public _FinalStage electronicBenefitsTransfer(ElectronicBenefitsTransfer electronicBenefitsTransfer) {
            this.electronicBenefitsTransfer = Optional.ofNullable(electronicBenefitsTransfer);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "electronicBenefitsTransfer", nulls = Nulls.SKIP)
        public _FinalStage electronicBenefitsTransfer(Optional<ElectronicBenefitsTransfer> electronicBenefitsTransfer) {
            this.electronicBenefitsTransfer = electronicBenefitsTransfer;
            return this;
        }

        @java.lang.Override
        public _FinalStage pinDebit(PinDebit pinDebit) {
            this.pinDebit = Optional.ofNullable(pinDebit);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "pinDebit", nulls = Nulls.SKIP)
        public _FinalStage pinDebit(Optional<PinDebit> pinDebit) {
            this.pinDebit = pinDebit;
            return this;
        }

        /**
         * <p>Object that contains the fees for American Express transactions.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage amex(Tiered3FeesAmex amex) {
            this.amex = Optional.ofNullable(amex);
            return this;
        }

        /**
         * <p>Object that contains the fees for American Express transactions.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "amex", nulls = Nulls.SKIP)
        public _FinalStage amex(Optional<Tiered3FeesAmex> amex) {
            this.amex = amex;
            return this;
        }

        @java.lang.Override
        public Tiered3Fees build() {
            return new Tiered3Fees(
                    mastercardVisaDiscover,
                    amex,
                    pinDebit,
                    electronicBenefitsTransfer,
                    specialityCards,
                    additionalProperties);
        }
    }
}
