/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TipProcessingEnabled.Builder.class)
public final class TipProcessingEnabled {
    private final boolean enabled;

    private final Optional<Boolean> tipPrompt;

    private final Optional<Boolean> tipAdjust;

    private final Optional<TipProcessingEnabledSuggestedTips> suggestedTips;

    private final Map<String, Object> additionalProperties;

    private TipProcessingEnabled(
            boolean enabled,
            Optional<Boolean> tipPrompt,
            Optional<Boolean> tipAdjust,
            Optional<TipProcessingEnabledSuggestedTips> suggestedTips,
            Map<String, Object> additionalProperties) {
        this.enabled = enabled;
        this.tipPrompt = tipPrompt;
        this.tipAdjust = tipAdjust;
        this.suggestedTips = suggestedTips;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Indicates if the terminal can accept tips.
     */
    @JsonProperty("enabled")
    public boolean getEnabled() {
        return enabled;
    }

    /**
     * @return Indicates if the terminal prompts for tips.
     */
    @JsonProperty("tipPrompt")
    public Optional<Boolean> getTipPrompt() {
        return tipPrompt;
    }

    /**
     * @return Indicates if a clerk can adjust a tip after the customer completes the sale.
     */
    @JsonProperty("tipAdjust")
    public Optional<Boolean> getTipAdjust() {
        return tipAdjust;
    }

    /**
     * @return Object that contains up to three tip amounts that the terminal displays during a sale.
     */
    @JsonProperty("suggestedTips")
    public Optional<TipProcessingEnabledSuggestedTips> getSuggestedTips() {
        return suggestedTips;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TipProcessingEnabled && equalTo((TipProcessingEnabled) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TipProcessingEnabled other) {
        return enabled == other.enabled
                && tipPrompt.equals(other.tipPrompt)
                && tipAdjust.equals(other.tipAdjust)
                && suggestedTips.equals(other.suggestedTips);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.enabled, this.tipPrompt, this.tipAdjust, this.suggestedTips);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EnabledStage builder() {
        return new Builder();
    }

    public interface EnabledStage {
        /**
         * <p>Indicates if the terminal can accept tips.</p>
         */
        _FinalStage enabled(boolean enabled);

        Builder from(TipProcessingEnabled other);
    }

    public interface _FinalStage {
        TipProcessingEnabled build();

        /**
         * <p>Indicates if the terminal prompts for tips.</p>
         */
        _FinalStage tipPrompt(Optional<Boolean> tipPrompt);

        _FinalStage tipPrompt(Boolean tipPrompt);

        /**
         * <p>Indicates if a clerk can adjust a tip after the customer completes the sale.</p>
         */
        _FinalStage tipAdjust(Optional<Boolean> tipAdjust);

        _FinalStage tipAdjust(Boolean tipAdjust);

        /**
         * <p>Object that contains up to three tip amounts that the terminal displays during a sale.</p>
         */
        _FinalStage suggestedTips(Optional<TipProcessingEnabledSuggestedTips> suggestedTips);

        _FinalStage suggestedTips(TipProcessingEnabledSuggestedTips suggestedTips);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements EnabledStage, _FinalStage {
        private boolean enabled;

        private Optional<TipProcessingEnabledSuggestedTips> suggestedTips = Optional.empty();

        private Optional<Boolean> tipAdjust = Optional.empty();

        private Optional<Boolean> tipPrompt = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(TipProcessingEnabled other) {
            enabled(other.getEnabled());
            tipPrompt(other.getTipPrompt());
            tipAdjust(other.getTipAdjust());
            suggestedTips(other.getSuggestedTips());
            return this;
        }

        /**
         * <p>Indicates if the terminal can accept tips.</p>
         * <p>Indicates if the terminal can accept tips.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("enabled")
        public _FinalStage enabled(boolean enabled) {
            this.enabled = enabled;
            return this;
        }

        /**
         * <p>Object that contains up to three tip amounts that the terminal displays during a sale.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage suggestedTips(TipProcessingEnabledSuggestedTips suggestedTips) {
            this.suggestedTips = Optional.ofNullable(suggestedTips);
            return this;
        }

        /**
         * <p>Object that contains up to three tip amounts that the terminal displays during a sale.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "suggestedTips", nulls = Nulls.SKIP)
        public _FinalStage suggestedTips(Optional<TipProcessingEnabledSuggestedTips> suggestedTips) {
            this.suggestedTips = suggestedTips;
            return this;
        }

        /**
         * <p>Indicates if a clerk can adjust a tip after the customer completes the sale.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage tipAdjust(Boolean tipAdjust) {
            this.tipAdjust = Optional.ofNullable(tipAdjust);
            return this;
        }

        /**
         * <p>Indicates if a clerk can adjust a tip after the customer completes the sale.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "tipAdjust", nulls = Nulls.SKIP)
        public _FinalStage tipAdjust(Optional<Boolean> tipAdjust) {
            this.tipAdjust = tipAdjust;
            return this;
        }

        /**
         * <p>Indicates if the terminal prompts for tips.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage tipPrompt(Boolean tipPrompt) {
            this.tipPrompt = Optional.ofNullable(tipPrompt);
            return this;
        }

        /**
         * <p>Indicates if the terminal prompts for tips.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "tipPrompt", nulls = Nulls.SKIP)
        public _FinalStage tipPrompt(Optional<Boolean> tipPrompt) {
            this.tipPrompt = tipPrompt;
            return this;
        }

        @java.lang.Override
        public TipProcessingEnabled build() {
            return new TipProcessingEnabled(enabled, tipPrompt, tipAdjust, suggestedTips, additionalProperties);
        }
    }
}
