/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.resources.funding.fundingactivity;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.payroc.api.core.ClientOptions;
import com.payroc.api.core.ObjectMappers;
import com.payroc.api.core.PayrocApiApiException;
import com.payroc.api.core.PayrocApiException;
import com.payroc.api.core.PayrocApiHttpResponse;
import com.payroc.api.core.QueryStringMapper;
import com.payroc.api.core.RequestOptions;
import com.payroc.api.core.pagination.PayrocPager;
import com.payroc.api.errors.BadRequestError;
import com.payroc.api.errors.ForbiddenError;
import com.payroc.api.errors.InternalServerError;
import com.payroc.api.errors.NotAcceptableError;
import com.payroc.api.errors.UnauthorizedError;
import com.payroc.api.resources.funding.fundingactivity.requests.ListFundingActivityRequest;
import com.payroc.api.resources.funding.fundingactivity.requests.RetrieveBalanceFundingActivityRequest;
import com.payroc.api.resources.funding.fundingactivity.types.ListFundingActivityResponse;
import com.payroc.api.resources.funding.fundingactivity.types.RetrieveBalanceFundingActivityResponse;
import com.payroc.api.types.ActivityRecord;
import com.payroc.api.types.FiveHundred;
import com.payroc.api.types.FourHundred;
import com.payroc.api.types.FourHundredOne;
import com.payroc.api.types.FourHundredSix;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawFundingActivityClient {
    protected final ClientOptions clientOptions;

    public RawFundingActivityClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Use this method to return a <a href="https://docs.payroc.com/api/pagination">paginated</a> list of funding balances available for each merchant linked to your account.
     * <p>Use query parameters to filter the list of results we return, for example, to search for the funding balance for a specific merchant.</p>
     * <p>Our gateway returns the following information about each merchant in the list:</p>
     * <ul>
     * <li>Total funds for the merchant.</li>
     * <li>Available funds that you can use for funding instructions.</li>
     * <li>Pending funds that we have not yet sent to funding accounts.</li>
     * </ul>
     */
    public PayrocApiHttpResponse<RetrieveBalanceFundingActivityResponse> retrieveBalance() {
        return retrieveBalance(RetrieveBalanceFundingActivityRequest.builder().build());
    }

    /**
     * Use this method to return a <a href="https://docs.payroc.com/api/pagination">paginated</a> list of funding balances available for each merchant linked to your account.
     * <p>Use query parameters to filter the list of results we return, for example, to search for the funding balance for a specific merchant.</p>
     * <p>Our gateway returns the following information about each merchant in the list:</p>
     * <ul>
     * <li>Total funds for the merchant.</li>
     * <li>Available funds that you can use for funding instructions.</li>
     * <li>Pending funds that we have not yet sent to funding accounts.</li>
     * </ul>
     */
    public PayrocApiHttpResponse<RetrieveBalanceFundingActivityResponse> retrieveBalance(
            RequestOptions requestOptions) {
        return retrieveBalance(RetrieveBalanceFundingActivityRequest.builder().build(), requestOptions);
    }

    /**
     * Use this method to return a <a href="https://docs.payroc.com/api/pagination">paginated</a> list of funding balances available for each merchant linked to your account.
     * <p>Use query parameters to filter the list of results we return, for example, to search for the funding balance for a specific merchant.</p>
     * <p>Our gateway returns the following information about each merchant in the list:</p>
     * <ul>
     * <li>Total funds for the merchant.</li>
     * <li>Available funds that you can use for funding instructions.</li>
     * <li>Pending funds that we have not yet sent to funding accounts.</li>
     * </ul>
     */
    public PayrocApiHttpResponse<RetrieveBalanceFundingActivityResponse> retrieveBalance(
            RetrieveBalanceFundingActivityRequest request) {
        return retrieveBalance(request, null);
    }

    /**
     * Use this method to return a <a href="https://docs.payroc.com/api/pagination">paginated</a> list of funding balances available for each merchant linked to your account.
     * <p>Use query parameters to filter the list of results we return, for example, to search for the funding balance for a specific merchant.</p>
     * <p>Our gateway returns the following information about each merchant in the list:</p>
     * <ul>
     * <li>Total funds for the merchant.</li>
     * <li>Available funds that you can use for funding instructions.</li>
     * <li>Pending funds that we have not yet sent to funding accounts.</li>
     * </ul>
     */
    public PayrocApiHttpResponse<RetrieveBalanceFundingActivityResponse> retrieveBalance(
            RetrieveBalanceFundingActivityRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getApiURL())
                .newBuilder()
                .addPathSegments("funding-balance");
        if (request.getBefore().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "before", request.getBefore().get(), false);
        }
        if (request.getAfter().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "after", request.getAfter().get(), false);
        }
        if (request.getLimit().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "limit", request.getLimit().get(), false);
        }
        if (request.getMerchantId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "merchantId", request.getMerchantId().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new PayrocApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBodyString, RetrieveBalanceFundingActivityResponse.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundred.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredOne.class),
                                response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 406:
                        throw new NotAcceptableError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredSix.class),
                                response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FiveHundred.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new PayrocApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new PayrocApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Use this method to return a <a href="https://docs.payroc.com/api/pagination">paginated</a> list of activity associated with your merchants' funding balances within a specific date range.
     * <p>Use query parameters to filter the list of results we return, for example, to view the activity for a specific merchant's funding balance.</p>
     * <p>Our gateway returns the following information about each activity in the list:</p>
     * <ul>
     * <li>Name of the merchant who owns the funding balance.</li>
     * <li>Amount of funds added or removed from the funding balance.</li>
     * <li>Funding account that received funds from the funding balance.</li>
     * </ul>
     */
    public PayrocApiHttpResponse<PayrocPager<ActivityRecord>> list(ListFundingActivityRequest request) {
        return list(request, null);
    }

    /**
     * Use this method to return a <a href="https://docs.payroc.com/api/pagination">paginated</a> list of activity associated with your merchants' funding balances within a specific date range.
     * <p>Use query parameters to filter the list of results we return, for example, to view the activity for a specific merchant's funding balance.</p>
     * <p>Our gateway returns the following information about each activity in the list:</p>
     * <ul>
     * <li>Name of the merchant who owns the funding balance.</li>
     * <li>Amount of funds added or removed from the funding balance.</li>
     * <li>Funding account that received funds from the funding balance.</li>
     * </ul>
     */
    public PayrocApiHttpResponse<PayrocPager<ActivityRecord>> list(
            ListFundingActivityRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getApiURL())
                .newBuilder()
                .addPathSegments("funding-activity");
        if (request.getBefore().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "before", request.getBefore().get(), false);
        }
        if (request.getAfter().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "after", request.getAfter().get(), false);
        }
        if (request.getLimit().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "limit", request.getLimit().get(), false);
        }
        QueryStringMapper.addQueryParameter(httpUrl, "dateFrom", request.getDateFrom(), false);
        QueryStringMapper.addQueryParameter(httpUrl, "dateTo", request.getDateTo(), false);
        if (request.getMerchantId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "merchantId", request.getMerchantId().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                ListFundingActivityResponse parsedResponse =
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListFundingActivityResponse.class);
                return new PayrocApiHttpResponse<>(
                        PayrocPager.create(parsedResponse, clientOptions, requestOptions), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundred.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredOne.class),
                                response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 406:
                        throw new NotAcceptableError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredSix.class),
                                response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FiveHundred.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new PayrocApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new PayrocApiException("Network error executing HTTP request", e);
        }
    }
}
