/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.resources.auth;

import com.payroc.api.core.ClientOptions;
import com.payroc.api.core.RequestOptions;
import com.payroc.api.resources.auth.requests.RetrieveTokenAuthRequest;
import com.payroc.api.resources.auth.types.GetTokenResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncAuthClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawAuthClient rawClient;

    public AsyncAuthClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawAuthClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawAuthClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Obtain an access token using client credentials
     */
    public CompletableFuture<GetTokenResponse> retrieveToken(RetrieveTokenAuthRequest request) {
        return this.rawClient.retrieveToken(request).thenApply(response -> response.body());
    }

    /**
     * Obtain an access token using client credentials
     */
    public CompletableFuture<GetTokenResponse> retrieveToken(
            RetrieveTokenAuthRequest request, RequestOptions requestOptions) {
        return this.rawClient.retrieveToken(request, requestOptions).thenApply(response -> response.body());
    }
}
