/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.errors;

import com.payroc.api.core.PayrocApiApiException;
import com.payroc.api.types.FourHundredFifteen;
import okhttp3.Response;

public final class UnsupportedMediaTypeError extends PayrocApiApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final FourHundredFifteen body;

    public UnsupportedMediaTypeError(FourHundredFifteen body) {
        super("UnsupportedMediaTypeError", 415, body);
        this.body = body;
    }

    public UnsupportedMediaTypeError(FourHundredFifteen body, Response rawResponse) {
        super("UnsupportedMediaTypeError", 415, body, rawResponse);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public FourHundredFifteen body() {
        return this.body;
    }
}
