/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.resources.paymentfeatures.cards;

import com.payroc.api.core.ClientOptions;
import com.payroc.api.core.RequestOptions;
import com.payroc.api.resources.paymentfeatures.cards.requests.BalanceInquiry;
import com.payroc.api.resources.paymentfeatures.cards.requests.BinLookup;
import com.payroc.api.resources.paymentfeatures.cards.requests.CardVerificationRequest;
import com.payroc.api.resources.paymentfeatures.cards.requests.FxRateInquiry;
import com.payroc.api.types.Balance;
import com.payroc.api.types.CardInfo;
import com.payroc.api.types.CardVerificationResult;
import com.payroc.api.types.FxRate;

public class CardsClient {
    protected final ClientOptions clientOptions;

    private final RawCardsClient rawClient;

    public CardsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawCardsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawCardsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Use this method to verify a customer’s card details.
     * <p>In the request, send the customer’s card details.</p>
     * <p>In the response, our gateway indicates if the card details are valid and if you should use them in follow-on actions.</p>
     */
    public CardVerificationResult verifyCard(CardVerificationRequest request) {
        return this.rawClient.verifyCard(request).body();
    }

    /**
     * Use this method to verify a customer’s card details.
     * <p>In the request, send the customer’s card details.</p>
     * <p>In the response, our gateway indicates if the card details are valid and if you should use them in follow-on actions.</p>
     */
    public CardVerificationResult verifyCard(CardVerificationRequest request, RequestOptions requestOptions) {
        return this.rawClient.verifyCard(request, requestOptions).body();
    }

    /**
     * Use this method to view the balance of an Electronic Benefit Transfer (EBT) card.
     * <p>If the request is successful, our gateway returns the current balance of an EBT card.</p>
     */
    public Balance viewEbtBalance(BalanceInquiry request) {
        return this.rawClient.viewEbtBalance(request).body();
    }

    /**
     * Use this method to view the balance of an Electronic Benefit Transfer (EBT) card.
     * <p>If the request is successful, our gateway returns the current balance of an EBT card.</p>
     */
    public Balance viewEbtBalance(BalanceInquiry request, RequestOptions requestOptions) {
        return this.rawClient.viewEbtBalance(request, requestOptions).body();
    }

    /**
     * Use this method to retrieve information about a debit card, a credit card, or an EBT card. If you apply surcharges to transactions, you can also check if the card supports surcharging.
     * <p>In the response, our gateway returns the following information about the card:</p>
     * <ul>
     * <li>
     * <p><strong>Card details</strong> - Information about the card, for example, the issuing bank and the masked card number.</p>
     * </li>
     * <li>
     * <p><strong>Surcharging information</strong> - If you apply a surcharge to transactions, our gateway checks that the card supports surcharging and returns information about the surcharge. For more information about surcharging, go to <a href="https://docs.payroc.com/knowledge/card-payments/credit-card-surcharging">Credit card surcharging</a>.</p>
     * </li>
     * </ul>
     */
    public CardInfo lookupBin(BinLookup request) {
        return this.rawClient.lookupBin(request).body();
    }

    /**
     * Use this method to retrieve information about a debit card, a credit card, or an EBT card. If you apply surcharges to transactions, you can also check if the card supports surcharging.
     * <p>In the response, our gateway returns the following information about the card:</p>
     * <ul>
     * <li>
     * <p><strong>Card details</strong> - Information about the card, for example, the issuing bank and the masked card number.</p>
     * </li>
     * <li>
     * <p><strong>Surcharging information</strong> - If you apply a surcharge to transactions, our gateway checks that the card supports surcharging and returns information about the surcharge. For more information about surcharging, go to <a href="https://docs.payroc.com/knowledge/card-payments/credit-card-surcharging">Credit card surcharging</a>.</p>
     * </li>
     * </ul>
     */
    public CardInfo lookupBin(BinLookup request, RequestOptions requestOptions) {
        return this.rawClient.lookupBin(request, requestOptions).body();
    }

    /**
     * <blockquote>
     * <strong>Important:</strong> There are restrictions on which merchants can use this method. For more information, go to <a href="https://docs.payroc.com/knowledge/card-payments/dynamic-currency-conversion">Dynamic Currency Conversion</a>.
     * </blockquote>
     * <p>Use this method to check if a card is eligible for Dynamic Currency Conversion (DCC) and to retrieve the conversion rate for a transaction amount. DCC provides a customer with the option to use their card's currency instead of the merchant's currency, for example, in Ireland, an American customer can pay in US dollars instead of Euros.</p>
     * <p>The request includes the following:</p>
     * <ul>
     * <li><strong>Payment method</strong> - Card information, a secure token, or digital wallet.</li>
     * <li><strong>Transaction information</strong> - Amount and currency of the transaction in the merchant's currency.</li>
     * </ul>
     * <p>If the card is eligible for DCC, our gateway returns the transaction amount in the card's currency and a dccOffer object that contains information about the conversion rate. The dccOffer object contains the following fields that you need when you <a href="https://docs.payroc.com/api/schema/card-payments/payments/create">run a sale</a> or <a href="https://docs.payroc.com/api/schema/card-payments/refunds/create-unreferenced-refund">unreferenced refund</a> with DCC:</p>
     * <ul>
     * <li>fxAmount</li>
     * <li>fxCurrency</li>
     * <li>fxRate</li>
     * <li>markup</li>
     * <li>accepted</li>
     * <li>offerReference</li>
     * </ul>
     */
    public FxRate retrieveFxRates(FxRateInquiry request) {
        return this.rawClient.retrieveFxRates(request).body();
    }

    /**
     * <blockquote>
     * <strong>Important:</strong> There are restrictions on which merchants can use this method. For more information, go to <a href="https://docs.payroc.com/knowledge/card-payments/dynamic-currency-conversion">Dynamic Currency Conversion</a>.
     * </blockquote>
     * <p>Use this method to check if a card is eligible for Dynamic Currency Conversion (DCC) and to retrieve the conversion rate for a transaction amount. DCC provides a customer with the option to use their card's currency instead of the merchant's currency, for example, in Ireland, an American customer can pay in US dollars instead of Euros.</p>
     * <p>The request includes the following:</p>
     * <ul>
     * <li><strong>Payment method</strong> - Card information, a secure token, or digital wallet.</li>
     * <li><strong>Transaction information</strong> - Amount and currency of the transaction in the merchant's currency.</li>
     * </ul>
     * <p>If the card is eligible for DCC, our gateway returns the transaction amount in the card's currency and a dccOffer object that contains information about the conversion rate. The dccOffer object contains the following fields that you need when you <a href="https://docs.payroc.com/api/schema/card-payments/payments/create">run a sale</a> or <a href="https://docs.payroc.com/api/schema/card-payments/refunds/create-unreferenced-refund">unreferenced refund</a> with DCC:</p>
     * <ul>
     * <li>fxAmount</li>
     * <li>fxCurrency</li>
     * <li>fxRate</li>
     * <li>markup</li>
     * <li>accepted</li>
     * <li>offerReference</li>
     * </ul>
     */
    public FxRate retrieveFxRates(FxRateInquiry request, RequestOptions requestOptions) {
        return this.rawClient.retrieveFxRates(request, requestOptions).body();
    }
}
