/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.resources.cardpayments.payments.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PaymentRequestChannel {
    public static final PaymentRequestChannel WEB = new PaymentRequestChannel(Value.WEB, "web");

    public static final PaymentRequestChannel MOTO = new PaymentRequestChannel(Value.MOTO, "moto");

    public static final PaymentRequestChannel POS = new PaymentRequestChannel(Value.POS, "pos");

    private final Value value;

    private final String string;

    PaymentRequestChannel(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PaymentRequestChannel
                        && this.string.equals(((PaymentRequestChannel) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case WEB:
                return visitor.visitWeb();
            case MOTO:
                return visitor.visitMoto();
            case POS:
                return visitor.visitPos();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PaymentRequestChannel valueOf(String value) {
        switch (value) {
            case "web":
                return WEB;
            case "moto":
                return MOTO;
            case "pos":
                return POS;
            default:
                return new PaymentRequestChannel(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        POS,

        WEB,

        MOTO,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitPos();

        T visitWeb();

        T visitMoto();

        T visitUnknown(String unknownType);
    }
}
