/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.resources.boarding.contacts;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.payroc.api.core.ClientOptions;
import com.payroc.api.core.MediaTypes;
import com.payroc.api.core.ObjectMappers;
import com.payroc.api.core.PayrocApiApiException;
import com.payroc.api.core.PayrocApiException;
import com.payroc.api.core.PayrocApiHttpResponse;
import com.payroc.api.core.RequestOptions;
import com.payroc.api.errors.BadRequestError;
import com.payroc.api.errors.ForbiddenError;
import com.payroc.api.errors.InternalServerError;
import com.payroc.api.errors.NotAcceptableError;
import com.payroc.api.errors.NotFoundError;
import com.payroc.api.errors.UnauthorizedError;
import com.payroc.api.resources.boarding.contacts.requests.DeleteContactsRequest;
import com.payroc.api.resources.boarding.contacts.requests.RetrieveContactsRequest;
import com.payroc.api.resources.boarding.contacts.requests.UpdateContactsRequest;
import com.payroc.api.types.Contact;
import com.payroc.api.types.FiveHundred;
import com.payroc.api.types.FourHundred;
import com.payroc.api.types.FourHundredFour;
import com.payroc.api.types.FourHundredOne;
import com.payroc.api.types.FourHundredSix;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawContactsClient {
    protected final ClientOptions clientOptions;

    public AsyncRawContactsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Use this method to retrieve details about a contact.
     * <p>To retrieve a contact, you need its contactId. Our gateway returned the contactId in the <a href="https://docs.payroc.com/api/schema/boarding/merchant-platforms/create-processing-account">Create Processing Account</a> method.</p>
     * <p><strong>Note:</strong> If you don't have the contactId, use the <a href="https://docs.payroc.com/api/schema/boarding/processing-accounts/list-contacts">List Contacts</a> method to search for the contact.</p>
     * <p>Our gateway returns the following information about a contact:</p>
     * <ul>
     * <li>Name and contact method, including their phone number or mobile number.</li>
     * <li>Role within the business, for example, if they are a manager.</li>
     * </ul>
     */
    public CompletableFuture<PayrocApiHttpResponse<Contact>> retrieve(int contactId) {
        return retrieve(contactId, RetrieveContactsRequest.builder().build());
    }

    /**
     * Use this method to retrieve details about a contact.
     * <p>To retrieve a contact, you need its contactId. Our gateway returned the contactId in the <a href="https://docs.payroc.com/api/schema/boarding/merchant-platforms/create-processing-account">Create Processing Account</a> method.</p>
     * <p><strong>Note:</strong> If you don't have the contactId, use the <a href="https://docs.payroc.com/api/schema/boarding/processing-accounts/list-contacts">List Contacts</a> method to search for the contact.</p>
     * <p>Our gateway returns the following information about a contact:</p>
     * <ul>
     * <li>Name and contact method, including their phone number or mobile number.</li>
     * <li>Role within the business, for example, if they are a manager.</li>
     * </ul>
     */
    public CompletableFuture<PayrocApiHttpResponse<Contact>> retrieve(int contactId, RetrieveContactsRequest request) {
        return retrieve(contactId, request, null);
    }

    /**
     * Use this method to retrieve details about a contact.
     * <p>To retrieve a contact, you need its contactId. Our gateway returned the contactId in the <a href="https://docs.payroc.com/api/schema/boarding/merchant-platforms/create-processing-account">Create Processing Account</a> method.</p>
     * <p><strong>Note:</strong> If you don't have the contactId, use the <a href="https://docs.payroc.com/api/schema/boarding/processing-accounts/list-contacts">List Contacts</a> method to search for the contact.</p>
     * <p>Our gateway returns the following information about a contact:</p>
     * <ul>
     * <li>Name and contact method, including their phone number or mobile number.</li>
     * <li>Role within the business, for example, if they are a manager.</li>
     * </ul>
     */
    public CompletableFuture<PayrocApiHttpResponse<Contact>> retrieve(
            int contactId, RetrieveContactsRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getApiURL())
                .newBuilder()
                .addPathSegments("contacts")
                .addPathSegment(Integer.toString(contactId))
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<PayrocApiHttpResponse<Contact>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new PayrocApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Contact.class), response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundred.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredOne.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredFour.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FiveHundred.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new PayrocApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new PayrocApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PayrocApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Use this method to update a contact of a processing account.
     * <p>To update a contact, you need its contactId. Our gateway returned the contactId in the response of the <a href="https://docs.payroc.com/api/schema/boarding/merchant-platforms/create-processing-account">Create Processing Account</a> method.</p>
     * <p><strong>Note:</strong> If you don't have the contactId, use our <a href="https://docs.payroc.com/api/schema/boarding/processing-accounts/list-contacts">List Contacts</a> method to search for the contact.</p>
     * <p>You can update the following details about a contact:</p>
     * <ul>
     * <li>First name and last name.</li>
     * <li>Contact details, including their phone number or mobile number.</li>
     * <li>Identification details, including their identification type and number.</li>
     * <li>Role within the business, for example, if they are a manager.</li>
     * </ul>
     */
    public CompletableFuture<PayrocApiHttpResponse<Void>> update(int contactId, UpdateContactsRequest request) {
        return update(contactId, request, null);
    }

    /**
     * Use this method to update a contact of a processing account.
     * <p>To update a contact, you need its contactId. Our gateway returned the contactId in the response of the <a href="https://docs.payroc.com/api/schema/boarding/merchant-platforms/create-processing-account">Create Processing Account</a> method.</p>
     * <p><strong>Note:</strong> If you don't have the contactId, use our <a href="https://docs.payroc.com/api/schema/boarding/processing-accounts/list-contacts">List Contacts</a> method to search for the contact.</p>
     * <p>You can update the following details about a contact:</p>
     * <ul>
     * <li>First name and last name.</li>
     * <li>Contact details, including their phone number or mobile number.</li>
     * <li>Identification details, including their identification type and number.</li>
     * <li>Role within the business, for example, if they are a manager.</li>
     * </ul>
     */
    public CompletableFuture<PayrocApiHttpResponse<Void>> update(
            int contactId, UpdateContactsRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getApiURL())
                .newBuilder()
                .addPathSegments("contacts")
                .addPathSegment(Integer.toString(contactId))
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new PayrocApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("PUT", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<PayrocApiHttpResponse<Void>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new PayrocApiHttpResponse<>(null, response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundred.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredOne.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredFour.class),
                                        response));
                                return;
                            case 406:
                                future.completeExceptionally(new NotAcceptableError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredSix.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FiveHundred.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new PayrocApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new PayrocApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PayrocApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Use this method to delete a contact associated with a processing account.
     * <p>To delete a contact, you need their contactId. Our gateway returned the contactId in the response of the <a href="https://docs.payroc.com/api/schema/boarding/merchant-platforms/create-processing-account">Create Processing Account</a> method.</p>
     * <p><strong>Note:</strong> If you don’t have the contactId, use our <a href="https://docs.payroc.com/api/schema/boarding/processing-accounts/retrieve">Retrieve Processing Account</a> method or our <a href="https://docs.payroc.com/api/schema/boarding/processing-accounts/list-contacts">List Contacts</a> method to search for the contact.</p>
     */
    public CompletableFuture<PayrocApiHttpResponse<Void>> delete(int contactId) {
        return delete(contactId, DeleteContactsRequest.builder().build());
    }

    /**
     * Use this method to delete a contact associated with a processing account.
     * <p>To delete a contact, you need their contactId. Our gateway returned the contactId in the response of the <a href="https://docs.payroc.com/api/schema/boarding/merchant-platforms/create-processing-account">Create Processing Account</a> method.</p>
     * <p><strong>Note:</strong> If you don’t have the contactId, use our <a href="https://docs.payroc.com/api/schema/boarding/processing-accounts/retrieve">Retrieve Processing Account</a> method or our <a href="https://docs.payroc.com/api/schema/boarding/processing-accounts/list-contacts">List Contacts</a> method to search for the contact.</p>
     */
    public CompletableFuture<PayrocApiHttpResponse<Void>> delete(int contactId, DeleteContactsRequest request) {
        return delete(contactId, request, null);
    }

    /**
     * Use this method to delete a contact associated with a processing account.
     * <p>To delete a contact, you need their contactId. Our gateway returned the contactId in the response of the <a href="https://docs.payroc.com/api/schema/boarding/merchant-platforms/create-processing-account">Create Processing Account</a> method.</p>
     * <p><strong>Note:</strong> If you don’t have the contactId, use our <a href="https://docs.payroc.com/api/schema/boarding/processing-accounts/retrieve">Retrieve Processing Account</a> method or our <a href="https://docs.payroc.com/api/schema/boarding/processing-accounts/list-contacts">List Contacts</a> method to search for the contact.</p>
     */
    public CompletableFuture<PayrocApiHttpResponse<Void>> delete(
            int contactId, DeleteContactsRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getApiURL())
                .newBuilder()
                .addPathSegments("contacts")
                .addPathSegment(Integer.toString(contactId))
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<PayrocApiHttpResponse<Void>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new PayrocApiHttpResponse<>(null, response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundred.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredOne.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FourHundredFour.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, FiveHundred.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new PayrocApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new PayrocApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PayrocApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
