/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.resources.attachments.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UploadToProcessingAccountAttachmentsRequestAttachment.Builder.class)
public final class UploadToProcessingAccountAttachmentsRequestAttachment {
    private final UploadToProcessingAccountAttachmentsRequestAttachmentType type;

    private final Optional<String> description;

    private final Optional<Map<String, String>> metadata;

    private final Map<String, Object> additionalProperties;

    private UploadToProcessingAccountAttachmentsRequestAttachment(
            UploadToProcessingAccountAttachmentsRequestAttachmentType type,
            Optional<String> description,
            Optional<Map<String, String>> metadata,
            Map<String, Object> additionalProperties) {
        this.type = type;
        this.description = description;
        this.metadata = metadata;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Type of attachment.
     */
    @JsonProperty("type")
    public UploadToProcessingAccountAttachmentsRequestAttachmentType getType() {
        return type;
    }

    /**
     * @return Short description of the attachment.
     */
    @JsonProperty("description")
    public Optional<String> getDescription() {
        return description;
    }

    /**
     * @return Object that you can send to include custom metadata in the request.
     */
    @JsonProperty("metadata")
    public Optional<Map<String, String>> getMetadata() {
        return metadata;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UploadToProcessingAccountAttachmentsRequestAttachment
                && equalTo((UploadToProcessingAccountAttachmentsRequestAttachment) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UploadToProcessingAccountAttachmentsRequestAttachment other) {
        return type.equals(other.type) && description.equals(other.description) && metadata.equals(other.metadata);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type, this.description, this.metadata);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TypeStage builder() {
        return new Builder();
    }

    public interface TypeStage {
        /**
         * <p>Type of attachment.</p>
         */
        _FinalStage type(@NotNull UploadToProcessingAccountAttachmentsRequestAttachmentType type);

        Builder from(UploadToProcessingAccountAttachmentsRequestAttachment other);
    }

    public interface _FinalStage {
        UploadToProcessingAccountAttachmentsRequestAttachment build();

        /**
         * <p>Short description of the attachment.</p>
         */
        _FinalStage description(Optional<String> description);

        _FinalStage description(String description);

        /**
         * <p>Object that you can send to include custom metadata in the request.</p>
         */
        _FinalStage metadata(Optional<Map<String, String>> metadata);

        _FinalStage metadata(Map<String, String> metadata);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, _FinalStage {
        private UploadToProcessingAccountAttachmentsRequestAttachmentType type;

        private Optional<Map<String, String>> metadata = Optional.empty();

        private Optional<String> description = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UploadToProcessingAccountAttachmentsRequestAttachment other) {
            type(other.getType());
            description(other.getDescription());
            metadata(other.getMetadata());
            return this;
        }

        /**
         * <p>Type of attachment.</p>
         * <p>Type of attachment.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("type")
        public _FinalStage type(@NotNull UploadToProcessingAccountAttachmentsRequestAttachmentType type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        /**
         * <p>Object that you can send to include custom metadata in the request.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage metadata(Map<String, String> metadata) {
            this.metadata = Optional.ofNullable(metadata);
            return this;
        }

        /**
         * <p>Object that you can send to include custom metadata in the request.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "metadata", nulls = Nulls.SKIP)
        public _FinalStage metadata(Optional<Map<String, String>> metadata) {
            this.metadata = metadata;
            return this;
        }

        /**
         * <p>Short description of the attachment.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage description(String description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        /**
         * <p>Short description of the attachment.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public _FinalStage description(Optional<String> description) {
            this.description = description;
            return this;
        }

        @java.lang.Override
        public UploadToProcessingAccountAttachmentsRequestAttachment build() {
            return new UploadToProcessingAccountAttachmentsRequestAttachment(
                    type, description, metadata, additionalProperties);
        }
    }
}
