/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.resources.reporting.settlement.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListReportingSettlementAuthorizationsRequest.Builder.class)
public final class ListReportingSettlementAuthorizationsRequest {
    private final Optional<String> before;

    private final Optional<String> after;

    private final Optional<Integer> limit;

    private final Optional<LocalDate> date;

    private final Optional<Integer> batchId;

    private final Optional<String> merchantId;

    private final Map<String, Object> additionalProperties;

    private ListReportingSettlementAuthorizationsRequest(
            Optional<String> before,
            Optional<String> after,
            Optional<Integer> limit,
            Optional<LocalDate> date,
            Optional<Integer> batchId,
            Optional<String> merchantId,
            Map<String, Object> additionalProperties) {
        this.before = before;
        this.after = after;
        this.limit = limit;
        this.date = date;
        this.batchId = batchId;
        this.merchantId = merchantId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Return the previous page of results before the value that you specify.
     * <p>You can’t send the before parameter in the same request as the after parameter.</p>
     */
    @JsonProperty("before")
    public Optional<String> getBefore() {
        return before;
    }

    /**
     * @return Return the next page of results after the value that you specify.
     * <p>You can’t send the after parameter in the same request as the before parameter.</p>
     */
    @JsonProperty("after")
    public Optional<String> getAfter() {
        return after;
    }

    /**
     * @return Limit the maximum number of results that we return for each page.
     */
    @JsonProperty("limit")
    public Optional<Integer> getLimit() {
        return limit;
    }

    /**
     * @return Filter transactions by the date that the merchant submitted the batch that contains the transaction. The format of this value is <strong>YYYY-MM-DD</strong>.
     * <p>You must provide either the batchId or the date.</p>
     */
    @JsonProperty("date")
    public Optional<LocalDate> getDate() {
        return date;
    }

    /**
     * @return Filter transactions by the unique identifier of the batch that contains the transaction.
     * <p>You must provide either the batchId or the date.</p>
     */
    @JsonProperty("batchId")
    public Optional<Integer> getBatchId() {
        return batchId;
    }

    /**
     * @return Filter results by the unique identifier that the processor assigned to the merchant.
     */
    @JsonProperty("merchantId")
    public Optional<String> getMerchantId() {
        return merchantId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListReportingSettlementAuthorizationsRequest
                && equalTo((ListReportingSettlementAuthorizationsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListReportingSettlementAuthorizationsRequest other) {
        return before.equals(other.before)
                && after.equals(other.after)
                && limit.equals(other.limit)
                && date.equals(other.date)
                && batchId.equals(other.batchId)
                && merchantId.equals(other.merchantId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.before, this.after, this.limit, this.date, this.batchId, this.merchantId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> before = Optional.empty();

        private Optional<String> after = Optional.empty();

        private Optional<Integer> limit = Optional.empty();

        private Optional<LocalDate> date = Optional.empty();

        private Optional<Integer> batchId = Optional.empty();

        private Optional<String> merchantId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListReportingSettlementAuthorizationsRequest other) {
            before(other.getBefore());
            after(other.getAfter());
            limit(other.getLimit());
            date(other.getDate());
            batchId(other.getBatchId());
            merchantId(other.getMerchantId());
            return this;
        }

        /**
         * <p>Return the previous page of results before the value that you specify.</p>
         * <p>You can’t send the before parameter in the same request as the after parameter.</p>
         */
        @JsonSetter(value = "before", nulls = Nulls.SKIP)
        public Builder before(Optional<String> before) {
            this.before = before;
            return this;
        }

        public Builder before(String before) {
            this.before = Optional.ofNullable(before);
            return this;
        }

        /**
         * <p>Return the next page of results after the value that you specify.</p>
         * <p>You can’t send the after parameter in the same request as the before parameter.</p>
         */
        @JsonSetter(value = "after", nulls = Nulls.SKIP)
        public Builder after(Optional<String> after) {
            this.after = after;
            return this;
        }

        public Builder after(String after) {
            this.after = Optional.ofNullable(after);
            return this;
        }

        /**
         * <p>Limit the maximum number of results that we return for each page.</p>
         */
        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public Builder limit(Optional<Integer> limit) {
            this.limit = limit;
            return this;
        }

        public Builder limit(Integer limit) {
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        /**
         * <p>Filter transactions by the date that the merchant submitted the batch that contains the transaction. The format of this value is <strong>YYYY-MM-DD</strong>.</p>
         * <p>You must provide either the batchId or the date.</p>
         */
        @JsonSetter(value = "date", nulls = Nulls.SKIP)
        public Builder date(Optional<LocalDate> date) {
            this.date = date;
            return this;
        }

        public Builder date(LocalDate date) {
            this.date = Optional.ofNullable(date);
            return this;
        }

        /**
         * <p>Filter transactions by the unique identifier of the batch that contains the transaction.</p>
         * <p>You must provide either the batchId or the date.</p>
         */
        @JsonSetter(value = "batchId", nulls = Nulls.SKIP)
        public Builder batchId(Optional<Integer> batchId) {
            this.batchId = batchId;
            return this;
        }

        public Builder batchId(Integer batchId) {
            this.batchId = Optional.ofNullable(batchId);
            return this;
        }

        /**
         * <p>Filter results by the unique identifier that the processor assigned to the merchant.</p>
         */
        @JsonSetter(value = "merchantId", nulls = Nulls.SKIP)
        public Builder merchantId(Optional<String> merchantId) {
            this.merchantId = merchantId;
            return this;
        }

        public Builder merchantId(String merchantId) {
            this.merchantId = Optional.ofNullable(merchantId);
            return this;
        }

        public ListReportingSettlementAuthorizationsRequest build() {
            return new ListReportingSettlementAuthorizationsRequest(
                    before, after, limit, date, batchId, merchantId, additionalProperties);
        }
    }
}
