/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.payroc.api.resources.tokenization.securetokens.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.payroc.api.core.ObjectMappers;
import com.payroc.api.types.PatchDocument;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PartiallyUpdateSecureTokensRequest.Builder.class)
public final class PartiallyUpdateSecureTokensRequest {
    private final String idempotencyKey;

    private final List<PatchDocument> body;

    private final Map<String, Object> additionalProperties;

    private PartiallyUpdateSecureTokensRequest(
            String idempotencyKey, List<PatchDocument> body, Map<String, Object> additionalProperties) {
        this.idempotencyKey = idempotencyKey;
        this.body = body;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Unique identifier that you generate for each request. You must use the <a href="https://www.rfc-editor.org/rfc/rfc4122">UUID v4 format</a> for the identifier. For more information about the idempotency key, go to <a href="https://docs.payroc.com/api/idempotency">Idempotency</a>.
     */
    @JsonIgnore
    public String getIdempotencyKey() {
        return idempotencyKey;
    }

    @JsonProperty("body")
    public List<PatchDocument> getBody() {
        return body;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PartiallyUpdateSecureTokensRequest
                && equalTo((PartiallyUpdateSecureTokensRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PartiallyUpdateSecureTokensRequest other) {
        return idempotencyKey.equals(other.idempotencyKey) && body.equals(other.body);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.idempotencyKey, this.body);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdempotencyKeyStage builder() {
        return new Builder();
    }

    public interface IdempotencyKeyStage {
        /**
         * <p>Unique identifier that you generate for each request. You must use the <a href="https://www.rfc-editor.org/rfc/rfc4122">UUID v4 format</a> for the identifier. For more information about the idempotency key, go to <a href="https://docs.payroc.com/api/idempotency">Idempotency</a>.</p>
         */
        _FinalStage idempotencyKey(@NotNull String idempotencyKey);

        Builder from(PartiallyUpdateSecureTokensRequest other);
    }

    public interface _FinalStage {
        PartiallyUpdateSecureTokensRequest build();

        _FinalStage body(List<PatchDocument> body);

        _FinalStage addBody(PatchDocument body);

        _FinalStage addAllBody(List<PatchDocument> body);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements IdempotencyKeyStage, _FinalStage {
        private String idempotencyKey;

        private List<PatchDocument> body = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PartiallyUpdateSecureTokensRequest other) {
            idempotencyKey(other.getIdempotencyKey());
            body(other.getBody());
            return this;
        }

        /**
         * <p>Unique identifier that you generate for each request. You must use the <a href="https://www.rfc-editor.org/rfc/rfc4122">UUID v4 format</a> for the identifier. For more information about the idempotency key, go to <a href="https://docs.payroc.com/api/idempotency">Idempotency</a>.</p>
         * <p>Unique identifier that you generate for each request. You must use the <a href="https://www.rfc-editor.org/rfc/rfc4122">UUID v4 format</a> for the identifier. For more information about the idempotency key, go to <a href="https://docs.payroc.com/api/idempotency">Idempotency</a>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage idempotencyKey(@NotNull String idempotencyKey) {
            this.idempotencyKey = Objects.requireNonNull(idempotencyKey, "idempotencyKey must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllBody(List<PatchDocument> body) {
            if (body != null) {
                this.body.addAll(body);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addBody(PatchDocument body) {
            this.body.add(body);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "body", nulls = Nulls.SKIP)
        public _FinalStage body(List<PatchDocument> body) {
            this.body.clear();
            if (body != null) {
                this.body.addAll(body);
            }
            return this;
        }

        @java.lang.Override
        public PartiallyUpdateSecureTokensRequest build() {
            return new PartiallyUpdateSecureTokensRequest(idempotencyKey, body, additionalProperties);
        }
    }
}
